[JDBC 라이브러리 구현하기 - 3단계] 레넌(조형래) 미션 제출합니다.
woowacourse/java-jdbc pull request #248
Opened 2022-10-11 10:29 UTC by brorae

안녕하세요 알린~
3단계도 리뷰 잘 부탁드립니다 !

2022-10-13 06:04 UTC, OzRagwort requested changes
안녕하세요 레넌

마지막 3단계 잘 구현해주셨어요!

레넌의 의견이 궁금한 것들 의주로 간단한 코멘트 남겨봤습니다!

2022-10-13 06:04 UTC, OzRagwort commented on app/src/test/java/com/techcourse/dao/UserHistoryDaoTest.java
> +                new UserHistory(1L, 1L, "brorae", "password", "brorae@woowa.com", "2022-11-11")))
userHistoryDao.log()가 void를 반환하다가 int를 반환하도록 수정이 되었네요 

어떤 값을 반환하는 건지 왜 반환하게 하셨는지 궁금해요! 

혹시 내가 의도한대로 반환될때와 아닌 경우 반환값이 다르다면 그 반환값으로 테스트를 더 자세하게 할 수 있을 것 같기도 해요!

2022-10-14 01:35 UTC, brorae commented on app/src/test/java/com/techcourse/dao/UserHistoryDaoTest.java
> +                new UserHistory(1L, 1L, "brorae", "password", "brorae@woowa.com", "2022-11-11")))
jdbctemplate에서 update 메서드 활용 시에 반영된 레코드의 값을 리턴해주고 있는데요. log 에서도 update를 진행하기 때문에 int 형 반환을 해주었습니다 ! 테스트는 int 값을 확인해주도록 변경했습니다!

2022-10-14 01:44 UTC, brorae commented on app/src/main/java/com/techcourse/service/TxUserService.java
> +        userService.insert(user);
요구사항이 changePassword 부분을 트랜잭션으로 만드는 것이라고 생각되어서 insert는 적용하지 않았는데, insert도 적용하는 것이 맞는 것 같네요! 중복코드는 JdbcTemplate에서 적용했던 것 처럼 Executor 인터페이스를 만들어서 적용했습니다 !

2022-10-14 02:15 UTC, brorae commented on jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
> -        verify(conn).close();
`DataSourceUtils.releaseConnection(conn, dataSource);`을 활용했습니다!
트랜잭션 동기화 매니저에 트랜잭션 커넥션이 있으면 커넥션을 닫지 않고 유지 시켜주고, 없으면 커넥션을 닫을 수 있네요 !

2022-10-14 05:58 UTC, OzRagwort requested changes
안녕하세요 레넌 모두 잘 마무리 해주신 것 같아요

approve해도 될 것 같았는데 사소한 점 두 가지만 고쳐주시면 바로 approve할게요!

2022-10-14 05:58 UTC, OzRagwort commented on jdbc/src/main/java/nextstep/jdbc/DatabasePopulatorUtils.java
> +            } catch (SQLException ignored) {
지금은 이 클래스가 사용되지 않고 있어요 남겨둘 필요가 없을 것 같아요!

2022-10-14 05:58 UTC, OzRagwort commented on app/src/test/java/com/techcourse/dao/UserHistoryDaoTest.java
> +                userHistoryDao.log(new UserHistory(1L, 1L, "brorae", "password", "brorae@woowa.com", "2022-11-11"))
단순 의견) 테스트는 무엇을 테스트하고있는지 어떻게 테스트하고 있는지를 한눈에 볼 수 있어야 한다고 생각해요 이렇게 한번에 사용하면 메서드는 짧아지겠지만 가독성이 좀 떨어질 것 같습니다

2022-10-14 06:07 UTC, OzRagwort commented on jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
> -        verify(conn).close();
아 그리고 이거 다시 추가해주세요!

2022-10-14 06:29 UTC, brorae commented on app/src/test/java/com/techcourse/dao/UserHistoryDaoTest.java
> +                userHistoryDao.log(new UserHistory(1L, 1L, "brorae", "password", "brorae@woowa.com", "2022-11-11"))
알린의 의견에도 동의합니다 ! Displayname으로 설명을 적어주는 방법도 있을 것 같아요 ! 평소에는 한글 메서드나 DisplayName을 쓰는 편인데 단순 미션이라 간단하게 메서드 이름을 적었습니다~ㅎㅎ

2022-10-14 06:43 UTC, OzRagwort approved these changes

2022-10-14 06:43 UTC, merged