[JDBC 라이브러리 구현하기 - 1단계] 로빈(임수빈) 미션 제출합니다.
woowacourse/java-jdbc pull request #610
Opened 2024-10-02 01:17 UTC by robinjoon

안녕하세요 초롱! 리뷰어로 만나니까 새롭네요. 리뷰 잘 부탁드립니다!

간단하게 JdbcTemplate에 두 종류의 메서드를 추가했습니다. 자원 close 하는 부분은 아직 신경쓰지 않았습니다. 좋은 방법이 있을지 생각해보는 중이라서요. 무작정 닫아버리니까 닫힌 자원이라는 예외가 발생하더라구요.

2024-10-02 01:19 UTC, robinjoon commented on app/src/main/java/com/techcourse/support/jdbc/init/DatabasePopulatorUtils.java
> +            final var sql = Files.readString(path);
원래 구현대로 하니 프로젝트 경로에 한글이 포함된 경우 파일을 제대로 찾지 못하는 오류가 있어서, http 미션에서 했던거 가져왔습니다.

2024-10-06 07:57 UTC, HoeSeong123 requested changes
안녕하세요 로빈!! 역시 구현을 굉장히 잘하셨네요.
2단계가 리팩토링이기도 해서 리팩토링 관련 피드백은 거의 남기지 않았어요.
첫 번째 단계가 어렵지 않았던 만큼 크게 피드백할 부분은 없는 것 같아서 간단한 질문 몇가지 남겼습니다.

평소 로빈이 정말 잘 하는 사람이라고 생각했었고, 그런 사람의 코드를 리뷰하다보니 코드 한줄한줄에 대한 이유가 너무 궁금해지더라고요ㅋㅋㅋ
질문 백개 남겼으니까 답변 잘 부탁드려요!!
아마 이번 리뷰 이휴에 바로 머지할 것 같고, 2단계부터는 리팩토링 관련한 피드백도 많이 남겨보겠습니다ㅎㅎ

그럼 앞으로 잘 부탁드려요!!

2024-10-06 07:57 UTC, HoeSeong123 commented on app/src/main/java/com/techcourse/dao/UserDao.java
> +    private CastingResultSetParser<User> UserResultSetParser() {
일부러 대문자로 작성하신건가요??

2024-10-06 07:57 UTC, HoeSeong123 commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +            throw new RuntimeException(e);
구현되어 있는 `DataAccessException`을 사용해도 좋을 것 같아요.
`RuntimeException`을 사용하신 이유가 있나요?

2024-10-06 07:57 UTC, HoeSeong123 commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +            return parseResults(resultSetParser, resultSet).getFirst();
원하는 값이 여러개라면 그 중 가장 첫 번째 값을 가져오는 식으로 진행하셨군요!!
예외를 던지지 않고 첫 번째 값으로 가져오게 한 이유가 있을까요??

2024-10-06 07:57 UTC, HoeSeong123 commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +    private ResultSet query(String sql, Object ... parameters) {
로빈은 오버로딩을 사용할 때 기준이 있나요?

2024-10-06 07:57 UTC, HoeSeong123 commented on jdbc/src/main/java/com/interface21/jdbc/core/CastingResultSetParser.java
> +public abstract non-sealed class CastingResultSetParser<T> implements ResultSetParser<T> {
이런 방식으로 구현하신 이유가 궁금해요!!
ResultSetParser의 확장성을 고려하신 건가요??

2024-10-06 07:57 UTC, HoeSeong123 commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
>      public JdbcTemplate(final DataSource dataSource) {
`JdbcTemplate`에 대한 테스트 코드가 없네요! 불필요하다고 생각해서 작성 안하신 건지 궁금해요.
만약 그렇다면 그렇게 생각하신 이유도 알려주세요~~

2024-10-06 08:51 UTC, robinjoon commented on app/src/main/java/com/techcourse/support/jdbc/init/DatabasePopulatorUtils.java
> +            final var sql = Files.readString(path);
제 맥북에서 프로젝트 경로에 한글이 있어서 안되더라구요. 에러 메세지에 한글로 되어있는 폴더 이름이 깨져나오길래 관련 키워드로 검색했던 거 같아요.

2024-10-06 09:09 UTC, robinjoon commented on jdbc/src/main/java/com/interface21/jdbc/core/CastingResultSetParser.java
> +public abstract non-sealed class CastingResultSetParser<T> implements ResultSetParser<T> {
한줄 요약 : 인터페이스로 메서드 시그니처를 정의해 설계시 편의성을 챙기고, 추상 클래스로 상세한 규약을 구현했어요.

`ResultSetParser` 설계 시 `JdbcTemplate` 내부 구현에서 ResultSet에 데이터가 남아있는 경우 `ResultSetParser` 인스턴스를 이용해 ResultSet에서 현재 커서 위치의 데이터를 파싱하는 구조로 설계했어요. 역할을 어느 클래스에 부여했는지 목록으로 나타내면 다음과 같아요.
1. `ResultSet`에 데이터가 남아있는지 확인 ➡️ `JdbcTemplate`
2. `ResultSet`의 데이터 한개를 가져와 원하는 형태로 가공 ➡️ `ResultSetParser`

라이브러리 입장에서 사용자가 어떤 타입으로 반환을 원하는지 알 수 없기 때문에 제네릭을 이용해 구현체에서 원하는 타입으로 반환할 수 있게 해야 했어요. 그런데 그러기 위해서는 안전하게 형변환을 해주기 위해 변환하고자 하는 타입을 추가해야 해서 필드와 생성자를 추가할 수 있는 추상클래스를 추가했어요.

안전한 타입 변환은 이 인터페이스의 구현체가 공통적으로 만족해야 하는 규약이에요. 따라서 이를 강제로 만족시킬 수 있도록 인터페이스의 직접 구현을 제한했어요.

인터페이스를 없애고 추상 클래스만 남겨도 되긴 할텐데요, 이런 라이브러리를 만들 때는 추상화의 수준이 어플리케이션보다 더 높기 때문에 추상화에 의존해 코드를 설계하는 것이 난이도가 더 낮은 것 같아요. 따라서 인터페이스로 메서드 시그니처를 먼저 정의해두고 이후에 인터페이스 구현체가 지켜야할 세부 구현을 추상클래스에 위임하는 방식을 사용했어요.

2024-10-06 09:16 UTC, robinjoon commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +    private ResultSet query(String sql, Object ... parameters) {
`public <T> List<T> query(String sql, ResultSetParser<T> resultSetParser, Object ... parameters)`
`private ResultSet query(String sql, Object ... parameters)`

이 두 메서드는 모두 "질의한다" 라는 이름을 가지고 있어요. 하지만, 접근 지정자가 후자의 경우 private이죠. 저는 접근 지정자가 private인 메서드와 public인 메서드를 분리해서 생각하고 있어요. public인 메서드들은 이름은 서로 다르게 하는 것을 선호하고, public과 private 에서는 이름의 중복보단 그 이름이 메서드의 동작을 제대로 대표하는지를 기준으로 정해요. 이 경우에는 질의한다는 의미가 너무 찰떡이라 자연스럽게 오버로딩을 사용한 거에요.

2024-10-06 09:18 UTC, robinjoon commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +            throw new RuntimeException(e);
코드 작성할때 저 예외의 존재를 파악하지 못했네요. 저 시점에 예외 처리를 어떻게 할지 고민하다가 다음 리팩토링때 개선해야지~ 하고 넘어갔어요. 반영해둘게요!

2024-10-06 09:22 UTC, robinjoon commented on app/src/main/java/com/techcourse/dao/UserDao.java
>      }
반영했습니다! https://github.com/woowacourse/java-jdbc/pull/610/commits/e4e5025f6d82a74ac239ea048dcb2084f6c66a4e

2024-10-06 09:23 UTC, robinjoon commented on app/src/main/java/com/techcourse/dao/UserDao.java
> +    private CastingResultSetParser<User> UserResultSetParser() {
오타가 있었네요😅 수정했습니다! https://github.com/woowacourse/java-jdbc/pull/610/commits/e40a944bdd01eda80f701174e45c685fbadd1421

2024-10-06 09:32 UTC, robinjoon commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +            throw new RuntimeException(e);
반영했습니다! https://github.com/woowacourse/java-jdbc/pull/610/commits/c20e22eef25ca43c4851e0782d9ac0590dd470b4

2024-10-06 09:33 UTC, robinjoon commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +            return parseResults(resultSetParser, resultSet).getFirst();
다시 생각해보니까 사용자가 단 한개의 결과만 반환하기를 바라는데 여러 데이터가 검색되면 정상적인 상황이 아니겠군요. 예외를 던지도록 수정하겠습니다!

2024-10-06 09:57 UTC, robinjoon commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +            return parseResults(resultSetParser, resultSet).getFirst();
반영했습니다! https://github.com/woowacourse/java-jdbc/pull/610/commits/4e7d44bddcc8b80ed1f45d7339abeadd4e2c62fd

2024-10-06 09:58 UTC, robinjoon commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
>      public JdbcTemplate(final DataSource dataSource) {
라이브러리를 개발한다는 관점에서 JdbcTemplate의 테스트는 필요할 것 같군요!

2024-10-06 10:40 UTC, robinjoon commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
>      public JdbcTemplate(final DataSource dataSource) {
테스트 추가했습니다! https://github.com/woowacourse/java-jdbc/pull/610/commits/d998082b4c0edda76fc4be4ecbc7e6704edfd1f7

테스트를 위해 H2 의존성을 추가하는 것 보단, 모킹을 진행하는 것이 타당하다 생각해 모킹을 진행했습니다!

2024-10-06 10:47 UTC, HoeSeong123 commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +    private ResultSet query(String sql, Object ... parameters) {
그렇군요!! 로빈의 말대로 private이라 사용할 때 헷갈릴 일도 없고, query라는 네이밍이 정말 잘 어울리는 메소드네요ㅎㅎ

2024-10-06 11:08 UTC, HoeSeong123 approved these changes
로빈 정말 빠르게 피드백 반영해주셨네요!!
변경사항 모두 확인했습니다.
이번 단계는 여기서 마무리해도 될 것 같아서 머지하도록 하겠습니다!
2단계에서 적용할만한 피드백 1개, 참고사항 1개 남겨놨으니 확인 부탁드려요~~

고생하셨습니다!!

2024-10-06 11:08 UTC, HoeSeong123 commented on jdbc/src/main/java/com/interface21/jdbc/core/CastingResultSetParser.java
> +public abstract non-sealed class CastingResultSetParser<T> implements ResultSetParser<T> {
>안전한 타입 변환은 이 인터페이스의 구현체가 공통적으로 만족해야 하는 규약이에요. 따라서 이를 강제로 만족시킬 수 있도록 인터페이스의 직접 구현을 제한했어요.

정말 생각해보지 못한 부분이네요!!!! 이 설명으로 이렇게 구현하신 이유가 완전히 이해됐습니다.
로빈은 인터페이스와 추상 클래스를 정말 잘 활용하시네요👍
정말 많은 고민을 해왔다는게 느껴지는 설계입니다.

2024-10-06 11:08 UTC, merged