[1단계 - JDBC 라이브러리 구현하기] 로키(정해성) 미션 제출합니다.
woowacourse/java-jdbc pull request #618
Opened 2024-10-02 17:24 UTC by HaiSeong

안녕하세요 짱수!
1단계 제출합니다.
감사합니다.

2024-10-02 17:29 UTC, HaiSeong commented on app/src/test/java/com/techcourse/dao/UserDaoTest.java
> +        final var actual = userDao.findByAccount(account);
이 부분에서 UserDaoTest를 수정하게 되었습니다.

이유는 `queryForObject`의 결과가 2건 이상이면 예외가 발생하도록 처리했는데 테스트 수행 순서에 따라서
`User("gugu", "password", "hkkang@woowahan.com")` 이 계정이 여러개가 insert 되어 예외가 발생하였기 때문입니다.

비즈니스 로직상 account는 유니크한 값이 되어야 한다 판단하여 단건 조회를 하는게 맞다 생각이 들어 여러건 조회로 수정하지 않았고 이 테스트 메서드에서만 따로 새로운 유저를 넣어 문제없이 작동하도록 했습니다

2024-10-04 13:09 UTC, zangsu requested changes
로키~~ 미션 잘 구현해 주셨네요!!
대체로 코멘트를 남길 부분이 없을 정도로 꼼꼼하게 구현을 해 주셔서,,,
열심히 리뷰를 해 보았지만 코멘트 개수가 많지 않네요 ㅎㅎ

가벼운 리뷰 남겨두었으니 확인 부탁드려요~

2024-10-04 13:09 UTC, zangsu commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +            ps.setObject(i + 1, args[i]);
세상에 그냥 `setObject()` 로 퉁쳐버릴 수 있었군요 😮

2024-10-04 13:09 UTC, zangsu commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +        try (ResultSet resultSet = ps.executeQuery()) {
> Note: A ResultSet object is automatically closed by the Statement object that generated it when that Statement object is closed, re-executed, or is used to retrieve the next result from a sequence of multiple results.

`ResultSet` 객체는 `Statement` 가 `close()` 될 때 함께 닫힌다고 하네요~

2024-10-04 13:09 UTC, zangsu commented on jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
>  class JdbcTemplateTest {
단건 조회 쿼리에서 결과가 없거나, 결과가 2개 이상일 경우의 예외 발생 테스트는 너무 좋네요. 
+) 로키는 `JdbcTemplateTest` 에서 어떤 것들을 테스트 해 보고 싶으신가요?

저는 `JdbcTemplateTest` 가 제공해 주는 파라미터 바인딩, 결과를 객체로 변환 해 주는 과정 등을 테스트 하고 싶을 것 같아요.
물론, 이 것을 테스트 하는 것이 꽤나 어려워서 아직 작성하지 못했지만요...ㅎㅎ

2024-10-04 15:53 UTC, HaiSeong commented on jdbc/src/main/java/com/interface21/jdbc/EmptyResultDataAccessException.java
> +public class EmptyResultDataAccessException extends RuntimeException {
`jdbcTemplate`을 실제로 테스트 해보니 [NonUniqueResultException](https://docs.jboss.org/hibernate/orm/6.0/javadocs/org/hibernate/NonUniqueResultException.html), [EmptyResultDataAccessException](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/dao/EmptyResultDataAccessException.html) 이렇게 두 이름의 예외를 사용하더라고요.
사실 말씀하신대로 네이밍을 통일하는것도 좋지만 `jdbcTemplate`을 구현하면서 학습하는 입장에서 `jdbcTemplate`의 `queryForObject`를 수행했을때 결과의 수에 따라 발생하는 예외의 이름에 익숙해 진다면 저에게 나중에 도움이 될것 같아요.

설득이 안되었다면 변경해보겠습니다.

2024-10-04 15:54 UTC, HaiSeong commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +    }
좋은 의견입니다. 메서드명 고민해볼게요!

2024-10-04 15:55 UTC, HaiSeong commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +            ps.setObject(i + 1, args[i]);
👍

2024-10-04 15:55 UTC, HaiSeong commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +        try (ResultSet resultSet = ps.executeQuery()) {
오 좋네요.
depth 때문에 만들었던 private 함수들 지워줘도 되겠네요.

2024-10-04 16:04 UTC, HaiSeong commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +    }
`next()`를 다시 호출해서 추가적인 결과를 확인하므로`checkForRemainingResult`라는 이름으로 변경하겠습니다.
피드백 부탁드려요!

2024-10-04 16:13 UTC, HaiSeong commented on jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
>  class JdbcTemplateTest {
음 다시 돌아보니 `JdbcTemplateTest` 에 필요한건 내부에서 호출되는 메서드의 호출 횟수 보다는 말씀하신것처럼 `파라미터 바인딩`, `결과를 객체로 변환 해준 결과` 같은게 더욱 필요한 테스트인것 같아요. 고민하여 반영해보겠습니다!

2024-10-04 18:32 UTC, zangsu commented on app/src/main/java/com/techcourse/dao/UserDao.java
> +    );
오호, 납득되었습니다!
로키 덕분에 하나 더 알아가네요~ 👍

2024-10-04 18:32 UTC, zangsu commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +    }
메서드 명이 훨씬 직관적이게 바뀌었군요! 👍

2024-10-04 18:35 UTC, zangsu commented on jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
> +    private static class TestObject {
내부 클래스 static 선언 👍

2024-10-04 18:35 UTC, zangsu commented on jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
>  class JdbcTemplateTest {
로키는 Mockito 를 사용하는 테스트가 꽤나 능숙해 보이네요!
확인하였습니다~

2024-10-04 18:36 UTC, zangsu commented on jdbc/src/main/java/com/interface21/jdbc/EmptyResultDataAccessException.java
> +public class EmptyResultDataAccessException extends RuntimeException {
아하, 실제로 사용되는 이름을 가져왔군요!
저는 실제 JdbcTemplate 을 우선 고려하지 않고 구현을 해 보려고 하다 보니 미처 몰랐네요
로키가 추구하는 방향이 확실하게 보여서 충분히 설득 되었습니다~~! 👍

2024-10-04 18:37 UTC, zangsu approved these changes
로키 1단계 수고하셨습니다!
이만 머지 할 테니 다음 단계로 넘어가시죠~

2024-10-04 18:37 UTC, merged