[1단계 - JDBC 라이브러리 구현하기] 카피(김상혁) 미션 제출합니다.
woowacourse/java-jdbc pull request #621
Opened 2024-10-03 06:27 UTC by tkdgur0906

안녕하세요 메이슨~ 리뷰어로 만나게 되서 반갑네요!

1단계 제출합니다!
리뷰 잘부탁드립니다~

2024-10-05 04:01 UTC, masonkimseoul requested changes
안녕하세요 카피!
건강상의 이유로 리뷰가 늦어서 미안합니다.
미션 잘 진행해주셨네요.
JdbcTemplateTest가 비어있는데, 이 부분도 추가해주시면 좋을 것 같습니다!

2024-10-05 14:09 UTC, tkdgur0906 commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +    private void closeResultSet(ResultSet rs) {
해당 내용이 공식 문서에 적혀져 있네요!
예전에 학습했던 부분인데 잊어버렸네요😅
명시적으로 close 하지 않도록 수정해습니다!

2024-10-05 14:19 UTC, tkdgur0906 commented on app/src/main/java/com/techcourse/dao/UserDao.java
> +            );
반영했습니다!

2024-10-05 14:37 UTC, tkdgur0906 commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +            return null;
기존에는 큰 이유없이 null을 반환했습니다!
스프링의 jdbcTemplate은 null일 경우 내부적으로 예외를 던지고 있는데,
사용자가 예외를 무조건 처리하게 하는 방식보다 Optional로 안전하게 처리하는 것이 좋을 것 같아 Optional을 도입했습니다!

2024-10-05 14:51 UTC, tkdgur0906 commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +             PreparedStatement pstmt = getPreparedStatement(sql, conn)) {
두 메서드를 합치라는 의도이실까요?
어떤 방식으로 분리할지 조금 더 설명해주실 수 있나요?

2024-10-05 15:03 UTC, tkdgur0906 commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +        } catch (SQLException e) {
`SQLException`은 `checkedException`이기 때문에 반드시 처리를 해줘야합니다.
그래서 현재는 `uncheckedException`인 `RuntimeException`으로 치환해서 throw하고 있습니다.
`SQLException`은 sql 구문 오류, 커넥션 오류 등 복구가 불가능한 예외이기 때문에 예외 전파를 막기 위해 `RuntimeException`으로 바꿔주는 것이 좋습니다.

`DataAccessException`은 `RuntimeException`을 상속받은 예외로 데이터 엑세스 관련 에러를 처리하는 상위 예외 클래스입니다. 다양한 데이터 접근 기술의 예외를 일관된 방식으로 처리하고, 각기 다른 오류를 표현하기 위해 여러가지 서브 클래스를 제공합니다.

2024-10-06 02:56 UTC, masonkimseoul approved these changes
안녕하세요 카피!
피드백 사항 모두 잘 반영해주셨네요~ 테스트 코드까지 👍
이번 단계는 여기서 마쳐도 좋을 것 같습니다.
다음 단계에서 만나요~

2024-10-06 02:56 UTC, masonkimseoul commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +             PreparedStatement pstmt = getPreparedStatement(sql, conn)) {
Connection이 자동으로 닫히는 부분은 생각하지 못했네요 🥲 저는 위 두 라인이 반복될 수 있으니까 다른 메서드로 분리하는게 어떨까? 라고 단순히 생각했었는데, 분리가 어려울 것 같습니다. 본의 아니게 혼란을 드렸네요... 이 부분은 지금 코드를 유지하면 좋을 것 같습니다!

2024-10-06 02:56 UTC, merged