[1단계 - JDBC 라이브러리 구현하기] 조조(조은별) 미션 제출합니다.
woowacourse/java-jdbc pull request #623
Opened 2024-10-03 08:40 UTC by eun-byeol

냥인 안녕하세요😺
이렇게 만나니 반갑네요!

1단계 구현해보았습니다. 기능 목록은 jdbc 패키지 `README`에 정리했어요.
지난 미션 코드는 마이그래이션 하지 않고, 기존 코드 활용했어요.

## 주요 변경 사항
### 1. UserDao 인터페이스화
- `UserDaoImpl` : JdbcTemplate 사용X
- `UserDaoJdbcImpl` : JdbcTemplate 사용O

### 2. app 패키지 Controller에서 UserService 주입
- 메모리 대신 DB를 사용하도록, 기존 `InMemoryUserRepository` 제거하고 DB를 사용하는 `UserService`로 교체

2024-10-03 14:52 UTC, cutehumanS2 requested changes
조조 ~ ⭐️ 안녕하세요. 냥인입니다. ㅎ ㅎ
저도 너무 반가워요. 🤍

미션 구현하시느라 정말 수고 많으셨어요. 👍 
그런데 UserDaoTest가 실패합니다. 확인 부탁드려요 조조  ~ ~

나머지는 요구사항에 맞게 잘 구현해 주시기도 했고, 
테스트도 잘 작성해 꼼꼼히 잘 작성해 주셔서 !
리팩토링은 2단계 때 하셔도 충분할 것 같아 사소한 코멘트들만 남겼습니다. 

조조가 보시기에 필요한 부분만 반영/답변하신 뒤 리뷰 요청 주세요!
아마도 다음번에 바로 머지할 것 같습니다.

파이팅입니다. 😘

2024-10-03 14:52 UTC, cutehumanS2 commented on jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
> +    void executeUpdate() {
ㅎㅎㅎ 여기 테스트 메서드명 짓기가 힘드셨나보군요. 
여기만 메서드명 그대로네요. 공감합니다.😅

2024-10-03 14:52 UTC, cutehumanS2 commented on jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
> +    void executeUpdate() {
그리고 여기는 왜 실패 테스트가 없나요?!

2024-10-03 14:52 UTC, cutehumanS2 commented on jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
> +        );
저는 커넥션과 PreparedStatement가 닫혔는지도 검증해 줬어요. 😸
조조도 검증해 보는 것 어떠신가요?
```java
// ex
verify(conn, times(1)).close();
```

2024-10-03 14:52 UTC, cutehumanS2 commented on jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
> +        System.out.println(actual);
오잉.

2024-10-03 14:52 UTC, cutehumanS2 commented on jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
> +        when(rs.getString(2)).thenReturn("jojo", "cutehuman");
🤍ㅋㅋㅋ

2024-10-03 14:52 UTC, cutehumanS2 commented on jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
> +        private final Long id;
좀 사소하지만 ㅎㅎ
id를 final로 하신 이유가 궁금합니다.

2024-10-03 14:52 UTC, cutehumanS2 commented on app/src/test/java/com/techcourse/dao/UserDaoTest.java
조조 ~ UserDaoTest가 실패해요. 😿
혹시 제가 추가로 설정해야 하는 부분이 있나요?
```
java.lang.RuntimeException: org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "USERS" not found (this database is empty); SQL statement:
```

2024-10-03 15:10 UTC, eun-byeol commented on app/src/test/java/com/techcourse/dao/UserDaoTest.java
다시 클론받아서 실행도 해보았는데, 저는 성공 합니다🥲
![image](https://github.com/user-attachments/assets/178d80d7-9c60-4183-bc1e-9253ae066352)

오류 상으로는`schema.sql`이 제대로 실행되지 않은 것 같은데
`DatabasePopulatorUtils.execute()`쪽 로직 확인해주실 수 있을까요?

2024-10-03 15:30 UTC, eun-byeol commented on app/src/main/java/com/techcourse/dao/UserDaoJdbcImpl.java
> +            );
(반영 완료) 칼럼명으로 가져오는 방법이 명시적이라서 더 좋네요!
인덱스 방식은 `getString()` 처럼 동일한 타입이 많은 경우 헷갈릴 수 있겠어요

2024-10-03 15:34 UTC, cutehumanS2 commented on app/src/test/java/com/techcourse/dao/UserDaoTest.java
조조 사과부터 하겠습니다. 죄송합니다. 😿 
제 환경 문제였어요. 코드 리뷰용 디렉토리명을 한글로 했더니 new File할 때 파일을 제대로 못 찾아오네요.
영문으로 바꾸니까 해결되었어요.

걱정 끼쳐드려 죄송해요 조조........😹

2024-10-03 15:40 UTC, eun-byeol commented on app/src/main/java/com/techcourse/dao/UserDaoJdbcImpl.java
> +    }
지금 요구사항 상으로는 필요하지 않다고 생각했는데, 냥인은 어떻게 생각하시나요?
추가한다면, UserDaoJdbcImpl 생성 시에 편해지는 장점이 있을 것 같아요

**before:**
`userDao = new UserDaoJdbcImpl(new JdbcTemplate(DataSourceConfig.getInstance()));`
**after:**
`userDao = new UserDaoJdbcImpl(DataSourceConfig.getInstance());`

2024-10-03 16:09 UTC, eun-byeol commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +            ResultSet rs = pstmt.executeQuery();
(반영 완료) try-with-resources 구문 사용하면서 놓친 것 같네요😄 추가했습니다!

2024-10-03 16:47 UTC, eun-byeol commented on jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
> +        System.out.println(actual);
(반영 완료) 하하핫ㅎㅎ

2024-10-03 17:01 UTC, eun-byeol commented on jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
> +        private final Long id;
불변하게 만들 수 있는데, 하지 않을 이유가 없었어요.
지금은 Dao에서 `insert()`의 반환값이 void 이지만, `User`로 바뀌었을 때도
setter로 id를 넣어주는 것이 아니라, new로 새로운 객체를 만들어 줄 수 있으니까요!
다만, final이 추후 문제가 될 땐 뺄 수도 있을 것 같아요~

2024-10-03 17:05 UTC, eun-byeol commented
냥인😺 빠르게 리뷰해주셨네요! 감사합니다!!
리뷰 반영 후에 다시 요청드려요

실패하는 테스트에 대해서는, 우선 제 컴퓨터에서는 문제가 없어 확인이 어렵네요🥲
내일 다른 크루 컴퓨터로 다시 체크해보겠습니다!
언제든 편하게 DM(💌) 주세요~

2024-10-03 23:51 UTC, cutehumanS2 commented on jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
> +    void executeUpdate() {
> executeUpdate의 경우 실패하는 경우가 없었어요. 실패 테스트를 에러 발생으로 보지 않고, 조회 결과 없음 용도로 사용했어요. 

오 그렇군요. ㅎ ㅎ 저는 에러 발생을 실패 테스트라고 생각했었습니다. 구분하는 것도 명확해서 좋아요. 👍

2024-10-04 00:33 UTC, cutehumanS2 commented on app/src/main/java/com/techcourse/dao/UserDaoJdbcImpl.java
> +    }
보통 dao나 repository에서 DataSource를 주입받아 JdbcTemplate를 생성하는 방법을 많이 사용한다고 해요.
저도 조조처럼 바로 JdbcTemplate을 주입받으면 되지 않을까- 하는 생각에(물론 됨) 그냥 궁금해서 질문 남겨 보았습니다. ㅎ‿ㅎ

2024-10-04 00:35 UTC, cutehumanS2 approved these changes
조조~ 반영 사항 확인 완료하였습니다. 
이제 2단계에서 열심히 리팩토링 해봅시다.😸
1단계는 이만 머지할게요~!

조조 보고싶어요. 🤍

2024-10-04 00:35 UTC, merged