[1단계 - JDBC 라이브러리 구현하기] - 몰리(김지민) 미션 제출합니다.
woowacourse/java-jdbc pull request #632
Opened 2024-10-03 14:34 UTC by jminkkk

안녕하세요 호기 ~~
오랜만입니다 잘 지내시죠 🙌

벌써 우테코 마지막 미션이네요 🥲

> 중복을 제거하기 위한 라이브러리는 JdbcTemplate 클래스에 구현한다.

중복을 제거하기 위한 JdbcTemplate이지만,,, JdbcTemplate의 중복 코드도 불편하더라구요,,,,ㅋㅋㅋㅋ
함수형 인터페이스로 중복을 최대한 제거하려고 했어요.
사용이 어색한 부분이나 질문 있다면 편하게 말씀 부탁드립니다. 

재미있게 마지막 미션 같이 해봐요 🔥

2024-10-05 16:00 UTC, hoyeonyy requested changes
안녕하세요 몰리~!
캠퍼스 나눠진 이후로 오랜만에 얘기해보는 것 같네요!

대부분 완성된 코드여서 크게 남길 코맨트는 없는 것 같아요! 몇 가지 질문 사항 남깁니다!

2024-10-06 06:09 UTC, jminkkk commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
>  }
이 부분의 `SQLException`는 데이터베이스 엑세스 또는 커넥션을 얻는 중에 발생하는 에러라 다른 에러로 전환이 적절한 것 같네요. 변경하겠습니다~!

2024-10-06 06:09 UTC, jminkkk commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
>  public class JdbcTemplate {
JdbcTemplate를 확인하지 않고 구현했는데, 아무래도 이미 사용해 봤던 터라 닮아져버렸던 것 같네요 🥲

> 몰리의 코드를 보다보니 제가 알고 있는 JdbcTemplate 와 거의 유사하게 되었더라구요! 혹시 몰리는 JdbcTemplate 을 만들면서, 혹은 사용하면서 느꼈던 불편한 점이 있나요??

만들면서는 자원 관리에 대한 부분이 번거로웠던 것 같아요. 
사용하면서는 컴파일 타임에 문법 오류 등을 확인할 수 없었던 점이 가장 치명적인 불편한 점이었던 것 같아요.
생각해보니 제가 불편했던 점을 다음 단계에 개선을 해보고 싶네요. 좋은 인사이트 감사합니다 👍👍

---

JdbcClient는 처음 들어봤는데 체이닝으로 파라미터나 반환값을 지정할 수 있군요!
흥미로운 키워드 감사합니다 👍

2024-10-06 06:14 UTC, jminkkk commented on jdbc/src/main/java/com/interface21/jdbc/core/ResultMapper.java
> +public class ResultMapper {
저도 동일하게 배치하곤 하고 여러 public에서 사용되는 private이라면 가장 마지막 public 메서드 아래에 위치시킵니다.
`existsNext` 의 위치가 변경이 필요해보이네요. 변경하겠습니다 😁

2024-10-06 07:36 UTC, hoyeonyy approved these changes
안녕하세요 몰리~

리뷰 반영과 테스트 잘 동작하는 것 확인했습니다!
이번 미션은 여기서 approve 할께요!

2024-10-06 07:36 UTC, merged