[1단계 - JDBC 라이브러리 구현하기] - 리비(이근희) 미션 제출합니다.
woowacourse/java-jdbc pull request #637
Opened 2024-10-03 19:11 UTC by Libienz

안녕하세요 마크~
리뷰이 리비입니다. jdbc 미션으로 만나게 되어 반갑습니다 ㅎㅎ

미션 진행해보았습니다! 리뷰 잘 부탁드립니다 🙇🏻‍♂️

2024-10-05 06:27 UTC, seunghye218 requested changes
안녕하세요 리비~ 리뷰어로 만나게 되었네요 반가워요~!

작업을 작은 커밋 단위로 잘 나눠서 리뷰하기 좋았어요. 테스트도 꼼꼼하게 작성해 주셔서 각 메서드의 동작을 파악하기 쉬웠습니다.
코멘트 몇개 남겼으니 확인 부탁드려요~~!

2024-10-05 06:27 UTC, seunghye218 commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
>      private static final Logger log = LoggerFactory.getLogger(JdbcTemplate.class);
try 문 안에서 로그를 찍던데 resourses에 할당이 실패하면 로그가 찍히지 않을 것 같네요!

2024-10-05 18:39 UTC, Libienz commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +            }
흔히 메서드 분리를 리팩터링 대상으로 이야기하지만 너무 과하게 분리하면 한 호흡에 메서드를 읽기 힘들다고 생각해요~

재사용되는 맥락이 깊지 않고 메서드를 읽기 어렵게 만드는 것 같아 다시 원복한 커밋입니다!

2024-10-05 18:39 UTC, Libienz commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +        }
합리적이라고 생각해서 반영했습니다~

2024-10-05 18:39 UTC, Libienz commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
>      private static final Logger log = LoggerFactory.getLogger(JdbcTemplate.class);
resource할당이 실패하면 쿼리 때문에 실패한 것이 아니기에 쿼리 로그는 불필요한 정보가 된다고 생각해요!
log 위치는 제 소신대로 유지해보겠습니다. 마크가 반영을 원하신다면 추가적인 코멘트 부탁드려요~

ps. 다만 쿼리 로그는 try문 내부에서 최상단에 위치하도록 수정되었습니다!

2024-10-06 03:54 UTC, seunghye218 approved these changes
요청한 리뷰에 대해 적용한 부분과 테스트 까지 잘 수정한 부분 확인했어요~ 요구 사항을 잘 만족하여 구현하셨네요. 이만 머지하겠습니다~ 2단계도 화이팅!

2024-10-06 03:54 UTC, seunghye218 commented on jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
> +        final int rowsAffected = jdbcTemplate.update(sql, keyHolder, "mark", "mark@example.com");
😄

2024-10-06 03:54 UTC, seunghye218 commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +            throw new EmptyResultDataAccessException(1);
👍

2024-10-06 03:54 UTC, seunghye218 commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
>      private static final Logger log = LoggerFactory.getLogger(JdbcTemplate.class);
로그를 통해 어떤 정보를 얻고 싶은지에 따라 위치를 달리해도 좋겠네요 😀

2024-10-06 03:55 UTC, merged