Step1
woowacourse/java-jdbc pull request #649
Opened 2024-10-05 07:19 UTC by PgmJun

안녕하세요 리건~~ 반갑습니다 이든이에요

실제 JdbcTemplate을 참고하면서 이번 미션 구현을 해보았는데 리뷰 잘 부탁드리겠습니다!

[얘기해보고 싶은 부분]
테스트 코드를 어떤 걸 짜봐야할 지 잘 모르겠습니다.
구현해준 JdbcTemplate에 대해서 테스트 코드를 짜고싶어서 아래와 같은 고민을 해봤어요

1. JdbcDataSource를 사용해서 테스트한다
그런데 이 방식은 Jdbc 라이브러리에 의존하는 테스트가 작성되기 때문에 좋은 구현이 아니라고 생각했습니다.

2. 테스트 더블을 사용해서 테스트한다.
JdbcTemplate의 실제 동작을 테스트해야하는데 테스트 더블을 통해 구현하면
DataSource, Connection,PreparedStatement 등 처리해야할 부분이 너무 많았고
전부 테스트 더블으로 가짜구현을 할 거면 테스트의 의미가 없을 것 같다고 생각이 들었습니다.

이 부분에 대해서 리건은 어떻게 구현하셨는지 궁금합니다! 도와주세요!!

2024-10-06 08:17 UTC, hangillee requested changes
안녕하세요 이든! 🙌
제가 달아뒀던 리뷰가 사라져서 깜짝 놀랐습니다..😂

몇가지 질문 코멘트를 남겼습니다. 확인 부탁드립니다!

p.s. 테스트에 대한 부분인데요..
저는 결국 Mocking을 활용해서 JdbcTemplate에서 발생할 수 있는 예외 상황이 적절하게 처리되고 있는지 검증했습니다. Mocking을 통해 JdbcTemplate외의 모든 외부 상황은 전부 정상 동작 중임을 가정한다고 생각했을 때, 큰 어색함은 없는 것 같아요.

2024-10-06 08:17 UTC, hangillee commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +            }
Indent depth를 줄일 수 있다면 줄이는 게 좋을 것 같습니다!

2024-10-06 08:17 UTC, hangillee commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +            }
Q.
`finally` 구문에서 ResultSet을 close해주지 않은 특별한 이유가 있나요?
try-with-resources를 사용하는데 finally를 사용하는게 어색하다고 느끼셨나요?

2024-10-07 03:54 UTC, PgmJun commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +            }
어떤 객체는 try-with-resources로 처리하고, 어떤 객체는 finally로 처리하는게 어색해서 이렇게 처리해주었습니다.

2024-10-07 04:56 UTC, PgmJun commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +            }
메서드 분리로 해결해보겠습니다:)

2024-10-07 09:07 UTC, PgmJun commented
## 리뷰 반영 내용
안녕하세요 리건! 리뷰 내용 반영하고 테스트 코드도 작성해보았습니다.
JdbcTemplate의 queryForObject() 메서드에서 조회된 데이터 개수에 따라 예외를 발생시켜야하는 부분이 있어서 그 부분 구현 및 테스트 작성해보았습니다!

검토 부탁드려요!!

2024-10-07 09:27 UTC, hangillee approved these changes
안녕하세요, 이든!
테스트 작성해주신 것 확인했습니다.

모든 테스트 전부 통과하는 것도 확인했습니다.
사용하지 않는 의존성만 다음 제출에서 제거해주세요!

고생하셨습니다!

2024-10-07 09:27 UTC, merged