[1단계 - JDBC 라이브러리 구현하기] - 아톰(이하늘) 미션 제출합니다.
woowacourse/java-jdbc pull request #654
Opened 2024-10-05 11:13 UTC by le2sky

2024-10-07 05:52 UTC, youngsu5582 requested changes
안녕하세요 아톰!
고수라고 소문은 들었는데 역시네요..! ( 콜백 패턴은 아마 제 코드에서도 도입할 거 같습니다 ☺️☺️ )
2단계 리팩토링 부분에서도 크게 달라질게 없을거 같네요.
리뷰는 가볍게 질문 및 아톰의 생각을 듣고 싶은 부분 남깁니다!
다음 리뷰 요청은 바로 Approve 일거 같습니다 🙂

2024-10-07 05:52 UTC, youngsu5582 commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +        ResultSet rs = pstmt.executeQuery();
`ResultSet` 에 대해서 close 를 잘 해주셨는데
try 구문안에 포함 가능할 거 같아요!

2024-10-07 05:52 UTC, youngsu5582 commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +            pstmt.setObject(index++, arg);
PreparedStatement 에는 `setObject` 이외
`setInteger` ,`setString`과 같은것들도 있습니다.

setObject 를 명확하게 사용한 이유가 있을까요? ( 다른 `setXXX` 들과 차이점은 뭔가요? )

2024-10-07 05:52 UTC, youngsu5582 commented on app/src/main/java/com/techcourse/dao/UserDao.java
> +        return jdbcTemplate.queryOne(sql, getUserResultSetCallBack(), id);
"jdbcTemplate 가 ResultSet 을 반환하고 후처리는 각각 DAO 에서 처리하는건 어떨까요?"

- 실행하는 jdbcTemplate 이 후처리인 `callback` 까지 알 필요 없다.
- 가변인자들 앞에 callback 메소드가 있는게 부자연스럽다
```java
return jdbcTemplate.queryOne(sql,id)
    .execute(this::getUserResultSetCallBack);
```

라고 물어보려고 했는데 ResultSet 역시 Resource 이므로 어렵네요,,,
( 삽질 해봤는데 어려움을 느꼈습니다... )

---

```java
public User findByAccount(String account) throws SQLException {
    String sql = "select id, account, password, email from users where account = ?";

    return jdbcTemplate.queryOne(sql, account)
            .execute(callback);
}

ResultSetCallBack<User> callback = (rs) -> new User(
        rs.getLong(1),
        rs.getString(2),
        rs.getString(3),
        rs.getString(4)
);
```

```java
public class QueryResult {
private final ResultSet rs;

public QueryResult(final ResultSet rs) {
    this.rs = rs;
}

// Method to execute a callback on the result
public <T> T execute(final ResultSetCallBack<T> callback) throws SQLException {
    final T result = callback.callback(rs);
    rs.close();
    return result;
}
}
```
와 같이 가능은 할 거 같은데 가볍게 아톰의 의견을 들을 수 있을까요??
( 기존의 패턴을 고수한 이유나 현재 제가 제시한 방법에 대해서면 될거 같아요 🙂 )

2024-10-07 05:52 UTC, youngsu5582 commented on app/src/main/java/com/techcourse/dao/UserDao.java
> +        return jdbcTemplate.queryOne(sql, getUserResultSetCallBack(), account);
```java
ResultSetCallBack<User> callback = (rs) -> new User(
        rs.getLong(1),
        rs.getString(2),
        rs.getString(3),
        rs.getString(4)
);
```
이와 같이 변수로 선언이 가능할꺼 같은데, 함수로 선언한 이유가 있을까요?

2024-10-07 05:52 UTC, youngsu5582 commented on jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
> +    @DisplayName("여러건 데이터 조회 결과가 존재하지 않는 경우 null을 반환한다.")
억까긴 한데 실제 DB에 `sql` 요청을 보내면, `SQLSyntaxErrorException` 을 발생시키지 않나요? 🥲🥲 ( 죄송합니당 😈 )

2024-10-07 05:52 UTC, youngsu5582 commented on jdbc/src/main/java/com/interface21/jdbc/core/PreparedStatementCallBack.java
> +public interface PreparedStatementCallBack {
아톰이 생각하시는 콜백(Callback) 패턴은 무엇이며 언제 사용이 유용할지 궁금합니다.
( 아마도, 위에 질문 `"jdbcTemplate 가 ResultSet 을 반환하고 후처리는 각각 DAO 에서 처리하는건 어떨까요?"` 역시도 이와 비슷한거 같습니다☺️ )

되게 깔끔하게 잘 구현하신거 같아서 물어봅니다!

2024-10-09 08:39 UTC, le2sky commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +            pstmt.setObject(index++, arg);
setXXX(index, value) 메서드는 지정한 인덱스의 ? 값을 value로 설정하는데요. value에 타입에 따라서 setString, setInteger로 나뉘는걸로 알고 있어요. setObject를 사용한 이유는 라이브러리 입장에서 args의 타입을 모르기 때문입니다. 제가 놓치고 있는 부분이 있다면, 추가 피드백 부탁 드립니다!

2024-10-09 08:39 UTC, le2sky commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +        ResultSet rs = pstmt.executeQuery();
현재 try 구문안으로 이동 시켜놨어요!

2024-10-09 08:43 UTC, le2sky commented on app/src/main/java/com/techcourse/dao/UserDao.java
> +        return jdbcTemplate.queryOne(sql, getUserResultSetCallBack(), account);
변수라면 인스턴스 변수를 말씀하시는 걸까요? 아니면, 지역 변수를 말씀하시는걸까요!?
지역 변수는 중복이 많아서 인스턴스 변수, 클래스 변수, 메서드 추출이 대안일텐데요. 변수보다 개인적으로 메서드를 사용하는 쪽이 가독성이 낫다고 생각했어요. 조이썬은 어떤 방식을 선호하시나요?

2024-10-09 09:12 UTC, le2sky commented on app/src/main/java/com/techcourse/dao/UserDao.java
> +        return jdbcTemplate.queryOne(sql, getUserResultSetCallBack(), id);
조이썬이 말씀하시는 바는 "jdbcTemplate에서 callback 을 몰라도 된다." 가 맞을까요? 

빌더 패턴이랑 비슷한 방식을 제안해주신 것 같아요. 제안 해주신 방법은 template이라는 이름의 의미가 퇴색되지 않는지 염려됩니다. 템플릿 메서드? 템플릿 콜백? 패턴 같은 느낌을 사용하는 친구들을 Template이라는 이름을 지어주는 것으로 알고 있어요. 다양한 방식 콜백 메서드를 사용하여 공통 작업을 수행하는 역할을 QueryResult에게 주게 된다면, QueryResultTemplate? 으로 불리는 것이 적절하지 않을까 생각이 드네요. 

그리고 제안주신 QueryResult  클래스는 좋은 것 같아요. 기존 JdbcTemplate에서는 rs 처리에서 비슷한 코드를 생성합니다. 
가령, `if(rs.next()`나 `while(rs.next)`을 다루는 부분이요.  이런 부분을 추상화해서 작업하려니 JdbcTemplate 사이즈가 커져서 부담이더라구요. QueryResult 내부로 rs 매핑 작업 위임하면 이런 작업이 편리하겠네요. 이 방식에서 생각나는 단점은 rs를 외부에서 주입받는데 방어적 복사를 못하니 외부에서 close할 수 있다? 정도 생각납니다. 

이 부분, 조이썬 의견 더욱 들어보고 싶어요. 그리고 제가 놓치고 있는 부분이 있다면 추가 피드백 부탁 드립니다!

2024-10-09 09:25 UTC, le2sky commented on jdbc/src/main/java/com/interface21/jdbc/core/PreparedStatementCallBack.java
> +public interface PreparedStatementCallBack {
인터넷에 있는 콜백 패턴의 정의보다는.. 부족하지만 순수한 제 생각을 전달 드립니다.
제가 생각하는 콜백은 다른 객체에게 값 대신 일련의 행동을 넘기는 방식입니다. `doJobWhenYouOk(() -> System.out.println('hi'))` 요런 느낌입니다. 

단점으로는 콜백 지옥 요런게 있고, 다른 객체 내부에서 사용하는 값을 외부에서 알게 되는 것도 문제로 볼 수 있어요. 
예를 들어,  `ResultSetCallBack<User> callback = (rs) -> { ... }`와 같은 코드에서는 외부에서 콜백을 만들려면 rs의 존재와 사용 방법을 알아야 합니다. (어쩔 수 없는 부분 같기도 하지만요..)

제어권이 다른 곳으로 넘어갈 때 유용하게 사용되는 것 같아요. 비동기나 스레드를 사용한다던가, 혹은 지금처럼 템플릿 콜백 패턴처럼 제어권이 템플릿 클래스 내부에 있는 경우에요. 조이썬은 어떻게 생각하시나요?

2024-10-10 00:22 UTC, youngsu5582 commented on app/src/main/java/com/techcourse/dao/UserDao.java
> +        return jdbcTemplate.queryOne(sql, getUserResultSetCallBack(), id);
> 조이썬이 말씀하시는 바는 "jdbcTemplate에서 callback 을 몰라도 된다." 가 맞을까요?

해당 관점에서 질문한게 맞습니다!
하지만, 해당 부분은 `Template` 의 관점에서 확실히 벗어난 거 같긴 하네요 🙂

<img width="751" alt="image" src="https://github.com/user-attachments/assets/9b6c34fa-9860-4164-81f0-62604aac5204">

이와 같이 빌더 패턴 + `Fluent Interface` 를 같이 적용하는걸 기대했는데
JdbcTemplate 은 온전히 템플릿에 맞게 수행하는게 맞는거 같습니다!

> 이 방식에서 생각나는 단점은 rs를 외부에서 주입받는데 방어적 복사를 못하니 외부에서 close할 수 있다?

저도 해당 부분이 사실 가장 큰 문제점 인거 같아요.
( 리소스 종료를 외부 책임으로 할당 + 호출 & 종료시점 명확하지 않음 - 콜백을 언제 넣어서 `execute` 할지 모르니 )

추가로, `ResultSet` 은 무조건 반환이 되어야 하는 자원 이므로
`쿼리를 통해 받은 모든 값들을 바로 쓰지 않는 경우는 없을까?` 생각하며 질문했습니다.
( Profile & Member JOIN -> 처음에는 Member 만 사용, 나중에는 Member + Profile DTO 사용 )

[rs를 이용하여 도메인과 매핑할 수 있는 데 중간 레벨의 추상화를 둔 이유](https://github.com/woowacourse/java-jdbc/pull/682#discussion_r1789588590)
이는 제 생각을 리뷰어(리비) 에게 남긴 링크로, 위의 질문이나 생각의 흐름이 더 궁금하다면 봐주세요! 🙂

2024-10-10 00:24 UTC, youngsu5582 commented on jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
> +    @DisplayName("여러건 데이터 조회 결과가 존재하지 않는 경우 null을 반환한다.")
해당 부분은 `getDataSource` 가 현재는 모킹이지만 나중에 실제 DB 로 변환 했을때는
일관성 있는 테스트가 되길 원해서 질문 했으나 ( 실제로, H2 로 변경해서 날려볼 시 `SQLSyntaxErrorException` 발생 )

`JdbcTemplate` 은 모든 데이터소스에서 일관성 있게 제공해야 하는 추상적 클래스 이므로
아톰이 구현한 거 처럼 모킹을 하고, 로직을 검증하는 게 더 바람직 한 거 같습니다. 🫡

2024-10-10 00:32 UTC, youngsu5582 commented on jdbc/src/main/java/com/interface21/jdbc/core/PreparedStatementCallBack.java
> +public interface PreparedStatementCallBack {
사실, 저는 자바스크립트 기반 프레임워크를 하다 와서 아직도 자바의 콜백 패턴이 너무 적응이 안되요 🥲🥲
( 왜 매개변수로 넘겨줘야 하지? ) 
( `then`-`catch` -> `async` - `await` 처럼 바로 명확하게 변경이 불가능 한가? )

이는 물론 아직 제 실력이 부족해서 일수도 있겠네요 🙂

핵심은 매개변수 를 통해, 무언가의 로직 (변환 or 또다른 실행 등등) 을 역할을 분리 또는 교체하기 용이하기 위해서인거 같아요.
근데, 결국 이게 매개변수 하나를 차지 하기도 하고, 객체를 넘겨주거나 객체를 가지고 있는것보다 유의미 한지는 아직 잘 못느끼는거 같습니당.

아톰의 의견 감사합니다☺️☺️

2024-10-10 00:35 UTC, youngsu5582 commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +            pstmt.setObject(index++, arg);
[setObject vs setXXX](https://github.com/woowacourse/java-jdbc/pull/682#discussion_r1789572262)

이는 제가 리뷰어 에게 남긴 답변입니다. 궁금하면 들어가서 봐도 될거 같습니다 🫡🫡

간단하게 위의 내용을 드러내면

타입을 명확하게 명시해서 사용하냐, 라이브러리가 타입을 추론해서 사용하게 만들지 가 차이점입니다.

- setObject : 검사 -> 형변환 -> setParameter
- setXXX :  setParameter

스택 오버플로우에 관련 글을 찾아보니
> 이 방법을 사용하면 하나의 DAO 메소드에서 다양한 데이터 타입을 처리할 수 있어 코드가 훨씬 유지보수가 용이해집니다.
단, setObject를 사용할 때 약간의 오버헤드가 발생할 수 있지만,
이는 유지보수가 더 쉬워지는 이점에 비하면 사소한 문제로 볼 수 있습니다.

와 같은 의견이 있었습니다. 참고만 해주세요! 🙂

2024-10-10 00:47 UTC, youngsu5582 commented on app/src/main/java/com/techcourse/dao/UserDao.java
> +        return jdbcTemplate.queryOne(sql, getUserResultSetCallBack(), account);
함수형 으로 지정 했기에
굳이 메소드가 아니라, 인스턴스 변수로 가져도 되지 않을까 질문을 했습니다.

추가로, 저는 변수를 가지는 쪽을 선호하는 거 같습니다.

메소드 는 
- 조금 더 복잡한 기능( 다른 메소드 를 같이 써야하고, 인스턴스 변수를 써야할 때 )
- 외부로 노출하는 API ( public )

함수형 으로 선언할 때는 왠만하면 변수로 지정하는거 같아요.

우선, 불필요한 `xxx()` 와 같이 괄호를 없앨수도 있고
현재 로직상 `getUserResultSetCallBack` 을 통해 호출 시, 새로운 함수형을 계속 생성해서 반환하는 식인거 같아요.
( 물론, 람다는 자체 캐싱을 해서 효율적으로 동작이 되긴 하더라구요 🙂 )

<img width="732" alt="image" src="https://github.com/user-attachments/assets/64f35d8b-0305-4e96-99d6-7691827a77b0">

```
com.techcourse.dao.UserDao$1@72ccd81a
com.techcourse.dao.UserDao$1@6d8792db
com.techcourse.dao.UserDao$1@64bc21ac
com.techcourse.dao.UserDao$1@493dfb8e
com.techcourse.dao.UserDao$1@5d25e6bb
```

( 익명 클래스로 변환 시 주소가 다르게 나옵니다. )

이런 관점에서 변수로 가지는게 좋다고 생각합니다.
아톰의 의견을 더 들려주셔도 좋습니다! ☺️

2024-10-10 00:49 UTC, youngsu5582 approved these changes
아톰! 남겨주신 의견들은 다 잘 봤습니다 🙂

특히, Template 라는 이름을 가진 클래스의 목적이 인상 깊었습니다. 🫡🫡

아톰이 남겨주신 질문들에 대해 답변 남겼으니 2단계 넘어가기 전 가볍게 봐주시면 좋을거 같아요 ☺️.
2단계도 화이팅입니다!

2024-10-10 00:49 UTC, merged