[1단계 - JDBC 라이브러리 구현하기] 시소(신지송) 미션 제출합니다.
woowacourse/java-jdbc pull request #657
Opened 2024-10-05 15:13 UTC by shin-jisong

안녕하세요 낙낙!
벌써 마지막 미션이네요 🥲
끝까지 열심히 달려 봅시다 잘 부탁드려요 👍

2024-10-06 06:27 UTC, nak-honest requested changes
안녕하세요 시소!!

리뷰어로 만나 뵙게 되어 너무 반갑습니다 :)

간단한 리뷰들 남겼으니 확인해 주시면 감사하겠습니다!!
시소도 마지막 미션 끝까지 화이팅이에요!!

2024-10-06 06:27 UTC, nak-honest commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +                }
이중 try 로 인해 현재 Indent 가 3인데요!!

메소드 분리를 통해 try-catch 문 하나만 사용해도 좋을 것 같아요!!

2024-10-06 06:27 UTC, nak-honest commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +
그리고 자원 해제만을 위해 try 문을 사용하는 것에 대해 어떻게 생각하실까요?
시소가 생각하시는 try 문의 역할은 무엇인가요??

2024-10-06 06:27 UTC, nak-honest commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +    }
기존에 있는 예외를 잘 활용해주셨네요 👍

2024-10-06 06:27 UTC, nak-honest commented on app/src/main/java/com/techcourse/domain/User.java
> +    }
현재 `equals` 는 id에 대해서만 비교하고 있고,
`hashCode` 는 여러 필드를 비교하고 있는데요!!

동등한(논리적으로 같은) 두 객체가 서로 다른 해시코드를 반환해도 괜찮은 것일까요?

2024-10-06 06:27 UTC, nak-honest commented on jdbc/build.gradle
> +    testImplementation project(path: ':app')
현재 jdbc 모듈에서 app 모듈을 의존중인데요!

아마 User 때문에 위와같이 의존성을 추가해 주신 것 같아요!

jdbc 가 구체적인 개발자의 코드를 알아도 괜찮은 것일까요?

2024-10-06 06:27 UTC, nak-honest commented on jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
> +    );
`resultSet -> new User(1L, "gugu", ...)`

예를들어 `userRowMapper`를 위와 같이 정의하면 resultSet의 각 메소드를 mock으로 처리하지 않아도 되기 때문에, 좀 더 편하게 구현할 수 있을 것 같네요!!
하지만 시소의 방식이 좀 더 일반적인 사용 방식과 비슷하기 때문에 그대로 두는 것도 좋다고 생각합니닷!

편하게 의견 주세욥!!

2024-10-06 06:27 UTC, nak-honest commented on jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
> +        when(preparedStatement.executeQuery()).thenReturn(resultSet);
`when(dataSource.getConnection()).thenReturn(connection);` 처럼, 반복적으로 설정하는 mock 객체간의 의존성을 `@BeforeEach`에서 해도 좋을 것 같아요!!

2024-10-06 07:49 UTC, shin-jisong commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +        }
상황에 따라 적절한 `DataAccessException`으로 변경해 주었습니다! 👍

2024-10-06 07:56 UTC, shin-jisong commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +                }
실제 구현을 참고하여 `IncorrectResultSizeDataAccessException` 예외를 던지는 방향으로 구현하였습니다!

2024-10-06 07:58 UTC, shin-jisong commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +                }
확실히 가독성이 떨어지네요 👀
Indent를 1로 되게 분리해 주었고 각 메서드에 적절한 이름을 명명해 주었습니다

2024-10-06 08:28 UTC, shin-jisong commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +
해당 코드에서는 예외 처리와 자원 해제 두 가지의 역할을 하고 있다 생각합니다
현재 코드 리팩토링으로 적절한 예외 상황을 추가해 주었어요

 Java 7 이후에 Java에서 지원해 주는 try-with-resources 구문으로 try-catch는 단순 예외 처리만이 아닌 Java 정책으로 자원 해제의 역할까지 맡고 있다 생각합니다
그 과정에서 발생하는 예외 처리 또한 중요한 역할이라 생각하고요 😊

2024-10-06 08:29 UTC, shin-jisong commented on app/src/main/java/com/techcourse/domain/User.java
> +    }
hashCode 또한 id에 대해서만 처리하도록 변경하였습니다!

2024-10-06 08:33 UTC, shin-jisong commented on jdbc/build.gradle
> +    testImplementation project(path: ':app')
같이 쓰려다 딱 걸렸네요 ㅎㅎ...
`TestUser` 추가해 주었습니다!

2024-10-06 08:34 UTC, shin-jisong commented on jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
> +    );
userRowMapper를 유연하게 두어야 추후 테스트가 추가되었을 때 불편함이 줄어들 것 같아 유지하는 방향을 선택하였습니다!

2024-10-06 08:37 UTC, shin-jisong commented on jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
> +        when(preparedStatement.executeQuery()).thenReturn(resultSet);
`when(preparedStatement.executeQuery()).thenReturn(resultSet);` 구문만 반복되고 있어 `@BeforeEach`로 옮겨 주었습니다!
나머지 설정 구문은 함수로 따로 리팩토링하여 테스트하는 부분에 집중해 보았습니다 👍

2024-10-07 04:43 UTC, nak-honest commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +
아하 네네!!
답변 감사합니다 시소!

다만 저는 catch 없이 try 문만 적으셔서 여쭈어 본 것이었어요!!
현재는 해당 부분이 하나의 try-catch로 묶였으니 넘어가셔도 좋을 것 같습니다 ㅎㅎ

2024-10-07 04:52 UTC, nak-honest approved these changes
안녕하세요 시소!

요구사항도 충분히 만족했고, 리뷰도 잘 반영해주셔서 merge 해 드리겠습니다!

간단한 테스트 코드 추가를 요청드렸는데 해당 부분은 다음 단계에서 반영해주세요!

2024-10-07 04:52 UTC, nak-honest commented on jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
>      public void testQueryForObjectNotFound() throws SQLException {
데이터가 존재하지 않는 경우 뿐만 아니라, 다수의 데이터 반환시에도 예외가 발생하는 것을 테스트 하면 좋을 것 같아요!

2024-10-07 04:52 UTC, merged