[1단계 - JDBC 라이브러리 구현하기] 리건(이한길) 미션 제출합니다.
woowacourse/java-jdbc pull request #660
Opened 2024-10-05 16:02 UTC by hangillee

안녕하세요, 알파카! 🦙
리뷰어로 만나니 더 반가운 것 같습니다.

알파카는 `JdbcTemplate` 테스트를 어떻게 작성하셨나요?
저는 모두 Mocking을 통해서 작성했습니다. 알파카의 테스트 전략이 궁금합니다!

리뷰 잘 부탁드립니다!

2024-10-07 07:45 UTC, slimsha2dy requested changes
안녕하세요 리건! 이렇게 미션 리뷰로 만나니까 또 반갑네요 ㅎㅎ
전체적으로 딱 미션 구현사항에 맞게 깔끔하게 짜주신 것 같습니다. 덕분에 코드 리뷰를 원활하게 할 수 있었습니다. 그래서 리뷰는 좀 지엽적인 부분 위주로 달게 된 것 같아요.. 제 의견이니 가볍게 참고하시고 반영할 부분만 반영하시면 될 것 같아요!
`JdbcTemplate` 테스트는 저도 리건처럼 Mocking으로 해결했는데요. 제대로 된 쿼리를 작성했더라도 db에 잘 반영되는지를 확인할 수 없는 부분이 아쉽지만 이거는 `JdbcTemplate` 자체보다는 `DatasSource` 등과 관련된 부분이라고 생각합니다. 그래서 테스트가 `JdbcTemplate`의 동작은 잘 검증하고 있다고 생각합니다.
과제 자체는 훌륭하게 잘 해주신 것 같아서 다음 리뷰 때는 머지를 할 것 같습니다!

2024-10-07 07:45 UTC, slimsha2dy commented on app/src/main/java/com/techcourse/dao/UserDao.java
> +        jdbcTemplate.update(sql, user.getAccount(), user.getPassword(), user.getEmail(), user.getId());
`id`는 primary key라 update하면 위험할 것 같은데요!
<img width="288" alt="스크린샷 2024-10-07 오후 4 18 00" src="https://github.com/user-attachments/assets/8be8cfaf-3289-4035-97d2-66715ab2e1ee">

2024-10-07 07:45 UTC, slimsha2dy commented on app/src/main/java/com/techcourse/dao/UserDao.java
>      }
사소한 부분인데 의견이 궁금합니다!
`RowMapper`는 바뀌지 않는 만큼 상수 필드로 사용해도 될 것 같은데 메서드로 구현하신 이유가 따로 있으실까요?

2024-10-07 07:45 UTC, slimsha2dy commented on app/src/main/java/com/techcourse/dao/UserDao.java
>      }
두 생성자 중 하나만 있어도 될 것 같은데 리건씌는 어떻게 생각하시나요?

2024-10-07 07:45 UTC, slimsha2dy commented on app/src/test/java/com/techcourse/dao/UserDaoTest.java
>          userDao = new UserDao(DataSourceConfig.getInstance());
사소한 부분이지만 이것도`UserDao`의 생성자에 위의 `jdbcTemplate`를 넣어주면 굳이 내부적으로 `JdbcTemplate`를 또 만들 필요가 없을 것 같아요 ㅎㅎ

2024-10-07 07:45 UTC, slimsha2dy commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +            pstmt.setObject(i + MAXIMUM_QUERY_FOR_OBJECT_RESULT, args[i]);
`setObject`가 1-based여서 1을 추가한 부분으로 보이는데 이 부분에 `MAXIMUM_QUERY_FOR_OBJECT_RESULT`라는 `queryForObject`의 최대 개수 상수를 사용해서 사알짝 헷갈리네요.
`SET_OBJECT_BASE` 등으로 따로 관리해주는 건 어떻게 생각하시나요구르트아줌마.

2024-10-07 07:45 UTC, slimsha2dy commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +    public void update(final String sql, Object... args) {
이 미션이 완벽하게 `JdbcTemplate`를 구현하는 건 아니지만 실제 `update` 인터페이스를 보면 업데이트한 tuple의 개수를 int로 반환하더라구요.
이에 대한 활용성이 없다고 생각하셔서 아무 것도 반환하지 않도록 구현하셨나요? 리건의 의견이 궁금합니다!

2024-10-07 07:45 UTC, slimsha2dy commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +        }
```suggestion
        if (results.size() != MAXIMUM_QUERY_FOR_OBJECT_RESULT) {
            throw new DataAccessException(QUERY_RESULT_EXCEPTION_MESSAGE + results.size());
        }
```

이런 식으로도 가능할 것 같은데 굳이 분리하신 이유가 있을까요?

2024-10-07 07:45 UTC, slimsha2dy commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +    }
`ResultSet`을 `close()` 해주어야 할까요? 🤔

2024-10-07 07:45 UTC, slimsha2dy commented on jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
> +    void verifyResourceClosed() throws SQLException {
오 전 이 경우는 생각 못했는데 테스트해주셨네요. 👍
저도 갖다 써야겠네요 ㅎㅎ

2024-10-07 13:31 UTC, slimsha2dy requested changes
안녕하세요 달려다가 까먹고 못 단 부분이 생각 나서 급하게 추가했습니다 ㅎㅎ 이 부분도 확인 부탁드릴게요!

2024-10-07 14:46 UTC, hangillee commented on app/src/main/java/com/techcourse/dao/UserDao.java
> +        jdbcTemplate.update(sql, user.getAccount(), user.getPassword(), user.getEmail(), user.getId());
오우 이건 고쳐놓겠습니다. 확실히 위험하네요!

2024-10-07 14:48 UTC, hangillee commented on app/src/main/java/com/techcourse/dao/UserDao.java
>      }
Lambda 구문이다 보니 굳이 상수로 둘 필요를 느끼지 못했습니다!
근데 상수로 뒀을 때, 멀티 스레드 환경에서 문제가 발생하진 않을까요?

2024-10-07 14:51 UTC, hangillee commented on app/src/main/java/com/techcourse/dao/UserDao.java
>      }
두 생성자 모두 테스트에서 활용되다보니 미션에서 제공되는 코드를 최대한 변경하지 않는 선에서 유지하려했습니다.

2024-10-07 15:07 UTC, hangillee commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +            pstmt.setObject(i + MAXIMUM_QUERY_FOR_OBJECT_RESULT, args[i]);
동의합니다. 수정해볼게용~

2024-10-07 15:28 UTC, hangillee commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +    public void update(final String sql, Object... args) {
네 맞습니다. 아직은 해당 정보를 활용하는 곳이 전혀 없어서 `void`로 구현했습니다!
추후에 요구사항이 생기면 리팩토링하는 재미도 챙겨보려구요 😁

2024-10-07 15:40 UTC, hangillee commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +        }
아무 생각 없이 조회 결과가 없을 때도 예외가 발생해야 하고
2개 이상일 때도 예외가 발생해야 한다고 생각해서 이렇게 구현한 것 같습니다. 고쳐보겠습니다!

2024-10-07 15:44 UTC, hangillee commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +    }
Connection을 활용하는 모든 객체는 명시적으로 닫아줘야 한다고 합니다.

해당 내용과 관련된 문서입니다!
[Must JDBC Resultsets and Statements be closed separately although the Connection is closed afterwards?](https://stackoverflow.com/questions/4507440/must-jdbc-resultsets-and-statements-be-closed-separately-although-the-connection)
[Explicitly closing Statements, ResultSets, and Connections](https://docs.oracle.com/javadb/10.4.2.1/devguide/cdevconcepts839085.html)

2024-10-07 16:03 UTC, slimsha2dy commented on app/src/main/java/com/techcourse/dao/UserDao.java
>      }
오호.. 전 반대로 Lambda 구문이다 보니 오히려 메서드로 굳이 빼지 않고 사용할 수 있는 점이 장점이라 생각해 상수로 사용했었습니다.
또한 상수이기 때문에 thread-safe하다고 생각되는데 혹시 제가 놓친 점이 있을까요? 상수로 뒀을 때 여러 스레드가 동시에 참조하더라도 문제가 생길 부분은 잘 떠오르지 않네요.

2024-10-07 16:05 UTC, slimsha2dy commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +    }
실제로 `JdbcTemplate`의 인터페이스를 확인해 봐도 두 메서드는 분리돼있더라구요.
저는 가변인자의 장점을 살리고 싶어서 + 이로 인한 오버헤드도 없다고 생각해 하나로 사용하도록 구현했는데 리건의 말씀도 일리가 있는 것 같습니다.

2024-10-07 16:33 UTC, slimsha2dy commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +    }
Jdbc 스펙에서는 `Statement`를 닫으면 `ResultSet`을 닫아주는데 `Connection`과 달리 풀링하지 않기 때문에 굳이 명시적으로 close할 필요는 없다고 생각했습니다.
해당 글을 확인해보니 `ResultSet`을 명시적으로 닫는 것은 과해 보인다는 의견이 있기도 하네요..ㅎㅎ

실제로 스펙처럼 하위 close를 지원하지 않는 구현체를 만날 일이 있을지는 모르겠지만, 그래도 들어가는 수고에 비해 생길 수 있는 위험성은 꽤나 크다고 생각하기 때문에 리건의 구현도 합리적인 것 같네요.

2024-10-07 16:37 UTC, slimsha2dy requested changes
확인해보니 수정하신다고 한 부분 중 `User`의 `id`를 업데이트하는 로직이 남아있네요.
이 부분만 고쳐주시면 바로 머지하겠습니다~
추가적으로 의견 또 달아놨으니 가볍게 확인 부탁드릴게요 ^~^

2024-10-07 16:37 UTC, slimsha2dy commented on app/src/main/java/com/techcourse/dao/UserDao.java
> +        jdbcTemplate.update(sql, user.getAccount(), user.getPassword(), user.getEmail(), user.getId());
이 부분 아직 적용이 안 된 것 같습니다!!

2024-10-08 01:33 UTC, slimsha2dy approved these changes
수고하셨습니다 리건! 다음 단계에서 또 봬용~

2024-10-08 01:33 UTC, slimsha2dy commented on app/src/main/java/com/techcourse/dao/UserDao.java
> +        jdbcTemplate.update(sql, user.getAccount(), user.getPassword(), user.getEmail(), user.getId());
헉 where 절에 쓰이는 id였네요..ㅎㅎ

2024-10-08 01:33 UTC, merged