[1단계 - JDBC 라이브러리 구현하기] - 호기(조호연) 미션 제출합니다.
woowacourse/java-jdbc pull request #676
Opened 2024-10-06 10:13 UTC by hoyeonyy

안녕하세요 테바!

레벨 2 이후에 오랜만에 뵙는 것 같아요!
잘부탁드립니다~!

2024-10-09 10:12 UTC, ksk0605 requested changes
안녕하세요 호기~
전반적으로 잘 작성해주셨네요! jdbcTemplate 의 메서드 명도 기존과 다르게 가려고 노력하셨나봐요 ㅋㅋ 본래 코드를 보지 않으시려는 노력이 있었던 것으로 보여서 멋지다는 생각이 듭니다. 

다음단계가 중복 제거인데 이미 많이 이루어져있어서 놀랐습니다. 
남긴 코멘트 확인해주시고 답변 달아주세요! 
큰 문제없으면 다음번에 머지하겠습니다.

2024-10-09 10:12 UTC, ksk0605 commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +    private final ResultMapper resultMapper;
jdbcTemplate 의 반복되는 코드들을 효과적으로 제거하셨네요! 호기의 실력에 감탄했습니다. 
다만, 한가지 여쭤보고 싶은 부분이 있어요. 

<img width="482" alt="Screenshot 2024-10-09 at 6 29 33 PM" src="https://github.com/user-attachments/assets/25d7560f-758d-4a9d-a7b0-347071353924">  

커밋로그를 확인해보면 `ResultMapper`, `QueryExecution`, `ParameterBinder` 를 먼저 만드신 후에 
JdbcTemplate을 구현하고 테스트를 작성하셨어요.

이 과정에서 `ResultMapper`, `QueryExecution`, `ParameterBinder` 의 코드 수정이 없고 테스트 작성도 안되어있는 것을 보니 세 객체들이 JdbcTemplate 구현에 특별한 버그를 일으키지는 않은 것으로 보여요. 

그런데 **분리된 객체를 사용하는 입장인 JdbcTemplate 이 작성되기도 전에 책임을 분리할 객체들이 제대로 작동될 것 이라는 확신을 테스트 코드 없이 어떻게 얻으셨을까?** 하는 궁금증이 생깁니다. 

만약 개발과정 중 bottom up 방식을 사용하여 하위 개념부터 접근하셨다면 그 개념들에 대한 테스트 코드 없이 개발하기는 어렵지 않을까 하는게 제 개인의견입니다. 

미리 설계를 진행한 이후에 개발을 진행하셨을 수도 있고 아니면 JdbcTemplate 과 함께 다 잘 작동되는 걸 확인하고 분리된 객체를 먼저 커밋하셨을 수도 있을 것 같아요. 

호기의 스토리가 듣고 싶어요 ㅎㅎ

2024-10-09 10:12 UTC, ksk0605 commented on jdbc/src/main/java/com/interface21/jdbc/core/ParameterBinder.java
> +		AtomicInteger index = new AtomicInteger(1);
그냥 integer가 아닌 AtomicInteger 를 사용한 근거가 무엇인지 듣고 싶어요 ㅎㅎ

그리고 숫자 1은 의미를 담아서 상수로 분리하는 것을 고려해볼 수 있겠습니다.

2024-10-09 10:12 UTC, ksk0605 commented on jdbc/src/main/java/com/interface21/jdbc/core/ResultMapper.java
> +		int rowNum = 1;
이 숫자 1도 의미를 담아보는 것을 고려해볼 수 있겠네요.

2024-10-10 01:57 UTC, hoyeonyy commented on jdbc/src/main/java/com/interface21/jdbc/core/ParameterBinder.java
> +	private void bindParameter(final PreparedStatement preparedStatement, int index, Object arg) {
아니요,,! 주어진거 쓰고 고치다보니 붙었던 것 같아요,,

일관성을 위해 final 삭제했습니다

2024-10-10 02:03 UTC, hoyeonyy commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +    private final ResultMapper resultMapper;
커밋 로그를 꼼꼼하게 작성하지 않는 저를 반성하게 되네요,,

사실 커밋은 전부 완성시켜놓고, 분리하고, 돌아가는 걸 확인한 다음에 커밋을 남겼습니다,,!
Top down 방식으로 진행하고 커밋만 bottom 부터 남긴 것 같아요,,!

2024-10-11 05:04 UTC, ksk0605 commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +    private final ResultMapper resultMapper;
개인적으로는 커밋 로그의 순서도 개발 진행 순서를 알려주기에 매우 중요하다고 생각합니다. 

[원자적 커밋](https://ko.wikipedia.org/wiki/%EC%9B%90%EC%9E%90%EC%A0%81_%EC%BB%A4%EB%B0%8B)을 습관화 해야 git 이 해결하고자 하는 문제인 버전관리에 더 부합하는 코드 관리를 할 수 있겠죠. 
위 기록에서 만약 JdbcTemplate 를 수정한 시점 이전으로 돌아간다면 멀쩡히 돌아가던 jdbcTemplate 부터 다시 작성해야 할 거에요. 실무에서 이런 일이 일어난다고 생각하면 아주 끔찍하니까요 ㅋㅋ

2024-10-11 05:08 UTC, ksk0605 commented on jdbc/src/main/java/com/interface21/jdbc/core/ParameterBinder.java
> +		AtomicInteger index = new AtomicInteger(1);
근거가 있는 의견은 언제나 지지합니다👍
저는 `AtomicInteger`를 사용하셔서 동시성 제어가 필요한 부분이 있는가? 하는 생각이 먼저 들었어요. 
우리가 많이 신경쓰는 **가독성이라는 것이 정말 읽기 쉬운 코드 만을 의미하는가?** 는 생각해볼 지점인 듯 합니다. 

저는 가독성에 대한 정의를 
> 읽기 쉬운 동시에 작성자의 의도가 드러나는 코드 

라고 내리고 있습니다. 꼭 AtomicInteger 가 아니더라도 특정한 목적을 가지는 라이브러리는 '그 목적'을 이룬다는 개발자의 의도가 드러나는 것이니까요.

바꾸라는 의미는 아니구요! 호기와 함께 생각을 나누고 싶었습니다 😀

2024-10-11 05:09 UTC, ksk0605 approved these changes
1단계는 여기서 마무리해도 될 것 같네요. 
2단계에서 뵙죠!

2024-10-11 05:09 UTC, merged