[1단계 - JDBC 라이브러리 구현하기] 폰드(권규택) 미션 제출합니다.
woowacourse/java-jdbc pull request #679
Opened 2024-10-06 13:47 UTC by tackyu

안녕하세요 커찬, 폰드입니다🙇‍♂️
`JdbcTemplateTest`에서 자원 반환 부분만 확인하였는데,
어떻게 개선할 수 있을지 혹시 의견 있으시다면 여쭙고 싶네요!
리뷰 잘 부탁드리겠습니다!

2024-10-07 05:42 UTC, leegwichan requested changes
안녕하세요 폰드~! 커찬입니다!늦지 않게 딱 맞춰 리뷰 보냅니다~
일단 제가 인식하는 부분부터 리뷰 남겨 보았어요! 확인 부탁드립니다!
혹시 궁금하거나 이해 안가는 부분 있으시면 DM 보내주시거나 나이스샷 강의장으로 찾아와주세요~ 친절하게 답변 드리겠습니다!

2024-10-07 05:42 UTC, leegwichan commented on app/src/main/java/com/techcourse/dao/UserDao.java
> +    private final JdbcTemplate jdbcTemplate;
사용하지 않는 `DataSource`는 제거하는 것 어떨까요?

2024-10-07 05:42 UTC, leegwichan commented on app/src/main/java/com/techcourse/dao/UserDao.java
> +    }
[질문] sql을 `String`을 명시하는 대신 `var`라고 사용한 이유가 있나요?

2024-10-07 05:42 UTC, leegwichan commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +    }
쿼리의 결과가 2개 이상일 경우에는 상위 1개의 결과를 반환할 것 같아요.
하지만 `queryForObject()`를 사용하는 개발자는 결과가 1개라고 예상하고 사용했을 것이라 생각해요.
결과가 2개 이상일 경우에는 에러를 발생해야 하지 않을까요?

2024-10-07 05:42 UTC, leegwichan commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +    }
`setPreparedStatement()`를 호출하는 곳이 getResultSet에 있어도 될까요?
저는 `getPreparedStatement()`에서 `setPreparedStatement()`를 호출하는 것이 좋아 보여요.

```java
    public <T> List<T> queryForObject(final String sql, final RowMapper<T> rowMapper, final Object... params) {
        try (Connection connection = getConnection();
             PreparedStatement preparedStatement = getPreparedStatement(sql, connection);
             ResultSet resultSet = getResultSet(params, preparedStatement)) {
            
            ...

        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

```

위와 같은 상황에서 "어 어디서 PreparedStatement에서 파라미터를 설정하지?" 라고 하면 저는 `getPreparedStatemet()`라고 생각할 것 같아요. (물론 인자를 보면 대충 예상은 할 수 있겠지만요... ㅎㅎ) 폰드의 생각은 어떠신가요?

2024-10-07 05:42 UTC, leegwichan commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +
개행 지워주세요 ㅎㅎ

2024-10-07 05:42 UTC, leegwichan commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +            }
[질문] 디버그를 호출하는 폰드만의 기준이 있나요?

2024-10-07 05:42 UTC, leegwichan commented on jdbc/src/main/java/com/interface21/jdbc/core/RowMapper.java
> +}
`RowMapper`를 함수형 인터페이스로 사용할 것이라면, `@FunctionalInterface`를 붙이는 건 어떨까요?

2024-10-07 05:42 UTC, leegwichan commented on jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
JdbcTemplateTest까지 잘 작성해 주셨네요 👍 
[질문] JdbcTemplateTest를 통해 JdbcTemplate의 어떤 것을 테스트하고 싶으셨나요? 그리고 그 이유는 무엇인가요?

2024-10-07 08:22 UTC, tackyu commented on app/src/main/java/com/techcourse/dao/UserDao.java
> +    private final JdbcTemplate jdbcTemplate;
`JdbcTemplate`을 의존하고 있어서 제거해도 괜찮을 것 같네요!

2024-10-07 08:39 UTC, tackyu commented on app/src/main/java/com/techcourse/dao/UserDao.java
> +    }
예시 코드와 그대로 사용해버렸네요😅
직접적인 자료형 명시가 더 나은것 같습니다!

2024-10-07 15:43 UTC, tackyu commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +    }
`resultSet.isLast()`로 검증하게끔 했는데 의도하신 바가 맞을까요?
\+ query와 queryForObject 서로 메서드 명이 바뀌어서 사용 되고 있는 부분도 수정했습니다!

2024-10-07 18:10 UTC, tackyu commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +    }
`getPreparedStatement()`에서 값을 설정하는 게 더 자연스러운 것 같아요!
감사합니다!

2024-10-08 13:30 UTC, tackyu commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +            }
기준을 아직 명확히 세우지 못한 것 같아요.
개발 및 테스트를 위해 확인 할 로그라는 의미에서 `DEBUG` 설정을 했습니다.

2024-10-08 14:02 UTC, tackyu commented on jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
JdbcTemplate이 DataSource를 통해 얻어오는 자원들을 잘 반환하는 지 테스트 하고 싶었습니다.
효율적인 자원 관리가 어플리케이션의 성능 측면에서 주요하다 생각했습니다!

2024-10-09 04:21 UTC, leegwichan approved these changes
안녕하세요 폰드! 리뷰어 커찬입니다!
리뷰 남긴 부분 다 잘 반영되어 있는 것을 확인해서 머지하도록 하겠습니다.
다음 단계도 화이팅입니다!

추가적으로 누락했던 폰드의 질문에 답변 남깁니다.

> JdbcTemplateTest에서 자원 반환 부분만 확인하였는데,
어떻게 개선할 수 있을지 혹시 의견 있으시다면 여쭙고 싶네요!

원래 Mockist였던 저라면, Mockito를 이용해서 각각을 Mock으로 선언해서 테스트를 진행했을 것 같아요! 실제 어떤 객체의 어떤 메서드를 호출하는지를 검증하는 느낌으로요!

Mock을 쓰면 대규모 리팩토링 등을 할 때, 코드를 처음부터 다시 써야하는 불상사가 있어 이제는 최대한 실제 객체를 사용하려 하는데요. 그래서 build.gradle에 testImplementation으로 H2 데이터베이스를 추가해서 테스트를 구성해 보았습니다. 혹시 코드가 궁금하시다면 제 PR 들어가서 참고해 보셔도 좋을 것 같아요!
https://github.com/woowacourse/java-jdbc/pull/665/files#diff-6ba9aa2207da9aadb67de162c882ed45b76d269cc3b547d833a2a61fc206bd36

2024-10-09 04:21 UTC, leegwichan commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +            return rowMapper.mapRow(resultSet, resultSet.getRow());
> resultSet.isLast()로 검증하게끔 했는데 의도하신 바가 맞을까요?

넵 맞습니다~

> + query와 queryForObject 서로 메서드 명이 바뀌어서 사용 되고 있는 부분도 수정했습니다!

확인 했습니다!

2024-10-09 04:22 UTC, merged