[1단계 - JDBC 라이브러리 구현하기] 산초(나영서) 미션 제출합니다.
woowacourse/java-jdbc pull request #689
Opened 2024-10-06 18:40 UTC by nayonsoso

안녕하세요 카피😊
리뷰어로 만나서 정말 반갑습니다.

전반적인 내용은 모두 LMS 에 나온 그대로 구현했습니다.
그럼 이번 리뷰도 잘 부탁드립니다!😇

2024-10-07 10:47 UTC, tkdgur0906 requested changes
안녕하세요 산초!
리뷰이로 만나게되서 반갑습니다~ㅎㅎ

요구사항 잘 만족해주셨네요!
몇가지 리뷰 남겼는데 확인부탁드려요!
그리고 JdbcTemplate 테스트가 실패하고 있는데 이것도 확인 부탁드립니다~~

2024-10-07 10:47 UTC, tkdgur0906 commented on jdbc/build.gradle
> +    implementation 'com.h2database:h2:2.2.224'
h2 의존성을 추가하신 이유가 있을까요?

2024-10-07 10:47 UTC, tkdgur0906 commented on app/src/main/java/com/techcourse/dao/UserDao.java
> +    public static final String SELECT_BY_ACCOUNT_QUERY = "select * from users where account = ?";
메서드 내에 넣는 것 대신 static으로 분리하는 것을 선호하시나요?
메서드 내에서 한번에 볼 수 없어서 불편할 수도 있을 것 같은데 산초의 생각이 궁금합니다!
(그냥 궁금한거니 주관대로 하셔도 됩니다)

2024-10-07 10:47 UTC, tkdgur0906 commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +            return null;
단건 조회 시 데이터가 없을 때 null을 반환하는 이유가 있나요?
NPE의 가능성이 없을까요?

2024-10-07 10:47 UTC, tkdgur0906 commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +        }
SQLException을 DataAccessException으로 치환해서 다시 던지는 이유가 있을까요?

2024-10-07 10:47 UTC, tkdgur0906 commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +    public <T> T queryForObject(Function<ResultSet, T> mapper, String sql, Object... args) {
queryForList와 queryForObejct의 중복코드가 존재하는 것 같은데
분리할 수 있는 방법이 있을까요?

2024-10-07 10:47 UTC, tkdgur0906 commented on jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
> +    private static JdbcTemplate jdbcTemplate;
현재 작성하신 테스트는 jdbcTemplate 테스트보다는 DAO 테스트에 가까운 것 같아요!
sql에 의존하지 않는 JdbcTemplate의 테스트를 작성해봐도 좋을 것 같아요!

2024-10-07 11:03 UTC, unifolio0 reviewed
산초가 코드를 엄청 잘 짰다고 소문이 자자해서 구경하러 왔어요!☺️☺️

2024-10-07 11:03 UTC, unifolio0 commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +            }
try문이 들어오면서 depth 관리가 힘든 건 알지만 그래도 depth를 1로 만들어보는 것도 괜찮을 것 같아요!☺️☺️

2024-10-08 02:25 UTC, nayonsoso commented on jdbc/build.gradle
> +    implementation 'com.h2database:h2:2.2.224'
JdbTemplate 을 테스트하기 위해서 추가해주었습니다😅
처음에는 JdbcTemplateTest 를 위해서 모킹을 했었는데요,
mock 을 하다보니 제가 지금 하고 있는게 '무엇을 위한 테스트인지?' 그리고 '테스트 대상의 동작을 테스트코드에서 구체적으로 보여주고 있는게 아닌지?' 라는 생각이 들었습니다.
그래서 통합테스트라고 생각하고 mock 없에 JdbcTemplateTest 를 작성하고 싶었고,
그렇게 하기 위해서는 데이터베이스와의 커넥션이 필요했기 때문에 H2 의존성을 사용했습니다

2024-10-08 02:25 UTC, nayonsoso commented on app/src/main/java/com/techcourse/dao/UserDao.java
> +    public static final String SELECT_BY_ACCOUNT_QUERY = "select * from users where account = ?";
네 저는 static 으로 분리하는 것을 선호합니다!

2024-10-08 02:30 UTC, nayonsoso commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +            return null;
사실 "null을 반환한다"고 합의만 된다면 문제가 없을 것 같긴해요.
예를 들어서 Collection 의 몇몇 조회 메서드 같은 경우에는 값이 없을 때 null 을 반환하는 것처럼요,
이런 질문을 하신걸 보면 카피의 생각은 다른 것 같은데, 카피의 의견을 듣고 싶어요 👂

2024-10-08 02:33 UTC, nayonsoso commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +        }
SQLException는 ChckedException 이고, 
DataAccessException는 UnchecktedException 이기 때문이에요!
JdbcTemplate 의 메서드를 호출하는 곳(e.g. 서비스)에서 Throws 를 하거나, 다시 try-catch 하지 않을 수 있도록 UnchecktedException 으로 바꿔주었어요.

2024-10-08 16:01 UTC, nayonsoso commented on jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
> +    private static JdbcTemplate jdbcTemplate;
위에 작성한 내용으로 대체합니다😊

2024-10-08 17:26 UTC, nayonsoso commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +    public void command(String sql, Object... args) {
command 는 "변경"과 관련된 모든 쿼리를 의미한거였어요!
제가 최근에 CQRS 를 접했는데, 이 개념에서는 
command 를 데이터에 변경을 하는 모든 명령으로 보고
query 를 조회 로직으로 봤더라고요.

이러한 정의가 실제로 많이 사용되는 것 같아서 함수명으로 적용해본 것입니다~

2024-10-08 17:29 UTC, nayonsoso commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +            }
https://github.com/woowacourse/java-jdbc/commit/1ce43bfc93aa2830fbb22f6ec595a323e0bc2254

이 커밋으로 "쿼리 실행 전후로 connection 으로부터 preparedStatement 실행하는 로직"을 분리해봤습니다!

2024-10-08 17:29 UTC, nayonsoso commented
안녕하세요 카피! (그리고 비토🙄)
리뷰 주신 내용들 반영 후 다시 요청드립니다 ~ 👍

2024-10-09 10:25 UTC, tkdgur0906 commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +            return null;
설계의 의도에 따라 다를 것 같은데, 말씀하신 3가지 방법 모두 다 가능할 것 같아요!
저 같은 경우는 null을 안전하게 처리하기 위해 Optional을 사용할 것 같습니다!

실제 JdbcTemplate에서는 queryForObject에 대해 반드시 하나의 결과가 있어야 한다고 설계해서 예외를 던지고 있네요.
그래서 Optional을 사용한 방식의 도입에 대해서 여러 논의도 있었는데 심심할 때 읽어보셔도 좋을 것 같아요!
https://github.com/spring-projects/spring-framework/issues/30927

2024-10-09 10:28 UTC, tkdgur0906 approved these changes
고생많으셨습니다 산초!
1단계는 어느정도 마무리 된 것 같아 2단계 새로 진행하시죠!
2단계도 화이팅입니다~

2024-10-09 10:29 UTC, merged