[1단계 - JDBC 라이브러리 구현하기] 호티(윤주호) 미션 제출합니다.
woowacourse/java-jdbc pull request #693
Opened 2024-10-07 05:12 UTC by Ho-Tea

안녕하세요 안나!
리뷰어로 만나뵙게되어 반갑습니다 👋
최대한 간단하게 구성하기 위해 노력했고, 열심히 구현했습니다 😊
잘부탁드리겠습니다 🙇‍♂️

> 추가적으로 `queryForObject` 메서드에서 반환값이 아무것도 없거나 여러개인 경우에 예외를 던지게 구성했었는데, 기존 `UserDaoTest`에서 데이터를 넣은 후 따로 롤백이 이루어지지 않기에 임의로 새로운 데이터를 넣고 `findByAccount`를 검증하게 되었습니다

2024-10-08 01:01 UTC, Mingyum-Kim requested changes
안녕하세요 호티! 
리뷰어 안나입니다 ~ 
말씀하신 것처럼 열심히 구현하신 게 눈에 보이네요 👏👏👏

전략 패턴 사용이나 테스트 등 고민을 많이 하신 점이 느껴집니다. 
미션 진행하시느라 수고했어요! 몇 가지 의견과 질문을 남겨놨어요. 

좋은 화요일 되세요 ~

2024-10-08 07:13 UTC, Ho-Tea commented on jdbc/src/main/java/com/interface21/jdbc/core/RowMapper.java
> +    T mapRow(ResultSet rs) throws SQLException;
`mapRow`메서드에서 `ResultSet`을 객체로 매핑하는 과정에서
- 컬럼 이름 또는 인덱스가 잘못된 경우
  - `resultSet.getLong("id"), resultSet.getString("account")`와 같은 메서드를 호출할 때, 지정한 컬럼 이름이 실제 데이터베이스 테이블에 없거나, 이름을 잘못 입력한 경우.
- 데이터 형 변환 오류
  - `ResultSet`에서 컬럼 데이터를 읽을 때, 해당 데이터 형이 기대하는 형식과 다를 경우 예외가 발생할 수 있을 것 같습니다.

2024-10-08 07:15 UTC, Ho-Tea commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +                log.error("파라미터 바인딩에 실패하였습니다. index: {}, arg: {}, 예외 메세지: {}", index - 1, arg, e.getMessage(), e);
`Object` 순서에 의존하는 만큼 지금은 향상된 `for`문보다는 기존 `for`문을 이용하는게 더 나은것 같네요 👍

2024-10-08 07:23 UTC, Ho-Tea commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +    }
현재 `query` 메서드는 아래와 같은 형식으로 메서드의 인자로 `column`값을 받지 않고 있어서 
`preparedStatement`의 값 설정이 이루어지지 않고, 호출하는 과정이 필요하지 않았습니다!
``` java
    public <T> List<T> query(String sql, RowMapper<T> rowMapper) {
        return queryExecute(sql, (preparedStatement, query) -> {
            try (ResultSet resultSet = preparedStatement.executeQuery()) {
                return resultMapping(rowMapper, resultSet);
            }
        });
    }
```

2024-10-08 07:29 UTC, Ho-Tea commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +                throw new DataAccessException(e);
`SQLException`을 `JdbcTemplate`을 벗어나 `Dao` 까지 전파되게 한다는 것이 어색하게 다가왔습니다.
- (`SQLException`은 각 데이터베이스 벤더마다 발생하는 에러 코드나 메세지가 다를 수 있기 때문에, 이런 예외가 `Dao`까지 전파되면 응용 프로그램이 데이터베이스에 종속적이 될 위험이 있음)

그리하여 `DataAccessException`으로 변환하였습니다.

2024-10-08 07:33 UTC, Ho-Tea commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +    private <T> List<T> resultMapping(RowMapper<T> rowMapper, ResultSet resultSet) throws SQLException {
`<T>`는 제네릭 타입을 의미하며, 메서드가 다양한 데이터 타입을 처리할 수 있도록 해줍니다. 
- 메서드 내에서 사용할 데이터 타입을 호출 시점에 결정

그로인하여 메서드를 호출할 때, `T`가 어떤 타입으로 사용할지 결정되며 
예를 들어, `RowMapper<User>`를 넘기면 `T`는 `User`로 결정됩니다.
이를 통해 메서드가 특정 데이터 타입에 국한되지 않고 다양한 타입을 처리할 수 있어 유연한 데이터 타입 처리가 가능하게 됩니다!

2024-10-08 07:38 UTC, Ho-Tea commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +            return sqlExecutor.execute(preparedStatement, sql);
제일 큰 장점은 아무래도 자동으로 자원을 해제해주는 것이라고 생각됩니다.
- `try-with-resources` 구문을 사용하면, `Connection, PreparedStatement, ResultSet` 같은 `AutoCloseable` 인터페이스를 구현한 자원들이 자동으로 닫혀 명시적으로 `close()` 메서드를 호출하지 않아도, `try` 블록이 끝나는 즉시 자원을 자동으로 해제되게 됩니다.

2024-10-08 08:04 UTC, Ho-Tea commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +    private <T> T queryExecute(final String sql, final SqlExecutor<T> sqlExecutor) {
일반적으로 `private` 메서드는 가급적 해당 메서드를 호출하는 `public` 메서드 아래에 배치하여 해당 메서드의 구현을 가까이에서 참조하는 것이 맞지만, 위와같이 클래스 내에서 여러 곳에서 사용되는 메서드는 최상단에 위치시켜 흐름을 명확하게 보여주는 것이 낫네요!
반영하였습니다 👍

2024-10-08 09:32 UTC, Ho-Tea commented on app/src/test/java/com/techcourse/dao/UserDaoTest.java
현재 테스트 데어터 간의 격리가 이루어지지 않은 상태입니다. 
한 메서드의 디비작업이 롤백되지 않기 때문에 다른 테스트 메서드에 영향을 끼치는 상태라고 판단되어 
`schema.sql` 상의 `drop` 구문을 추가하였습니다.

2024-10-09 00:19 UTC, Mingyum-Kim commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +                throw new DataAccessException(e);
오호 그렇다면 예외 메시지를 그대로 담아 DataAccessException에 담는 것이 아니라 그 상황에 맞는 예외 메시지를 직접 작성해주는 것이 목적을 더 달성할 수 있겠네요 😀 이 부분은 선택적으로 반영해주세요!

2024-10-09 01:07 UTC, Mingyum-Kim commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +    }
아 제 말은
`select * from user where accout = ?` 이런 식으로 파라미터가 포함된 sql 이 실행되었을 때 현재 설계에서는 처리할 수 없다는 것을 말하고 싶었습니다!
이 부분에 대해서도 생각해보시면 좋을 것 같아요 ~

2024-10-09 01:09 UTC, Mingyum-Kim approved these changes
안녕하세요 호티 😀
피드백 빠르게 반영해주셨네요!

요구사항을 모두 만족하셔서 1단계는 빠르게 넘어가겠습니다. 추가로 궁금한 점을 달아놓았는데, 다음 단계 진행하시기 전에 한 번 체크해봐주세요!

다음 단계도 파이팅입니다!
즐거운 공휴일 되세요 ~

2024-10-09 01:10 UTC, merged