[1단계 - JDBC 라이브러리 구현하기] 잉크(이예찬) 미션 제출합니다.
woowacourse/java-jdbc pull request #695
Opened 2024-10-07 06:33 UTC by yechop

안녕하세요 카고
jdbc미션 잘 부탁드립니다!

2024-10-07 11:08 UTC, devhoya97 requested changes
안녕하세요 잉크! 리뷰어로 만나게 되다니 반갑습니다 ㅎㅎ 잉크와 페어프로그래밍하며 JPA 삽질하던 때가 새록새록하네요.

코드가 전반적으로 제 코드와 엄청 비슷해서 크게 코멘트 남길만한 부분을 찾지 못했어요. 코멘트 읽어보시고, 다음 번에 리뷰요청 주시면 바로 approve 드릴 것 같습니다!

2024-10-07 11:08 UTC, devhoya97 commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +            return mapResultSetToList(rowMapper, pstmt);
코드에 반영하지 않아도 되는 사소한 질문) mapResultSetToList 라는 메서드가 여기서도 호출되는데, 실제 메서드의 위치는 query보다 위에 있어요. 

레벨3 팀프로젝트시 저희 팀은 A메서드와 B메서드가 C메서드를 호출하고 있다면, C메서드는 A,B보다 아래에 두자는 컨벤션을 뒀는데요, 잉크는 메서드의 순서가 A, C, B가 더 적절하다고 보시나요?! 이유가 궁금합니다!

2024-10-08 05:14 UTC, yechop commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +            return mapResultSetToList(rowMapper, pstmt);
- d()  메서드도 b() , c()  메서드를 이용하지만 a() 가 먼저 메서드를 사용하니 a()  메서드 아래에 위치한다.

```java
class Example {

	public void a() {
		b();
		c();
	}
	
	private void b() {
		// ...
	}
	
	private void c() {
		// ...
	}
	
	public void d() {
		b();
		c();
	}
}
```
저희 팀은 위와 같은 컨벤션을 정해서 사용하고 있어요
mapResultSetToList() 은 query() 보다 더 위에 있는 메서드에서 사용하고있어서 순서를 이렇게 정했습니다.
뭐가 더 적절한지, 일반적인지는 모르겠지만 적응되니 불편하진 않아요!

2024-10-08 05:22 UTC, yechop commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +    }
네 필요한 검증이네요!!  추가했습니다

2024-10-08 06:07 UTC, devhoya97 commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +            return mapResultSetToList(rowMapper, pstmt);
아하 궁금했는데 답변 감사합니다 :)

2024-10-08 06:09 UTC, devhoya97 approved these changes
리뷰 반영해주신 부분 확인했습니다! 다음 단계로 넘어가보시죠 👍

2024-10-08 06:09 UTC, merged