[2단계 - JDBC 라이브러리 구현하기] 리니(이예린) 미션 제출합니다.
woowacourse/java-jdbc pull request #704
Opened 2024-10-07 15:47 UTC by linirini

시소, 안녕하세요~
1단계에서 이미 어느정도 리팩토링을 진행했다보니, 빠르게 2단계로 돌아왔습니다🖐️
이번 pr에서의 변경사항은 다음과 같아요!

- `PreparedStatementResolver` 분리
- `UserHistoryDao` 리팩터링

이번 리뷰도 잘 부탁드립니다:)

2024-10-09 06:31 UTC, shin-jisong requested changes
안녕하세요 리니!
미션을 살펴보고 리뷰를 남기느라 시간이 좀 소요되었네요 🥲
미션을 잘 구현해 주셔서 거의 리뷰 남길 것이 없었지만 살펴보거나 궁금한 부분들 몇 가지 남겼습니다 👍

2024-10-09 06:31 UTC, shin-jisong commented on study/src/test/java/transaction/stage2/Stage2Test.java
> +     * REQUIRED: defualt 설정: 활성화된 트랜잭션이 있는지 체크하고, 없다면 새로운 트랜잭션을 생성
학습 테스트를 열심히 학습해 주셨네요 👍

2024-10-09 06:31 UTC, shin-jisong commented on jdbc/src/main/java/com/interface21/jdbc/core/PreparedStatementResolver.java
> +public class PreparedStatementResolver {
저희 요구사항에서는 ` PreparedStatementSetter 인터페이스` 를 제시해 주었는데
리니는 어떤 판단으로 `PreparedStatementResolver 클래스`를 구현하였는지 궁금해요!

2024-10-09 06:31 UTC, shin-jisong commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> -            setParameters(ps, args);
사실 기존의 setParameters가 복잡한 로직이 아니었어서 이렇게 객체를 분리하는 건 역할 혹은 책임의 관리 측면이라 생각해요!
리니가 생각하는 JdbcTemplate의 책임은 무엇이라 PreparedStatementResolver를 분리하였나요?
혹은 분리하는 이유를 추가적으로 설명해 주시면 좋을 것 같아요 👀

2024-10-09 06:31 UTC, shin-jisong commented on jdbc/src/main/java/com/interface21/jdbc/core/PreparedStatementResolver.java
> +    public static void setParameters(PreparedStatement pstmt, Object... args) {
현재 args에 아무것도 입력하지 않을 경우에는 자동으로 객체가 맵핑되지만 
null을 넣을 경우 해당 로직에서 예외가 발생할 것 같아요!
적절한 처리를 해 주는 것 어떨까요?

2024-10-09 07:01 UTC, linirini commented on jdbc/src/main/java/com/interface21/jdbc/core/PreparedStatementResolver.java
> +public class PreparedStatementResolver {
LMS에서 `매번 PreparedStatementSetter 인터페이스를 구현하려니 번거롭다. 가변인자를 사용해서 좀더 편리하게 만들 수 없을까?`라는 부분에 저는 동감했습니다.
`RowMapper`를 예로 들어보자면, `RowMapper`는 데이터베이스에서 받은 결과를 어떤 객체로 매핑하고 싶은지에 따라 다양한 매핑 로직을 가질 수 있어요. 따라서, 확장성을 고려하여 함수형 인터페이스로 개발자가 필요에 맞게 구현할 수 있도록 만들었어요!
반면, `PreparedStatementResolver`의 경우, `PreparedStatement`에 값을 대입하는 `setParameters` 작업을 수행합니다. 여러 곳에서 사용되는 공통 로직이지만, 각각의  구현체가 필요한 것이 아닌 정해진 작업을 반복적으로 수행하기 때문에 인터페이스보다는 유틸 클래스 형태로 만드는 것이 적합하다고 생각했습니다.
추후에 다양한 구현체가 필요해졌을 때, 인터페이스를 분리하는 것을 고려해볼 수 있을 것 같아요:)

2024-10-09 07:14 UTC, linirini commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> -            setParameters(ps, args);
JdbcTemplate은 개발자가 JDBC 기술을 쉽게 사용할 수 있도록 도와주는 클래스입니다.
이 클래스를 사용하여 개발자는 쿼리문을 작성하고, 인자를 전달하고, 응답 결과를 매핑하는 작업에만 집중할 수 있어요!
즉, JdbcTemplate의 책임은 JDBC를 직접 사용할 때 반복적으로 발생하는 작업을 대신 처리해주고, 데이터베이스 작업에 대한 표준화된 접근 방식을 제공하는 것이라고 생각합니다.

그리고 이 안에서도 PreparedStatement에 인자를 설정해주는 반복적인 작업이 발생합니다. 따라서, PreparedStatement 설정과 관련된 책임을 분리하여 JdbcTemplate 클래스는 데이터베이스 작업의 일반적인 흐름과 관련된 책임에 집중할 수 있게 하였습니다.

2024-10-09 07:18 UTC, linirini commented on jdbc/src/main/java/com/interface21/jdbc/core/PreparedStatementResolver.java
> +    public static void setParameters(PreparedStatement pstmt, Object... args) {
null이 아닐 경우만 반복문을 수행하도록 수정했습니다!

2024-10-09 08:49 UTC, linirini commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +    private <T> T execute(String sql, PreparedStatementExecutor<T> pstmtExecutor, Object... args) {
- Conncetion, PreparedStatment 생성 및 자원 회수
- 예외 처리
- PreparedStatement 인자 설정
위의 작업들이 반복되는데 좋은 리팩터링 방향을 찾지 못하고 있었어요 ㅜㅜ
그러다가 [`Template Callback Pattern`](https://inpa.tistory.com/entry/GOF-%F0%9F%92%A0-Template-Callback-%EB%B3%80%ED%98%95-%ED%8C%A8%ED%84%B4-%EC%95%8C%EC%95%84%EB%B3%B4%EA%B8%B0#%EC%9E%90%EB%B0%94%EC%9D%98_%EC%BD%9C%EB%B0%B1)을 알게 되어서 적용해봤습니다!
덕분에 반복되는 작업에 대한 메서드는 분리하되, 그 안에서 다양한 PreparedStatement의 전략 로직을 `PreparedStatementExecutor` 함수형 인터페이스 메서드의 매개변수값으로 넘기는 방식으로  클래스를 생성하지 않고 리팩터링 할 수 있었어요!

2024-10-10 01:43 UTC, shin-jisong commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +    private <T> T execute(String sql, PreparedStatementExecutor<T> pstmtExecutor, Object... args) {
이런 방식도 있었네요! 저도 참고해 봐야겠습니다 👍

2024-10-10 01:46 UTC, shin-jisong approved these changes
안녕하세요 리니!
3단계에서 좀 더 어려운 요구사항이 들어올 것 같아 2단계는 이만 머지하려고 합니다~
혹시 더 주고받고 싶었던 부분이 있었다면 다음 PR 본문에 써 주시면 좋을 것 같아요 👍
다음 단계도 파이팅입니다 👊

2024-10-10 01:59 UTC, merged