[2단계 - JDBC 라이브러리 구현하기] 카고(정민호) 미션 제출합니다.
woowacourse/java-jdbc pull request #712
Opened 2024-10-09 03:25 UTC by devhoya97

안녕하세요 폴라! 2단계로 돌아왔습니다.

의도하지 않았는데, 1단계에서 기존 JdbcTemplate의 구조를 많이 따라하다보니, 2단계 리팩터링에서 요구하는 요구사항들이 거의 다 만족되어 있더라구요. 그래서 기존에 SQLException을 잡아서 RuntimeException으로 날리던 부분을 DataAccessException이라는 커스텀 예외를 날리는 정도로 변경한 것 외에는 코드 상으로 변경된 점이 없습니다! (그래도 LMS 내용을 꼼꼼히 보고 학습해보았습니다..!)

추가로 DM에서 이야기 나눴던 것처럼, 학습테스트에 주석으로 학습한 내용을 추가했습니다! phantomReading 테스트에서 schema.sql 쪽에 에러가 나던 부분은 schema.sql의 주석에 적힌 설명대로, 아래와 같이 멀티쿼리 옵션을 수행하도록 변경해서 해결했습니다! 
```java
config.setJdbcUrl(container.getJdbcUrl() + "?allowMultiQueries=true");
```

참고로 schema.sql에 적혀있던 주석 내용은 다음과 같습니다.
```
-- mysql 8.0.30부터는 statement.execute()으로 여러 쿼리를 한 번에 실행할 수 없다.
-- 멀티 쿼리 옵션을 url로 전달하도록 수정하는 방법을 찾아서 적용하자.
```

리뷰할 내용이 거의 없을 것 같긴 하지만, 잘 부탁드립니다!!

2024-10-09 16:47 UTC, jinchiim commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +            throw new DataAccessException(e);
중요한 것은 아니지만 라이브러리이니 친절한 메시지를 고민해봐도 괜찮겠네요 😄

2024-10-09 16:48 UTC, jinchiim commented on study/src/test/java/connectionpool/stage2/Stage2Test.java
> +     * 하지만 DataSource를 여러 개 사용하거나 세부 설정을 하려면 빈을 직접 생성하는 방법을 사용한다. -> RDS 때문에 DataSource를 두 개 설정할 때 Config를 빈으로 등록한 이유가 이거구나
👍🏻

2024-10-09 17:04 UTC, jinchiim requested changes
안녕하세요 카고!
2단계에서 학습테스트에 주석을 너무 잘 달아놓으셔서 보기도 좋고 저도 학습된 것 같아요 감사합니다 😄

딱 하나만 더 해보면 좋을 것 같아 RC 드립니다! 이번 단계도 화이팅해봐요! 🫡

2024-10-09 17:04 UTC, jinchiim commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
요구사항에 자세히 보면  `getDatasource` 라는 메서드가 있습니다!
![image](https://github.com/user-attachments/assets/fe252b7e-7a27-424d-8d5e-62e40918f29b)

한번 만들어보고 왜 `Datasource` 를 꺼내오는 행위가 있는지 고민해보면 좋을 지점 같아 한번만 `RC` 드려요! 😋

2024-10-10 04:58 UTC, devhoya97 commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +            throw new DataAccessException(e);
"쿼리를 실행하던 도중 예외가 발생했습니다. sql = %s" 와 같이 친절한 메시지를 던지도록 변경했습니다!

2024-10-11 05:02 UTC, devhoya97 commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
리뷰요청을 보내면서 핑퐁하기엔 시간이 오래걸릴 것 같아서 DM으로 질문드렸는데요! 기록용으로 남겨두겠습니다 :)

<img width="1071" alt="image" src="https://github.com/user-attachments/assets/7785b2d1-41ca-4233-a485-277492c238b7">

2024-10-11 06:25 UTC, jinchiim approved these changes
안녕하세요 우테코 대표 오빠 카고님

쳐다볼 수 있는 시간이 3초이기에 `Approve`가 꽤나 힘들었지만
열심히 리뷰를 반영하고 함께 디엠한 정을 생각해 2초만 보도록 노력하여 `Approve`를 드립니다.

3단계에서 뵙시다! 🫡

2024-10-11 06:26 UTC, merged