[STEP2]
woowacourse/java-jdbc pull request #713
Opened 2024-10-09 03:45 UTC by PgmJun

안녕하세요 리건~
제가 STEP1때 고민했던 부분이 STEP2와 연관이 되어있어서 크게 많은 처리가 발생하진 않았네요

## 변경사항
### 1. PreparedStatementSetter 추가
변경 사항은 PreparedStatementSetter가 인터페이스로 분리되어서 JdbcTemplate에서 PreparedStatement에서 Args를 Pstmt에 세팅하는 책임을 분리했다는 점이구요

PreparedStatementSetter는 제가 구현한 ArgumentPreparedStatementSetter 를 사용하긴 했지만, 확장 및 사용의 편의를 위해서 FunctionalInterface로도 선언해두었습니다.

### 2. 쿼리 로그 Info -> Debug 레벨로 변경
쿼리는 서버 운영의 정보보다는 디버그를 위한 정보에 가깝다고 생각합니다.
실제로 개발을 하다보면 쿼리는 Debug레벨로 찍히기도 하구요
때문에 info 레벨로 찍어주던 쿼리를 Debug 레벨로 변경하였습니다

### 3. ResultSet Close 로직 제거
리건이 저번에 리뷰 남겨주신 부분에 대해서 이걸 좀 더 간소화할 수 없을까 고민하다가 알게 되었는데요
Statement 객체는 close 시에 ResultSet도 함께 close해주기 때문에 ResultSet Close 로직을 제거해도 괜찮다는 것을 알게 되었습니다.
모르셨다면 리건도 참고하세요:)

<img width="569" alt="스크린샷 2024-10-09 12 44 54" src="https://github.com/user-attachments/assets/2fa92ab7-4bec-44a6-8555-9e587aa57b8d">

2024-10-09 08:17 UTC, hangillee requested changes
안녕하세요, 이든~
저도 이번 미션에서 해야할 일을 1단계에서 먼저 해버려서 참 난감했습니다..

몇가지 코멘트 남겨드렸는데 확인 부탁드립니다!

2024-10-09 08:17 UTC, hangillee commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
>               PreparedStatement pstmt = conn.prepareStatement(sql)
꼭 반영해주실 필요는 없지만 한가지 제안드리고 싶은 것이 있습니다!
[Java 9부터 `try-with-resources` 밖에서 자원을 할당](https://www.baeldung.com/java-try-with-resources#java-9---effectively-finalvariables)할 수 있다고 합니다.

큰 차이는 없지만 `try`문 밖에서 해당 자원을 활용할 수 있는 유연성 확보와
코드가 매우 깔끔해지는 효과가 있어서 고려해보시는 것도 추천드립니다!

2024-10-09 08:17 UTC, hangillee commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +            pss.setValues(pstmt);
이 코드 3줄이 지금 `update()`, `query()`, `queryForObject()` 메소드에서 중복되는 것 같은데
`private` 메소드로 분리하는 건 어떨까요?

2024-10-09 08:17 UTC, hangillee commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
>      }
말씀해주신 것처럼 함수형 인터페이스로 선언해두셨으니
람다와 인터페이스 익명 구현 객체를 활용해보시는 건 어떨까요?

LMS에도 이런 멘트가 있는 만큼 추천드려요~
![image](https://github.com/user-attachments/assets/f3a0076a-9c2b-4c95-a0fe-f3305351dabf)

2024-10-09 13:11 UTC, PgmJun commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
>      }
저도 그걸 보고 구현해볼까 싶었지만, 클래스로 분리하는게 코드가 더 이쁜 것 같아서 클래스로 구현하였습니닷..ㅋㅋ
그래도 리뷰어인 리건이 해보라고 하시니 한 번 적용해볼게요^^

2024-10-09 13:34 UTC, PgmJun commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
>               PreparedStatement pstmt = conn.prepareStatement(sql)
적용했더니 코드가 깔끔해보이긴 합니다~!
좋은 정보 감사합니다:)

2024-10-10 18:49 UTC, hangillee approved these changes
고생하셨습니다, 이든!
이만 머지해도 좋을 것 같네요!

2024-10-10 18:50 UTC, merged