[3단계 - JDBC 라이브러리 구현하기] 감자 미션 제출합니다.
woowacourse/java-jdbc pull request #718
Opened 2024-10-09 08:08 UTC by khabh

안녕하세요 트레 💩🐾 감자입니다
학습 테스트가 어려워서 3단계 제출 못 할 뻔했네요 🥲
3단계 리뷰도 잘 부탁드립니다 🙇‍♀️

2024-10-10 06:06 UTC, takoyakimchi requested changes
안녕하세요 감자! 3단계 구현도 고생 많으셨어요.
3단계 요구사항은 다 만족한 것 같고 질문만 몇 개 남겨봤어요!

2024-10-10 06:06 UTC, takoyakimchi commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +        }
트랜잭션 사용 여부와 관계 없이 `transactionManager`에서 커넥션을 가져오고 있네요!!

2024-10-11 05:27 UTC, khabh reviewed
안녕하세요 트레 🐶 해줘

2024-10-11 05:27 UTC, khabh commented on jdbc/src/main/java/com/interface21/jdbc/transaction/TransactionManager.java
> +
> `static` 이어야 하는 이유가 궁금해요!

CONNECTIONS를 static으로 지정한 이유는 여러 인스턴스가 동일한 DataSource에 대해 트랜잭션을 공유할 수 있도록 하기 위함입니다. jdbcTemplate에서는 트랜잭션 처리를 위해 DataSource를 통해 TransactionManager 인스턴스를 새롭게 생성하는데, 만약 CONNECTIONS가 인스턴스 필드였다면 동일한 DataSource에 대해 서로 다른 Connection을 참조하게 될 수 있습니다.

> 객체의 생명주기를 봤을 때 DataSource랑 `Connection`을 들고 있을 수도 있었을 것 같아요.
> Map을 쓰기로 한 의사결정 과정이 궁금해요!

애플리케이션에서 두 개 이상의 DataSource를 사용하는 경우에도 커넥션을 잘 관리해 주기 위해 Map을 사용했습니다.

2024-10-11 11:34 UTC, takoyakimchi commented on study/src/test/java/transaction/stage1/Stage1Test.java
> +        config.setJdbcUrl(container.getJdbcUrl() + "?allowMultiQueries=true");
:짱수아하:

2024-10-11 11:36 UTC, takoyakimchi commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +        }
눈이 침침해서 미안합니다 🙄

2024-10-12 07:10 UTC, takoyakimchi approved these changes
감자 고생했어요! 다음 단계에서 생각해보면 좋을만한 코멘트 남겨봤어요.

2024-10-12 07:10 UTC, takoyakimchi commented on app/src/main/java/com/techcourse/config/JdbcConfig.java
> +}
Config 클래스라고 하면 라이브러리를 사용하는 개발자마다 서로 다른 설정을 해줄 수 있는 것처럼 느껴지는데
이 파일은 모든 라이브러리 사용자가 동일한 방식으로 구현해야 할 것 같아요.
좀 더 편하게 사용하도록 할 수 있는 방법은 없을까요?

2024-10-12 07:10 UTC, takoyakimchi commented on app/src/main/java/com/techcourse/service/UserServiceImpl.java
> +
`Impl`이라는 이름이 조금 모호하게 들리는 것 같아요.
`UserService`를 어떤 방식으로 `구현`했나요?

2024-10-12 07:11 UTC, merged