[3단계 - JDBC 라이브러리 구현하기] 구름(김민수) 미션 제출합니다.
woowacourse/java-jdbc pull request #719
Opened 2024-10-09 08:10 UTC by alstn113

안녕하세요 무빈! 구름 ⛅️입니다.

### Step3 구현

step3을 진행하면서 모든 메서드 파라미터에 Connection을 추가해야 했습니다.
그래서 TransactionManager를 사용할까하다가 step4 내용이라 만들지 않았습니다. 참고 부탁드립니다.

step3의 주요 내용은 커넥션을 재사용하는 트랜잭션을 만들고 롤백하는 것입니다.

TransactionTemplate을 사용해서 트랜잭션 부분을 구현해봤습니다.
코드는 깔끔해지는데 execute와 dao 부분에 같은 connection이 들어가야하는게 문제가 됩니다. 
이 부분은 transaction manager를 구현하면서 개선하겠습니다.
```java
public <T> T execute(Connection con, Supplier<T> supplier) {
    try {
        con.setAutoCommit(false);
        T result = supplier.get();
        con.commit();

        return result;
    } catch (Exception e) {
        rollback(con);
        throw new DataAccessException(e);
    } finally {
        release(con);
    }
}
```

### 학습테스트

connectionPool과 transaction 관련 학습 테스트를 진행했습니다.

미리 리뷰 감사합니다. 좋은 하루 보내세요~ ⛅️ 👍

2024-10-10 16:19 UTC, hjk0761 requested changes
구름 안녕하세요!
열심히 3단계 공부하고 돌아왔습니다.

역시 미션도, 학습 테스트도 너무 잘 해주신 것 같아요!
이번에도 역시나 질문이 리뷰의 주를 이루는 것 같군요.

3단계도 고생 많았어요!!
질문이 해결되고 나면 approve 드리겠습니다!

2024-10-10 16:19 UTC, hjk0761 commented on app/src/main/java/com/techcourse/dao/UserDao.java
> +    public User findById(Connection con, Long id) {
한 트랙잭션에서 관리되는 걸 놓치지 쉬울 것 같았는데, 꼼꼼하시네요!!

2024-10-10 16:19 UTC, hjk0761 commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +    private <T> T getSingleResult(List<T> results) {
분리 잘 해주신 것 같습니다!

2024-10-10 16:19 UTC, hjk0761 commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +    private static <T> List<T> mapResultSet(
혹시 static 인 이유가 있을까요?

2024-10-10 16:19 UTC, hjk0761 commented on jdbc/src/main/java/com/interface21/jdbc/core/TransactionTemplate.java
> +                con.close();
setAutoCommit 설정을 다시 해준 건 좋은 것 같아요!
궁금한 점은, 바로 close 하는 커넥션인데 이런 처리가 어느 상황에서 유효한지 알고 싶습니다!

2024-10-10 16:19 UTC, hjk0761 commented on jdbc/src/main/java/com/interface21/jdbc/core/TransactionTemplate.java
> +    public <T> T execute(Connection con, Supplier<T> supplier) {
혹시 supplier 를 사용한 메서드를 구현하신 이유가 있는지 궁금합니다!

2024-10-10 16:19 UTC, hjk0761 commented on study/src/test/java/transaction/stage1/Stage1Test.java
> + * Serializable     | -           | -                    | -
학습 테스트도 잘 수행해 주셨네요!!
써주신 것 처럼 MySQL 에서 InnoDB 스토리지 엔진을 사용하면 Repeatable Read 수준에서도 Phantom Read 가 잘 발생하지 않는다고 합니다! 👍

2024-10-10 16:19 UTC, hjk0761 commented on app/src/main/java/com/techcourse/service/UserService.java
> +    private final TransactionTemplate txTemplate;
TransactionTemplate를 필드로 가지게 된 이유가 궁금합니다!
dataSource 나 connection 등에 의존적이지 않아 static 메서드와 같은 선택지도 있을 것 같아요.
어떤 이유에서 필드로 가지게 되었나요?

2024-10-11 01:28 UTC, alstn113 commented on jdbc/src/main/java/com/interface21/jdbc/core/TransactionTemplate.java
> +                con.close();
트랜잭션이 없는 부분은 Connection을 전달하지 않고 connection을 얻은 후 try with resources를 통해서 close를 해줍니다.
다음의 예시가 그에 해당합니다.
```java
/**
 * 트랜잭션 처리 없어 connection을 가져오고, 닫는다.
 */
private <T> T execute(String sql, PreparedStatementCallback<T> callback) {
    try (Connection con = dataSource.getConnection();
         PreparedStatement pstmt = con.prepareStatement(sql)) {
        return callback.doInStatement(pstmt);
    } catch (SQLException e) {
        throw new DataAccessException("execute error", e);
    }
}
```

하지만 트랜잭션을 사용하는 경우 같은 connection을 사용해야하기 때문에 try with resources로 close해주면 안됩니다.
그래서 다음과 같이 connection을 받아서 사용합니다.
```java
private <T> T execute(Connection con, String sql, PreparedStatementCallback<T> callback) {
    try (PreparedStatement pstmt = con.prepareStatement(sql)) {
        return callback.doInStatement(pstmt);
    } catch (SQLException e) {
        throw new DataAccessException("execute error", e);
    }
}
```

결론적으로 TransactionTemplate에서 connection을 받고, setAutoCommit=false를 지정한 후 같은 connection으로 다양한 쿼리 처리를 한 후 commit이나 rollback을 합니다. 마지막에 다시 setAutoCommit=true로 한 후 connection을 close해줍니다.

2024-10-11 01:34 UTC, alstn113 commented on jdbc/src/main/java/com/interface21/jdbc/core/TransactionTemplate.java
> +    public <T> T execute(Connection con, Supplier<T> supplier) {
현재 changePassword 메서드는 void를 응답하지만 리턴 타입이 다른 경우도 있을 것 같아서 만들었습니다.

2024-10-11 01:42 UTC, alstn113 commented on app/src/main/java/com/techcourse/service/UserService.java
> +    private final TransactionTemplate txTemplate;
원래 TransacationManager의 필드에 datasource를 받고 있었어요. connection을 TransactionTemplate에서 시작할려했어요. 그러나 각 query에 connection을 넣어줘야해서 문제가 있었고, 지웠어요. 그 흔적입니다.

또한 나중에 TransactionManager를 주입할 것 같아서 미리 그렇게 했던 것 같아요.

2024-10-12 11:11 UTC, hjk0761 commented on app/src/main/java/com/techcourse/service/UserService.java
> +    private final TransactionTemplate txTemplate;
4단계 구현방향을 의도하시고 구현한 거라면 좋은 것 같습니다!!

2024-10-12 11:12 UTC, hjk0761 approved these changes
구름, 리뷰가 많이 늦어져서 정말 죄송합니다..

답변 잘 확인했습니다!
4단계 바로 진행하시면 될 것 같아요!!

마지막 단계도 화이팅입니다!!

2024-10-12 11:12 UTC, merged