[2단계 - JDBC 라이브러리 구현하기] 낙낙(이낙헌) 미션 제출합니다.
woowacourse/java-jdbc pull request #739
Opened 2024-10-09 18:15 UTC by nak-honest

안녕하세요 리브!!

기존 1 단계에서 이미 구현된 부분이 많아, 변경 사항이 많지 않습니다!!

편하게 리뷰 주시면 감사하겠습니다 :)

2024-10-10 05:46 UTC, Minjoo522 requested changes
안녕하세요 낙낙!
빠르게 구현해주셨네요! 👍

<img width="787" alt="image" src="https://github.com/user-attachments/assets/4c8d24ad-4af4-41a9-967b-62e98e41d641">

LMS에서 보시면 `PreparedStatementSetter`가 있는데요~
이 인터페이스를 사용하면 PreparedStatement 값을 세팅하는 아래 로직을 분리할 수 있을 것 같아요!
```java
        for (int parameterIndex = 0; parameterIndex < args.length; ++parameterIndex) {
            preparedStatement.setObject(parameterIndex + 1, args[parameterIndex]);
        }
```

그리고 학습테스트에서 공부한 내용도 주석에 같이 적어주면 더 많은 이야기를 나눠볼 수 있을 것 같아요!
간단한 리뷰 몇가지 남겨 두었으니 확인해보시고 리뷰 재요청주세요! 👍

2024-10-10 05:46 UTC, Minjoo522 commented on study/src/test/java/transaction/stage1/Stage1Test.java
> +        config.setJdbcUrl(container.getJdbcUrl() + "?allowMultiQueries=true");
```java
final var mysql = new MySQLContainer<>(DockerImageName.parse("mysql:8.0.30"))
        .withUrlParam("allowMultiQueries", "true")
        .withLogConsumer(new Slf4jLogConsumer(log));
```
오 여기에 + 연산자를 통해 추가해줄수도 있겠군요!
저는 MySQLContainer의 메서드를 통해 설정해 주었습니다. 👍

2024-10-10 05:46 UTC, Minjoo522 commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +        return executeStatement(sql, preparedStatement -> getResults(preparedStatement, rowMapper), args);
우와 람다를 정말 극한으로 사용해주셨네요!
하지만 저는 이 코드를 이해하기가 좀 어려웠던 것 같아요 ㅠㅠ
조금 더 가독성이 좋게 바꿔볼 수는 없을까요?

2024-10-10 05:46 UTC, Minjoo522 commented on study/src/test/java/transaction/stage2/Stage2Test.java
> +     * 생성된 트랜잭션이 몇 개인가? 왜 그런 결과가 나왔을까?
이 질문들에 대한 낙낙의 답도 한 번 정리해보면 좋을 것 같아요!

2024-10-11 10:19 UTC, nak-honest reviewed
안녕하세요 리브!!
리뷰 반영 완료하였습니다!

확인해 주시면 감사하겠습니다 :_

2024-10-11 11:36 UTC, Minjoo522 approved these changes
안녕하세요 낙낙! 리브입니다.
빠르게 리뷰 반영 해주셨네요! 👍
진~짜 간단하게 남겼는데요 다음 단계 진행하면서 반영해주시면 될 것 같습니다!
다음 단계도 화이팅이에요!

2024-10-11 11:36 UTC, Minjoo522 commented on jdbc/src/main/java/com/interface21/jdbc/core/PreparedStatementSetter.java
> +public interface PreparedStatementSetter {
오 `PreparedStatementSetter`를 만들어주셨네요!
`StatementExecutor`처럼 `@FunctionalInterface` 어노테이션을 붙여주는 건 어떨까요?

2024-10-11 11:36 UTC, Minjoo522 commented on study/src/test/java/transaction/stage1/Stage1Test.java
> +            // 답변 : 비즈니스 상황에 따라 다르지만, 일반적으로는 적절하지 않다.
👍

2024-10-11 11:36 UTC, Minjoo522 commented on study/src/test/java/transaction/stage2/Stage2Test.java
> +     * NOT_SUPPORTED 가 붙은 트랜잭션의 이름이 나오는 것은, AOP로 인해 프록시가 생성은 되기 때문이다. 다만 active가 flase 로 나오기 때문에 실제 트랜잭션이 동작하는 것은 아니다.
👍

2024-10-11 11:36 UTC, merged