[2단계 - JDBC 라이브러리 구현하기] 마크(김승현) 미션 제출합니다.
woowacourse/java-jdbc pull request #745
Opened 2024-10-10 05:30 UTC by seunghye218

안녕하세요 산초~ DB Connection Pool과 Transaction 학습 테스트를 포함하여 2단계 미션 제출합니다~

2024-10-11 17:25 UTC, nayonsoso requested changes
안녕하세요 마크💎⛏️
요구사항이 [익명 클래스, 함수형 인터페이스, 제네릭, 가변 인자, 람다, try-with-resources, 
checked vs unchecked exception]를 사용해서 클린코드 작성하기였는데, 여기 나열된 항목들 모두를 사용해주셔서 아주 클린했던 것 같습니다✨ 구현은 1단계에서 대부분 해주셔서 이번엔 학습 테스트에 대해서도 코멘트를 남겨봤습니다. 답변 다시고 다시 요청주시면, 바로 머지하겠습니다!

2024-10-11 17:25 UTC, nayonsoso commented on study/src/test/java/transaction/stage2/Stage2Test.java
> +                        "transaction.stage2.FirstUserService.saveFirstTransactionWithNotSupported"
이 부분도 마찬가지로, Not supported 는 트랜잭션 없이 작동합니다. 그렇다면 `saveFirstTransactionWithNotSupported()` 함수에 `@Transactional(propagation = Propagation.REQUIRED)` 어노테이션이 있을 때는 트랜잭션이 1개 / 어노테이션이 없을 때는 트랜잭션이 0개여야하는데, 테스트 코드에서는 이렇지 않은 것 같아요. 마크는 혹시 그 이유를 아시나요?

2024-10-11 17:25 UTC, nayonsoso commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +        }, params);
[선택 반영]

![image](https://github.com/user-attachments/assets/40d2514e-9336-4597-a672-489ab410ae21)

LMS 에 올라와있는 이 구조를 참고해서 더 개선할 수 있을 것 같아요😊

2024-10-11 17:25 UTC, nayonsoso commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +    public <T> T queryForObject(String sql, RowMapper<T> rowMapper, @Nullable Object... params) {
가변인자에 해당하는 값이 아무것도 오지 않으면 null 이 아니라 길이가 0인 배열이 오는걸로 알고 있어요..! 🫨

2024-10-11 17:25 UTC, nayonsoso commented on jdbc/src/main/java/com/interface21/jdbc/core/PreparedStatementCallback.java
> +    T doInPreparedStatement(PreparedStatement ps) throws SQLException, DataAccessException;
throws 에서 DataAccessException 는 없애도 될 것 같아요! 
코드를 보니 콜백 함수 내부에서는 DataAccessException (Checked)가 발생할 수 있고, 이를 잡아서 DataAccessException (Unchecked) 로 변환해주고 있더라고요. 

1. DataAccessException가 발생하는 것도 아니고,
2. DataAccessException를 throw 해서 다른 곳에서 처리하게 하는 것도 아니고
3. DataAccessException는 UncheckedException 이니 그럴 필요성도 없을 것 같습니다!

2024-10-12 02:06 UTC, seunghye218 commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +    public <T> T queryForObject(String sql, RowMapper<T> rowMapper, @Nullable Object... params) {
```
...()     // Object[] {}
...(null) // null
```
명시적으로 null을 넘기게 되면 null로 넘어오기 때문에 가능하다고 볼 수 있을 것 같아요!

2024-10-13 11:13 UTC, nayonsoso approved these changes
안녕하세요 마크😊
이번 단계 요구사항은 모두 충족한듯하여 머지합니다. 다음 단계도 파이팅입니다🍀

2024-10-13 11:13 UTC, merged