[2단계 - JDBC 라이브러리 구현하기] 조이썬(이영수) 미션 제출합니다.
woowacourse/java-jdbc pull request #760
Opened 2024-10-10 15:56 UTC by youngsu5582

안녕하세요 리비!
생각보다 오래 걸렸네요.
빠르게 리뷰 사이클을 돌린게 좋겠다고 생각해서 간단하게 변환하고 올렸습니다!
( 얘기하면서, 코드를 고쳐보고 싶기도 하구요 🙂🙂 )

큰 변화점으로 StatementSetter 는 아직 뒀습니다.

`생각해보기`에서 원하는 지향성인거 같기도 해서 유지했습니다.

최대한 불필요한 중복을 제거하려 노력했습니다.
이때 필연적으로 3+a 의 매개변수가 발생하게 됩니다.
```java
private <T, R> R executeQueryTemplate
(final String sql, final RowMapper<T> rowMapper, final ResultSetConverter<T, R> converter, final Object... params) {
```

하지만, 이때 중간에 메소드만 변경이 가능해 중복을 최소화가 됩니다.
이런 경우 리비의 생각은 어떤지 궁금하네요 🙂

---

추가로, 급하게 구현한다고 학습을 많이 안해서 지식적인 질문도 좋아요!

2024-10-11 07:22 UTC, Libienz requested changes
안녕하세요 조이썬~

매우매우 깔끔한 코드가 되었네요 💯 
코멘트 남겨보았습니다. 이번에도 마찬가지로 모두 반영을 원하는 코멘트는 아니니 조이썬의 의견을 들려주세요! 

> 최대한 불필요한 중복을 제거하려 노력했습니다.
이때 필연적으로 3+a 의 매개변수가 발생하게 됩니다.

메서드 체이닝을 적극적으로 활용하여 중복을 잘 제거해주셨다고 생각해요~ 다만 파라미터 관련해서는 사소한 코멘트 남겨보았는데 확인해주세요! 

2단계 화이팅입니다 🔥🔥

2024-10-11 07:23 UTC, youngsu5582 commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +            throw new QueryExecutionException("쿼리 실행중 예외가 발생했습니다", exception);
어라 놓쳤네요 죄송해용 😿

2024-10-12 13:36 UTC, youngsu5582 commented on study/src/test/java/transaction/stage2/Stage2Test.java
> +                .hasSize(2)
안그래도, 두개의 차이를 생각하고 있었는데 
부가성일 때는 `REQUIRED_NEW` 도 좋겠네요! 🙂

2024-10-12 13:55 UTC, youngsu5582 commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
>          try (final Connection connection = dataSource.getConnection();
코드적으로 converter 는 
rowMapper,resultSet 을 받아서
resultSet 을 rowMapper 가 의도한 값으로 변환되게 해주는 대리자의 느낌입니다.

- rowMapper 는 온전히 ResultSet 을 받아서 변환 하는 용도
- converter 는 rowMapper 와 resulset 를 받아서 변환을 수행하는 용도

이렇게 한 이유가 메소드를 교체하기 위해선 어쩔수가 없더라구요. 🥲
( 특히, `List<T>` , `Stream<T>` 와 같이 그냥 T 가 아님을 구분하기 위해서 `R` 이라는 제네릭도 필요했구요 )


그래서, 빼긴 어려울 거 같습니당 😭😭
리비의 좋은 의견이 있다면 들려주셔도 좋습니다!

2024-10-12 14:02 UTC, youngsu5582 commented on app/src/main/java/com/techcourse/dao/UserDao.java
> +    );
왜 쓰는지는 알겠더라구요 ☺️
( 각 DAO 가 명확하게 자신의 도메인을 변환하는 로직을 가질 수 있다 )

2024-10-13 06:49 UTC, youngsu5582 commented on study/src/test/java/transaction/stage2/Stage2Test.java
> +
좋은 질문 이네요!
우선
- 물리 트랜잭션 : 실제 DB 에서 일어나는 트랜잭션 ( DB 변경을 커밋, 롤백 할때 사용 )
- 논리 트랜잭션 : 애플리케이션 코드 레벨에서 관리되는 트랜잭션 ( 하나의 물리 트랜잭션 내 여러 개 존재 가능 )

트랜잭션을 부착하지 않은 메소드 가 제일 처음 앞에 위치하면 `@transactional` 을 붙이지만 않으면 될 거 같으나
중간에 있으면 기존의 트랜잭션 전파 레벨에 따라 트랜잭션을 따르기 때문에 
명시적으로 붙여야 트랜잭션을 사용하지 않고 사용 가능할 거 같아요!

왜 써야 하는지는 감이 잘 안오네요,,  🙂

결론으론 물리 - 논리 적으로 둘다 분리가 될 거 같은데 리비의 의견이 듣고 싶네요!
( 대신, 기존 물리 트랜잭션은 보류가 될 거 같아요 )

2024-10-13 06:55 UTC, youngsu5582 commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +        try (resultSet) {
해당 부분은 꽤나 어렵네요 🥲🥲
어렵다고 생각한 이유가 막상 이 메소드 들을 외부로 빼고
`List` 에 넣거나 변수로 가지면 무언가 맞지가 않다는 생각이 든다일까요..?

저도 이게 `JdbcTeamplte 의 역할인가?` 라고 생각하면 아닌거 같은데
`이 구현체 들을 JdbcTemplate 가 가지는 게 맞는가?` 라고 생각이 들어서 어렵네요 😢

( 추가로 기존의 JdbcTemplate 코드 역시 1500줄이 넘는데 이런 맥락에서 길게 된걸수도 있겠다 생각이 드네요 )

결론으로
`convertXXX` 가 하나 늘어날 때마다 구현체 클래스를 만들어 인스턴스 변수나 / 리스트로 넣어야 되는지가 포인트인데
이런 관점에서 jdbcTemplate 의 역할이 해당 방향으로도 타당한거 같은데 리비의 의견을 더 들려줄 수 있나요?

2024-10-13 07:40 UTC, youngsu5582 commented
리비!
에러 부분 의견 남겨주신대로 반영했습니다!
추가로,  코드 변경한 부분이 에러 밖에 없는데 그 이유에 대해 각각 코멘트를 남겼습니다.
리비와 의견을 더 듣고 반영해보도록 하겠습니다! 🫡🫡

p.s 늦어서 죄송해요.. 🥲🥲
프리코스가 다가오다 보니,,,

2024-10-14 04:39 UTC, Libienz commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
>          try (final Connection connection = dataSource.getConnection();
> rowMapper 는 온전히 ResultSet 을 받아서 변환 하는 용도
> converter 는 rowMapper 와 resulset 를 받아서 변환을 수행하는 용도

아하 이해했습니다~ 남겨두기에 합리적이네요 👍

2024-10-14 04:47 UTC, Libienz commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +        try (resultSet) {
Functional Interface를 고민해보라는 코멘트였습니다!

JdbcTemplate에서는 실제로 여러 Functional 인터페이스를 다룹니다~ 
다음과 같이 해당 인터페이스를 구현하는 클래스를 JdbcTemplate 내부 클래스로 관리하는 경우도 있더군요.

```java
// JdbcTemplate.class
    private static class RowCallbackHandlerResultSetExtractor implements ResultSetExtractor<Object> {
        private final RowCallbackHandler rch;

        public RowCallbackHandlerResultSetExtractor(RowCallbackHandler rch) {
            this.rch = rch;
        }

        @Nullable
        public Object extractData(ResultSet rs) throws SQLException {
            while(rs.next()) {
                this.rch.processRow(rs);
            }

            return null;
        }
    }

    private static class SimplePreparedStatementCreator implements PreparedStatementCreator, SqlProvider {
        private final String sql;

        public SimplePreparedStatementCreator(String sql) {
            Assert.notNull(sql, "SQL must not be null");
            this.sql = sql;
        }

        public PreparedStatement createPreparedStatement(Connection con) throws SQLException {
            return con.prepareStatement(this.sql);
        }

        public String getSql() {
            return this.sql;
        }
    }

```

Functional Interface를 이용하면 명세가 분리될 수 있습니다.
그 구현체는 익명함수가 될 수도 있겠고 위처럼 내부 클래스일수도 있겠네요~

이번 코멘트는 반영하지 않으셔도 되지만..! 궁금한게 있으시다면 추가적으로 말씀해주세요~

2024-10-14 04:48 UTC, Libienz commented on study/src/test/java/transaction/stage2/Stage2Test.java
> +
> 중간에 있으면 기존의 트랜잭션 전파 레벨에 따라 트랜잭션을 따르기 때문에
명시적으로 붙여야 트랜잭션을 사용하지 않고 사용 가능할 거 같아요!

위의 말로 잘 정리해주신 것 같네요~

저도 너무 헷갈렸는데 AOP로 구현된 스프링 Transaction 특성 상, 전파를 막기 위해 논리 트랜잭션이라는 개념이 등장할 수 밖에 없었다고 생각합니다 👍

2024-10-14 04:51 UTC, Libienz approved these changes
고생하셨습니다 조이썬..! 

바쁜 일정속에도 미션을 소홀히 하지 않으시는군요 ㅎㅎ
조이썬 덕분에 저도 잘 배우고 있답니다.

다음 미션 일정이 조금 급한데 같이 달려보시죠!
다음 요청 기다리고 있겠습니다~

2024-10-14 04:51 UTC, Libienz commented on jdbc/src/main/java/com/interface21/jdbc/exception/ConnectionFailException.java
> +        super(String.format("DB 연결중 실패 - 쿼리: [%s]. 에러: [%s]",sql,cause.getMessage()), cause);
와우..! 💯

2024-10-14 04:51 UTC, merged