[2단계 - JDBC 라이브러리 구현하기] 테니(나아연) 미션 제출합니다.
woowacourse/java-jdbc pull request #772
Opened 2024-10-11 07:33 UTC by ay-eonii

안녕하세요 감자~!

테코톡 준비하느라 2단계 리뷰요청이 많이 늦었습니다 ㅠㅡㅠ

1단계에서 남겨주신 리뷰도 반영했어요 😄
편하게 리뷰해주세요~!

2024-10-11 14:53 UTC, khabh requested changes
안녕하세요 테니 🐣 감자입니다 🥔 
2단계도 너무 잘 구현해 주셨네요~
테스트 코드에 누추한 감자 매번 끼워 주셔서 감사합니다 ㅎ.ㅎ
간단한 코멘트 몇 개 남겼으니 확인해 주시고, 다음 리뷰 요청 시에는 학습 테스트도 함께 올려 주세요 🙇‍♀️

2024-10-11 14:53 UTC, khabh commented on jdbc/src/test/java/com/interface21/jdbc/core/StatementParamSetterTest.java
> +        StatementParamSetter.setParams(prepareStatement, "potato", "hi");
ㅋㅋㅋㅋㅋ 너무 귀여워요

2024-10-11 14:53 UTC, khabh commented on jdbc/src/main/java/com/interface21/jdbc/core/ConsumerWrapper.java
> +    public static <T> Consumer<T> accept(ThrowingConsumer<T, Exception> consumer) {
오 이런 방식으로 예외 핸들링을 통일시킬 수도 있겠네요 👍

2024-10-11 14:53 UTC, khabh commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +            throw new DataAccessException(e.getMessage(), e);
👍👍

2024-10-12 01:33 UTC, ay-eonii reviewed
안녕하세요 감자~ 꼼꼼하게 리뷰해주셔서 감사합니다 ☺️

리뷰 반영했고, 학습테스트도 추가했으니 확인부탁드려요 ~ 
(3단계가 트랜잭션이라 다음 단계에서 하려고합니다!)

2024-10-12 01:33 UTC, ay-eonii commented on jdbc/src/main/java/com/interface21/jdbc/core/StatementParamSetter.java
> +        AtomicInteger index = new AtomicInteger(1);
AtomicInteger가 동시성 이슈로 많이 사용되긴 하는데, 저는 getAndIncrement 메서드때문에 사용했습니다 ㅎㅎ 

stream을 돌면서 1씩 증가시키려니 코드가 안예쁘더라구요 🥲 그래서 객체로 만들고 1씩 증가시킬까하다가 일이 커지는 거 같아 getAndIncrement 를 지원하는 AtomicIntger를 사용했습니다

2024-10-12 01:33 UTC, ay-eonii commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +        Connection connection = dataSource.getConnection();
헉 그렇네요!! 꼼꼼하게 봐주셔서 감사해요 ☺️ 

[`3dfde92`](https://github.com/woowacourse/java-jdbc/pull/772/commits/3dfde92b5b29a6a3a05151b332da36340a02809b)
[`746dbfe`](https://github.com/woowacourse/java-jdbc/pull/772/commits/746dbfe9039bc5bcbdc2da48996420912ace72d8)

위 두 커밋에서 처리했습니다!

2024-10-12 01:33 UTC, ay-eonii commented on jdbc/src/main/java/com/interface21/jdbc/core/StatementParamSetter.java
> +                .forEach(ConsumerWrapper.accept(param -> ps.setObject(index.getAndIncrement(), param)));
저도 이부분을 고민했었는데요 🥲 시간관계상 스킵했습니다

하지만 감자 코멘트 덕분에 명분을 얻고 리팩토링 했어요 👍👍👍
일단 현재 필요한 정도로만 구현했습니닷 ㅎㅎ

[`2f18a55`](https://github.com/woowacourse/java-jdbc/pull/772/commits/2f18a5574e15331b6a0da1523c085de9af9ea58f)

2024-10-12 01:50 UTC, khabh approved these changes
안녕하세요 테니 🐣 리뷰 반영 엄청 빠르게 해 주셨네요 👍👍
테니의 부지런함에 감동받아 호다닥 리뷰 남겼습니다 🥔
리팩터링이랑 학습 테스트 모두 꼼꼼히 해 주셔서 이만 머지할게요 :)

2024-10-12 01:50 UTC, khabh commented on jdbc/src/main/java/com/interface21/jdbc/core/StatementParamSetter.java
> +    );
잘 반영해 주셨네요 👍👍

2024-10-12 01:50 UTC, khabh commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +             PreparedStatement preparedStatement = creator.createPreparedStatement(connection)) {
이제 자원들이 모두 잘 관리되고 있네요 😊

2024-10-12 01:50 UTC, khabh commented on study/src/test/java/connectionpool/stage1/Stage1Test.java
> +        HikariConfig hikariConfig = new HikariConfig("src/test/resources/hikari.properties");
학습 테스트도 꼼꼼하게 해 주셨네요 :)

2024-10-12 01:50 UTC, merged