[3단계 - JDBC 라이브러리 구현하기] 알파카(최휘용) 미션 제출합니다.
woowacourse/java-jdbc pull request #778
Opened 2024-10-11 11:43 UTC by slimsha2dy

안녕하세요 클로로루실후르바!
이번 단계는 4단계에서 진행될 리팩토링 및 동기화 구현 없이 트랜잭션 로직 구현만 진행해서 그런지 추가된 점이 많지 않네요..
이번 단계도 잘 부탁드립니다~ 🙇

2024-10-11 16:23 UTC, eunjungL requested changes
안녕하세요, 알파카! 클로로머시기입니다.

3단계도 잘 진행해주셨네요! 
이번에도 크게 리뷰할 내용이 없어 사소한 리뷰 위주로 달렸습니다. 😅 
`의견`이라고 표시된 리뷰의 반영 여부는 알파카의 판단하에 결정해주시면 됩니다!

한 번 고민해보면 좋을 지점들이 몇 개 있어 RC 한 번 드립니다.
남은 JDBC 미션 기간도 파이팅입니다~

2024-10-11 16:23 UTC, eunjungL commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +            return update(conn, sql, pss);
```suggestion
        try (Connection conn = dataSource.getConnection()) {
            return update(conn, sql, pss);
```
개행이 약간 어색하게 느껴지네요! 한 줄에 써도 충분할 것 같습니다.

2024-10-11 16:23 UTC, eunjungL commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +    public int update(Connection conn, String sql, Object... args) {
의견)
지금 update 메서드의 오버로딩이 꽤 많고 서로 호출하고 있어서 코드를 파악하는데 시간이 조금 걸리네요!
호출하는 순서에 따라 메서드 순서를 맞춰주면 자연스럽게 아래로 내리며 읽을 수 있을 것 같아요.

2024-10-11 16:23 UTC, eunjungL commented on app/src/main/java/com/techcourse/service/UserService.java
> +            final var user = findById(id);
질문)
`findById`도 한 개의 트랜잭션으로 관리되는 연산으로 보이는데요, 이 친구는 현재 UserDao 내부에서 별도의 connection을 얻게 되어있는 것 같아요. 
한 개의 트랜잭션에서 별도의 connection을 가져가도 괜찮을까요? 이런 경우 롤백과 커밋은 어떻게 처리되나요?
알파카의 의견이 궁금해요!

2024-10-11 16:23 UTC, eunjungL commented on app/src/main/java/com/techcourse/service/UserService.java
> +            throw new DataAccessException(e);
의견)
서비스 단에서 발생하는 예외의 메시지는 조금 더 사용자 친화적이어도 좋을 것 같네요!

2024-10-11 16:23 UTC, eunjungL commented on app/src/main/java/com/techcourse/service/UserService.java
> +        } catch (SQLException e) {
Transaction의 rollback은 SQL 관련 예외에 대해서만 진행되네요!
만약 `new UserHistory()`를 하는 과정에서 사용자 정의 예외가 발생하면 어떻게 되나요?

2024-10-12 08:25 UTC, slimsha2dy commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +            return update(conn, sql, pss);
오우 그러네요 바로 반영하겠습니다잇!

2024-10-12 08:31 UTC, slimsha2dy commented on app/src/main/java/com/techcourse/service/UserService.java
> +            final var user = findById(id);
오.. `findByID`는 조회 로직이고 가장 처음에 실행되기 때문에 지금은 롤백과 커밋에 있어서 큰 문제가 없어 보이긴 한데요.
만약 조회 로직의 순서가 바뀌게 될 경우 커밋되지 않은 같은 트랜잭션에서 수정된 데이터를 제대로 받아오지 못해 의도대로 동작하지 못할 가능성이 있겠네요.
클로로의 말씀처럼 같은 트랜잭션에서는 한 커넥션을 사용하는 것이 당연한데 제가 놓친 부분입니다. 수정하겠습니다 감사합니다!! 🙇

2024-10-12 08:51 UTC, slimsha2dy commented on app/src/main/java/com/techcourse/service/UserService.java
> +        } catch (SQLException e) {
경고가 뜨는 예외만 처리하다 보니 생각하지 못한 부분이네요.. 👍 
당연히 사용자 정의 예외가 발생하면 이 또한 마찬가지로 롤백을 진행해야 합니다.
모든 예외를 처리하기 위해 `Exception`을 catch하도록 수정했습니다!!

2024-10-12 08:55 UTC, slimsha2dy commented on app/src/main/java/com/techcourse/service/UserService.java
> +            throw new DataAccessException(e);
동의합니다!
반영하도록 하겠습니다. 클로버 짱 👍

2024-10-12 09:34 UTC, slimsha2dy commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +    public int update(Connection conn, String sql, Object... args) {
카카루의 말씀처럼 파악이 힘든 것은 저도 느끼고 있습니다..ㅎㅎ

그런데 한 메서드에 대해 오버로딩된 여러 형태가 public으로 제공되고 **체이닝**하는 현재의 구조 상 가장 마지막에 호출되는 **핵심 로직이 포함된 메서드**를 가장 위에 두고 체이닝하는 다른 메서드들을 아래쪽에 두는 편이 라이브러리를 직접 확인할 일이 있는 사람 입장에서는 더 편할 것 같다는 생각이 드는데요.
만약 라이브러리의 내부 구현을 직접 확인하는 상황이라면 체이닝만 수행하는 메서드들을 실제로 직접 흐름을 따라가면서 확인하는 것의 중요도는 좀 낮다고 생각합니다.
그래서 여러 오버로딩 중 핵심 로직을 가장 상단에 두고 나머지(큰 로직 없이 체이닝하는 오버로딩 메서드들)는 아래에 두는 것이 실제 동작 파악에는 더 유용할 것 같습니다..
그리고 또한 오버로딩인 만큼 여러 메서드들이 전부 같은 동작을 수행해야 하고 추가적인 옵션만 달라지는 경우가 대부분이므로 더더욱 체이닝 흐름 자체는 큰 상관이 없다고 생각하긴 합니다.
이에 대해서는 어떻게 생각하시나요?

2024-10-12 12:19 UTC, eunjungL approved these changes
안녕하세요, 알파카! 클로버입니다.
제 닉네임의 별칭이 점점 많아지네요 ^_^

리뷰 반영 해주신 것과 코멘트에 의견 달아주신 것 모두 확인했습니다!
3단계 요구사항은 충분히 만족하신 것 같아 이만 merge 합니다.

마지막 4단계도 파이팅입니다! 👍

2024-10-12 12:19 UTC, eunjungL commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +    public int update(Connection conn, String sql, Object... args) {
> 만약 라이브러리의 내부 구현을 직접 확인하는 상황이라면 실제 내부 동작에 비해 체이닝만 수행하는 메서드들을 실제로 직접 흐름을 따라가면서 확인하는 것의 중요도는 좀 낮다고 생각합니다.
그래서 여러 오버로딩 중 핵심 로직을 가장 상단에 두고 나머지(큰 로직 없이 체이닝하는 오버로딩 메서드들)는 아래에 두는 것이 실제 동작 파악에는 더 유용할 것 같습니다..

이 의견이 정말 타당하게 느껴지네요! 체이닝의 흐름보다는 실제 동작을 가진 핵심 메서드가 동작 파악에 더 도움될 것 같다는 의견에 매우 동의합니다. 지금의 순서를 유지해도 충분할 것 같아요.
의견 공유 감사해요 알파카~ 👍

2024-10-12 12:19 UTC, merged