[3단계 - JDBC 라이브러리 구현하기] 이상(이건상) 미션 제출합니다.
woowacourse/java-jdbc pull request #781
Opened 2024-10-11 13:02 UTC by kunsanglee

안녕하세요 커비~ 😇
3단계 트랜잭션 진행해봤습니다.

`UserService`에서 호출하는 메서드인 `changePassword` 메서드 내부에서 `UserDao.update`, `UserHistoryDao.log` 메서드를 호출하는데,
각 메서드에서 예외가 발생할 가능성이 있기 때문에 `changePassword` 메서드에서 `Connection` 객체를 생성해서 두 메서드에 넘겨주도록 구현했습니다. 

이렇게 `update`, `log` 메서드는 같은 `Connection` 객체를 대상으로 쿼리를 수행합니다.
두 메서드 중 어느 곳이든 예외가 던져지면, 외부 메서드인 `changePassword` 메서드에서 `rollback`을 합니다.
결국 모두 성공하거나 모두 실패하는 원자성을 갖습니다.

2024-10-12 15:35 UTC, skylar1220 approved these changes
안녕하세요 이상 이번에도 역시 빠르게 구현해주셨네요!
기존 로직과 공존하는 중간 단계가 잘 구현된 것 같아요~ (+ 지난번 코멘트도 반영된 것 확인했습니다!)

2024-10-12 15:35 UTC, skylar1220 commented on app/src/main/java/com/techcourse/service/UserService.java
> +        }
connection을 try-with-resource로 처리해도 더 간단해져서 좋을 것 같아요~

2024-10-12 15:35 UTC, skylar1220 commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +    public int update(Connection connection, String sql, PreparedStatementSetter preparedStatementSetter) {
오버로딩으로 변경 최소화👍

2024-10-12 15:51 UTC, skylar1220 requested changes
어프로브 번복이라 죄송합니다..ㅎㅎ
몇 개 질문이 더 있어서 좀 더 얘기나눠보면 좋을 것 같아요😋😋

2024-10-12 15:51 UTC, skylar1220 commented on app/src/main/java/com/techcourse/service/UserService.java
> +        } catch (SQLException e) {
현재 구조에서 만약 connection이 null인채로 진행된다면 어떤 일이 일어날까요? 이에 대한 처리를 해보는 건 어떨까요!

2024-10-12 15:51 UTC, skylar1220 commented on app/src/main/java/com/techcourse/service/UserService.java
> +                connection.rollback();
로직 중에 SQLException가 아닌 다른 예외가 생긴다면 기대한 동작이 될까요..! 현재 구조에서는 SQLException만 대비해도 되지만 가능성을 생각해볼 수 있을 것 같아요~

2024-10-13 06:10 UTC, kunsanglee commented on app/src/main/java/com/techcourse/service/UserService.java
> +        } catch (SQLException e) {
현재 `Connection` 객체는 `DataSource` 객체의 `getConnection` 메서드에서 가져오는데요, 
`Connection getConnection() throws SQLException;` 메서드 시그니쳐를 보면 `SQLException`만 던지고 있습니다.
그래서 사실 try 문 안에서 connection 변수에 null이 할당되어 `NullPointerException`가 발생하지 않는다고 생각해요. getConnection 메서드 호출 중에 예외가 발생해도 그 예외는 `SQLExcpetion`일 것이고, catch 문 에서 처리가 되기 때문입니다! 🙃
저는 이렇게 생각하는데 혹시 제가 놓치고 있는 부분이 있을까요?

2024-10-13 06:17 UTC, kunsanglee commented on app/src/main/java/com/techcourse/service/UserService.java
> +                connection.rollback();
위에 답은 현재 코드에서 발생할 가능성에 대한 답이었는데, 커비가 말씀해주신 가능성을 생각한다면 지금 없는 로직이 추가되었을 때 catch 되지 않는 Exception이 발생할 가능성이 있을 것 같아요. 지금 코드에 적용한다면 SQLException, Exception 둘 중 어느 예외가 발생해도 롤백을 할 것이니, 사실상 Exception만 catch하면 되는 상황이겠네요. 만약 특정 예외는 발생해도 롤백을 하지 않는 비즈니스 로직이 추가되면 재밌을 것 같네요. 덕분에 생각을 좀 더 깊게 할 수 있었어요! 감사합니다 😊

2024-10-13 06:20 UTC, kunsanglee commented on app/src/main/java/com/techcourse/service/UserService.java
> +        }
처음에 try-with-resources 문을 사용할 때 catch 문에서 connection을 참조할 수 없어서 불가능한 줄 알았습니다. 반영할게요! 😃

2024-10-13 10:56 UTC, skylar1220 approved these changes
이상 이번엔 진짜진짜 어프로브입니다😂
반영해주신 거 확인 완료했습니다~
마지막 단계까지 달려보아요!

2024-10-13 10:56 UTC, skylar1220 commented on app/src/main/java/com/techcourse/service/UserService.java
> +        try (Connection connection = dataSource.getConnection()) {
질문)
try-with-resource안에서 connection을 선언하고 connection에 대한 롤백 처리를 명시적으로 해주지 않은 이유가 있을까요?

2024-10-13 10:56 UTC, skylar1220 commented on app/src/main/java/com/techcourse/service/UserService.java
> +        } catch (SQLException e) {
아래 답변에서 얘기해주셨다싶이 추후 어떤 로직이 추가될지에 따른 null 가능성을 염두에 둔 이야기였어요😋

2024-10-13 10:56 UTC, merged

2024-10-13 11:19 UTC, kunsanglee commented on app/src/main/java/com/techcourse/service/UserService.java
> +        try (Connection connection = dataSource.getConnection()) {
`try-with-resources` 구문은 `AutoCloseable`을 구현한 자원을 자동으로 닫아주는데요, `Connection` 객체는 이를 구현하고 있어서 자동으로 자원을 닫습니다. `connection.setAutoCommit(false)`로 트랜잭션을 시작한 후 예외가 발생하여 `Connection`이 `commit` 되지 않은 상태로 닫히면 JDBC 드라이버는 자동으로 롤백합니다. 😀