[2단계 - JDBC 구현하기] 안나(김민겸) 미션 제출합니다.
woowacourse/java-jdbc pull request #785
Opened 2024-10-11 13:34 UTC by Mingyum-Kim

안녕하세요 애쉬 ~
2단계 미션 구현하고 리뷰 요청 드립니다 😊

이번 미션에서 이전에 애쉬가 준 피드백을 반영한 주요 변화는 다음과 같아요. 

1. `try-with-resources`를 사용한 중복 코드 제거
try-catch-finally 구조로 되어있던 코드를 `try-with-resources`를 사용해 제거하였습니다. 자동으로 자원을 해제하고 말씀 주셨던 코드 가독성 부분을 해소할 수 있었습니다.

2. 예외 핸들링
이전 리뷰에서 DataAcessException에 대해서 언급해주셨어요. 예외의 목적은 그 이유를 파악하는 것이 핵심인데, SQLException을 그대로 던지거나 IllegalArgumentException과 같이 모호한 에러를 던지는 것은 빠르게 원인을 파악하기 어려울 것 같았습니다. 
실제 JdbcTemplate에서는 DataAccessException 의 하위 계층의 예외 클래스를 구현하여 예외 상황마다 다르게 예외를 던진다고 해요. 

현재는 직접 정의한 커스텀 예외인 JdbcTemplateException을 만들어 던지도록 변경했어요. Unchecked Exception을 사용하니 Checked Exception인 SQLException으로 인한 복잡한 try-catch 문을 외부에서 작성하지 않아도 되고 런타임에 유연하게 에러 원인을 파악할 수 있었습니다. 

3. JdbcTemplateTest

이전에 코멘트 남겨주셨었는데 반영하지 못하고 넘어갔었어요. 기본적인 update, query, queryForObject 메서드에 대한 테스트를 작성하였습니다.

이번 리뷰도 잘 부탁드립니다 😊

2024-10-13 06:19 UTC, ashsty requested changes
안녕하세요, 안나!
2단계 미션도 잘 진행해주셨네요 ☺️

리뷰가 너무 늦어져서 죄송해요.
간단한 코멘트 몇 가지만 남겨뒀는데 확인해주시면 감사하겠습니다. 

다음 단계 기한이 타이트한 것 같지만, 그래도 반영이 필요한 부분이 있는 것 같아 rc 드려요. 🥹
다음 요청 때는 무조건 머지할 계획이니 마감 기한이 걱정되신다면 제 리뷰 여부와 관계 없이 3/4단계 진행하고 계시면 될 것 같아요.

얼마 남지 않은 주말도 잘 보내세요~~!

2024-10-13 06:19 UTC, ashsty commented on jdbc/src/main/java/com/interface21/jdbc/core/ParameterSetter.java
> +    Parameters createParameters();
```suggestion

    Parameters createParameters();
```

개행 규칙을 맞춰주어도 좋겠네요 👍

2024-10-13 06:19 UTC, ashsty commented on jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
> +    private DataSource dataSource;
setup() 메서드에서만 사용되는 것 같은데
전역 변수로 선언된 이유가 궁금해요! ☺️

2024-10-13 06:19 UTC, ashsty commented on app/src/main/java/com/techcourse/dao/UserDao.java
> +            final var parameters = new Parameters();
[질문] Sql은 String 클래스인데
파라미터는 var을 쓰신 이유가 있을까요?

2024-10-13 06:19 UTC, ashsty commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +    private static <T> List<T> getObjects(RowMapper<T> rowMapper, PreparedStatement pstmt) throws SQLException {
[질문] static 키워드가 붙은 이유가 있을까요?

2024-10-13 06:19 UTC, ashsty commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +    private static <T> T getObject(RowMapper<T> rowMapper, PreparedStatement pstmt) throws SQLException {
getObjects 메서드와 구현이 거의 유사해보여요.
중복을 제거해보아도 좋겠네요!

2024-10-13 06:19 UTC, ashsty commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +    public <T> T queryForObject(String sql, ParameterSetter parameterSetter, RowMapper<T> rowMapper) {
query 메서드와 비슷한 부분이 많아 보여요.
여기 중복도 줄여보면 좋을 것 같아요! 🤗

조금 더 나아가자면,
반복되는 try-with-resources 구문을 메서드로 추출해볼 수도 있겠네요!

2024-10-14 04:43 UTC, Mingyum-Kim commented on jdbc/src/main/java/com/interface21/jdbc/core/ParameterSetter.java
> +    Parameters createParameters();
네 👍👍 반영하였습니다

2024-10-14 04:44 UTC, Mingyum-Kim commented on jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
> +    private DataSource dataSource;
오 DataSource는 setUp 메서드에서만 사용해도 괜찮겠네요 👍

2024-10-14 04:50 UTC, Mingyum-Kim commented on app/src/main/java/com/techcourse/dao/UserDao.java
> +            final var parameters = new Parameters();
기존 코드에서 파라미터를 var로 사용하고 있어서 통일성을 맞추려 하다 보니까 그렇게 된 것 같아요. 
String 대신 var를 사용하도록 변경하였습니다 👍

2024-10-14 04:51 UTC, Mingyum-Kim commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +    private static <T> List<T> getObjects(RowMapper<T> rowMapper, PreparedStatement pstmt) throws SQLException {
아니요 ㅎㅎ IntelliJ 단축키를 사용해서 메서드 분리하다보니 static이 붙은 것 같아요 ㅠ 불필요하므로 제거하였습니다!

2024-10-14 04:59 UTC, Mingyum-Kim commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +    private static <T> T getObject(RowMapper<T> rowMapper, PreparedStatement pstmt) throws SQLException {
네 좋아요. 전달 받은 데이터가 여러 개인 경우 리스트로 반환하고, 하나인 경우 제일 첫 번째 인덱스를 반환하도록 구현하였습니다!

2024-10-14 05:02 UTC, Mingyum-Kim commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +    public <T> T queryForObject(String sql, ParameterSetter parameterSetter, RowMapper<T> rowMapper) {
네 공통된 부분을 메서드로 추출하여 중복을 제거하였습니다 👍

2024-10-14 05:07 UTC, Mingyum-Kim commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
>      public <T> List<T> query(String sql, Parameters parameters, RowMapper<T> rowMapper) {
생각해보니 그렇네요 .. !
`select * from user where id = 1` 의 결과가 여러 개의 데이터를 반환해야한다면 파라미터 세팅을 해줄 필요가 있겠어요. Setter를 받아서 파라미터를 세팅해주도록 변경하였습니다 👍

2024-10-14 05:14 UTC, Mingyum-Kim commented on app/src/main/java/com/techcourse/dao/UserDao.java
> +        jdbcTemplate.update(sql, () -> {
사실 가변인자를 사용하는 것보다 좀 귀찮더라도 Paramters를 사용해 직접 정의하는 것이 좋을 것이라 생각하였습니다 😅
가변인자는 파라미터의 순서를 명확히 할 수 없고 SQL 파라미터를 잘못 넣어주어 문제가 생기는 경우 원인을 파악하고 수정하기 어려울 것이라 판단했어요. Parameters를 사용하는 경우 파라미터 인덱스를 명확히 설정할 수 있어요. 필요하다면 Paramters 내부에서 Null Safe 등 동적으로 파라미터 입력값의 유효성을 검사할 수 있다는 것도 장점이라고 생각해요.
이러한 이유로 가변인자보다 Parameters를 사용할 것을 선택하였는데 애쉬는 혹시 어떻게 생각하실까요?

2024-10-14 05:28 UTC, ashsty commented on app/src/main/java/com/techcourse/dao/UserDao.java
> +        jdbcTemplate.update(sql, () -> {
저는 구현하면서 사용자의 입장을 조금 더 중요하게 생각했던 것 같아요! 

라이브러리에서 가변 인자를 활용하는 `setter`를 만들어두면 사용자는 매번 `setter`를 새로 구현하는 대신
라이브러리가 지원하는 `setter`를 활용하기만 하면 되니까요. 🤔

하지만 코드적인 장점이 더 중요하다고 생각해서 위와 같은 방식을 선택했다고 하신다면(이유가 있다면)
안나의 의견도 일리가 있다고 생각합니다! ☺️

2024-10-14 05:29 UTC, ashsty approved these changes
안녕하세요 안나~ 
수정 사항 모두 확인했어요.
이번 미션의 요구사항은 모두 만족했다고 생각해서 머지드립니다~~!! 고생하셨어요!

2024-10-14 05:29 UTC, merged