[3단계 - JDBC 라이브러리 구현하기] 망쵸(김주환) 미션 제출합니다.
woowacourse/java-jdbc pull request #789
Opened 2024-10-11 17:05 UTC by 3Juhwan

제우스, 안녕하세요. 망쵸입니다 😀 
3단계 완성해서 리뷰 요청드려요. 

3단계를 처음 진행했을 때, 서비스에서 커넥션을 만들고 트랜잭션 경계를 정하고 dao 로직을 호출하게 했어요. 코드가 굉장히 별로더군요. 
4단계에서 스레드 로컬을 사용하는 걸로 알고 있어요. 정답은 알지만, 현재 단계에서 최대한 리팩터링하고 싶었어요! 
커넥션을 서비스에서 직접 다루지 않고 싶었고, 서비스에 서비스 로직만 남기기 위해 노력했어요. 하지만, 실패했답니다.. 단순 리팩터링으로는 어렵더군요. 불가능하기에 스프링에서는 스레드 로컬을 사용하지 않을까 하는 생각이 들었어요. 

조금 보기 불편한 코드가 있을 수 있어서, 양해 부탁드려요 🙇‍♂️ 4단계에서 대부분의 코드가 삭제될 거라 생각하고 있어요!

2024-10-12 14:21 UTC, zeus6768 requested changes
안녕하세요 망쵸 👋

TransactionJdbcTemplate 클래스를 구현하신 게 인상깊네요. 

덕분에 많이 배웠어요 🙇‍♂️

말씀해주신대로 4단계에서 주요한 리팩토링이 진행될 것 같아, 부족한 점을 짚기보단 함께 학습할 만한 주제들에 대해 코멘트 남겼어요.

한 번 코멘트 주고 받은 뒤 4단계로 넘어갈게요!

2024-10-12 14:21 UTC, zeus6768 commented on jdbc/src/main/java/com/interface21/jdbc/core/TransactionJdbcTemplate.java
> +                    connection.rollback();
롤백 실행 중 예외가 발생하면 어떻게 복구할까요? 😁

2024-10-12 14:21 UTC, zeus6768 commented on jdbc/src/main/java/com/interface21/jdbc/core/TransactionJdbcTemplate.java
> +public class TransactionJdbcTemplate extends JdbcTemplate {
상속 대신 합성으로 구현할 수 있을 것 같은데, 망쵸는 어떻게 생각하나요?

2024-10-12 14:21 UTC, zeus6768 commented on jdbc/src/main/java/com/interface21/jdbc/core/TransactionJdbcTemplate.java
> +                    connection = null;
connection.close() 만으로는 만족하지 못하셨군요 👍👍👍

null을 할당해야 하는 이유는 무엇인가요? 어떤 문제를 막을 수 있나요?

2024-10-12 14:21 UTC, zeus6768 commented on jdbc/src/main/java/com/interface21/jdbc/core/ConnectionCallback.java
> +}
트랜잭션 설정 외에, 어떤 상황에 이 인터페이스를 구현해서 쓰게 될까요?

2024-10-12 15:06 UTC, 3Juhwan commented on jdbc/src/main/java/com/interface21/jdbc/core/TransactionJdbcTemplate.java
> +                    connection.rollback();
connection.rollback()에서 예외가 발생하는 상황을 보니까 3가지네요! 
1. 데이터베이스 접근 오류
2. 커넥션이 닫힌 상태
3. auto-commit이 켜진 상태

2, 3번은 애플리케이션 구현 단계에서 방지할 수 있겠는데, 1번은 개발자가 제어하기 어려운 부분이라 생각해요. 네트워크 문제, 데이터베이스 오류, 데드락 발생 등이 예시에요. 

여러 번 롤백을 재시도하다가 안된다면, 애플리케이션 수준에서는 해결하기 어려울 것 같고, 문제 상황에 적절한 대응을 해야 겠어요. 

또, 히카리처럼 커넥션을 풀링하는 상황에서는 문제가 발생한 커넥션을 폐기하는 것이 좋아요. 그럼 커넥션 풀이 자동으로 새로운 커넥션을 생성할 테니깐요. 

혹시 제우스가 알고 계신 다른 방법이 있을까요?

2024-10-12 15:30 UTC, 3Juhwan commented on jdbc/src/main/java/com/interface21/jdbc/core/TransactionJdbcTemplate.java
> +                    connection = null;
커넥션을 클래스의 필드에서 관리하기 때문에, 메서드 실행이 종료되고 null로 초기화하게 작성했어요. 
다만, 해당 클래스 구현이 좀 억지스러운 부분이 있어서 설득력 있는 근거일지는 모르겠어요. 

service와 dao 모두에서 커넥션을 직접 사용하는 것을 막고 싶었어요. 리뷰 요청드리고 계속 코드를 뜯어봤는데, 불가능하단 결론을 내리게 되었어요.. 아무리 머리를 굴려봐도 안되더라고요! 이 욕심에 억지스러운 TransactionJdbcTemplate이라는 클래스를 만들어 졌네요.

2024-10-12 16:00 UTC, 3Juhwan commented on jdbc/src/main/java/com/interface21/jdbc/core/ConnectionCallback.java
> +}
지금 이 인터페이스는 개발자로 하여금 서비스 로직에 집중할 수 있게 도와줘요. 개발자가 커넥션, 트랜잭션 설정을 할 필요가 없어요. 
그 외에는 JDBC를 저수준 레벨까지 사용해야 하는 상황에서 도움이 될 것 같아요. 그런 상황을 맞이한 적이 없어서, 잘 떠오르지 않네요. 
제우스가 알고 계신 게 있다면 공유 부탁드려요!

2024-10-12 16:28 UTC, 3Juhwan commented on jdbc/src/main/java/com/interface21/jdbc/core/TransactionJdbcTemplate.java
> +public class TransactionJdbcTemplate extends JdbcTemplate {
아무래도 상속보다는 합성(조합)이 변화에 더 유연하게 대처할 수 있을 거에요! 대부분의 상황에서 합성이 좀더 좋을 거라 생각해요. 

그럼에도 상속으로 구현한 이유는, 현재 상황에서 기존 JdbcTemplate의 변경을 최소화할 수 있기 때문이에요. 실제로 PR에서 JdbcTemplate 변경된 부분은 일부 메서드가 `private` -> `protected` 되었다는 점인데요. 또, dao 코드는 변경이 없어요. 

합성을 사용한다면 dao에 JdbcTemplate을 TxJdbcTemplate으로 변경해야 하고, TxJdbcTemplate이 JdbcTemplate의 역할을 하기 위해선 JdbcTemplate가 제공하는 메서드를 모두 구현해야 해요 😢 

두 버전 모두 구현해 보았었는데, 4단계에서 버려질 클래스라는 걸 아니까 4단계 pr에서 변경되는 부분을 적게 하려고 상속을 택했어요.

2024-10-13 03:35 UTC, zeus6768 approved these changes
고생하셨어요 망쵸~!

3단계는 이만 머지할게요 ㅎㅎ

4단계도 화이팅입니다!!

2024-10-13 03:35 UTC, zeus6768 commented on jdbc/src/main/java/com/interface21/jdbc/core/TransactionJdbcTemplate.java
> +                    connection = null;
이번 미션 3단계에서만 해볼 수 있는 좋은 시도였다고 생각해요~!

주어진 코드에서 많은 시도를 하신 게 느껴졌어요 👍

2024-10-13 03:35 UTC, merged