[3단계 - JDBC 라이브러리 구현하기] 로키(정해성) 미션 제출합니다.
woowacourse/java-jdbc pull request #794
Opened 2024-10-12 06:14 UTC by HaiSeong

짱수 안녕하세요.
이번 3단계는 테스트를 통과하는것을 최우선 목표로 세우고 미션을 진행했습니다.
편하게 리뷰 부탁드립니다.

2024-10-12 11:09 UTC, zangsu requested changes
로키~~ 3단계 코드도 잘 구현해 주셨습니다!
특히 `TransactionManager` 의 구현은 꽤나 만족스러워서 제 3단계 구현에 깊이 영향을 받을까 두렵네요 ㅎㅎ
전체적으로 코드도 깔끔하게 잘 정리해 주셔서 리뷰하는데 어려움이 없었어요!
몇가지 제안사항 / 궁금한 점들을 코멘트로 남겨 두었으니 확인 부탁 드립니다!

2024-10-12 11:09 UTC, zangsu commented on app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
>  public class MockUserHistoryDao extends UserHistoryDao {
개인적인 선호인데, 저는 테스트를 위한 객체일지라도 `MockXXX`, `FakeXXX` 로 클래스 네이밍을 하는 것을 지양하는데요. 
이유는 "어떤 부분이 모킹 된" / "어떤것이 다른 Fake인" 것인지의 정보를 담지 못하기 때문이에요.
때문에 역할을 잘 담을 수 있는 `InMemoryXXX` 와 같은 네이밍을 사용하곤 하는데요.

혹시 해당 클래스의 네이밍을 변경해 보는 것은 어떻게 생각하실까요?

2024-10-12 13:50 UTC, HaiSeong commented on study/src/test/java/transaction/stage2/Stage2Test.java
>      void testRequiredNewWithRollback() {
first 트랜잭션은 롤백 되고 second 트랜잭션은 커밋되버립니다.
이걸 의도했다면 좋은거고
의도하지 않았다면 망한거죠

2024-10-12 14:01 UTC, HaiSeong commented on study/src/test/java/transaction/stage2/Stage2Test.java
> +     * -> 물리적 트랜잭션은 실제 데이터베이스에 커밋되거나 롤백되는 트랜잭션을 말하고 논리적 트랜잭션은 서비스 메서드에서 사용하는 트랜잭션을 말한다.
NOT_SUPPORTED의 동작은
1. 현재 트랜잭션이 존재하면, 해당 트랜잭션을 일시 중단합니다.
2. 메서드를 트랜잭션 없이 실행합니다.
3. 메서드 실행이 끝나면, 원래 트랜잭션을 재개합니다.

그래서 first에 어노테이션이 붙어있으면 first 트랜잭션이 실행되다가 중단되고 second 트랜잭션을 한 후 다시 first 트랜잭션이 재개됩니다.

first에 어노테이션이 없으면 second만 실행됩니다.

2024-10-12 14:05 UTC, zangsu commented on study/src/test/java/transaction/stage2/Stage2Test.java
> +     * -> 물리적 트랜잭션은 실제 데이터베이스에 커밋되거나 롤백되는 트랜잭션을 말하고 논리적 트랜잭션은 서비스 메서드에서 사용하는 트랜잭션을 말한다.
> 2. 메서드를 트랜잭션 없이 실행합니다.
와 
> second 트랜잭션을 한 후
가 서로 다른 이야기 같아요.

로키의 요점은 존재하는 트랜잭션이 있다면 해당 트랜잭션을 일시정지.
현재의 메서드는 트랜잭션 없이 동작한단거죠?

그렇다면 주석 처리 전의 물리적 트랜잭션은 2개가 맞나요?
주석 처리 이후의 물리적 트랜잭션은 1개가 맞나요?

2024-10-12 14:08 UTC, HaiSeong commented on jdbc/src/test/java/com/interface21/transaction/TransactionManagerTest.java
> +        when(connection.getAutoCommit()).thenReturn(true);
원래 잘 안쓰려고 하고 잘 못씁니다. ㅋㅋ ㅠㅠㅠㅠㅠ

그런데 TransactionManager를 테스트 할 방법을 찾지 못했어요.
제 생각에 이걸 테스트 해보려면 정상 동작 했을때 실제로 데이터 베이스에 값이 들어갔는지,
또는 실패했을때 기존 상태 그대로 인지를 테스트 해야해여.
이렇게 되면 이걸 위한 객체를 또 만드는게 코스트가 크고 이 객체가 잘 작동하는지 여부를 확신할 수 없어 테스트가 추가로 필요하다 생각해요.
개인적으로 제가 짠 테스트가 눈으로도 확인할 수 있는걸 테스트 코드로 검증한다고 생각되요.
코드에 `setAutoCommit(false)` 가 있는지 `commit()` 이 있는지 눈으로 확인하면 되니까요.
그렇지만 이 테스트가 있는것 만으로 다른 개발자에게 믿음을 줄 수 있지않나 생각이 들어요.

2024-10-12 14:13 UTC, HaiSeong commented on study/src/test/java/transaction/stage2/Stage2Test.java
> +     * -> 물리적 트랜잭션은 실제 데이터베이스에 커밋되거나 롤백되는 트랜잭션을 말하고 논리적 트랜잭션은 서비스 메서드에서 사용하는 트랜잭션을 말한다.
그러네요. 제가 설명한걸 제가 읽어봐도 이상하네요. 눈으로 확인할때는 분명히 2개의 트랜잭션이 나오는데 이상하다고 생각이 되어요

2024-10-12 14:15 UTC, HaiSeong commented on study/src/test/java/transaction/stage2/Stage2Test.java
> +     * -> 물리적 트랜잭션은 실제 데이터베이스에 커밋되거나 롤백되는 트랜잭션을 말하고 논리적 트랜잭션은 서비스 메서드에서 사용하는 트랜잭션을 말한다.
>NOT_SUPPORTED 메서드 자체는 트랜잭션 없이 실행되지만, 그 내부의 데이터베이스 작업은 필요에 따라 새로운 트랜잭션을 생성합니다. 이것이 두 번째 트랜잭션이 생기는 이유입니다.

라고 하는데 이 이유가 맞는지 궁금해요!

2024-10-12 14:15 UTC, HaiSeong commented on jdbc/src/main/java/com/interface21/transaction/TransactionManager.java
> +    public void transaction(Consumer<Connection> function) {
앗 수정하겠습니다!

2024-10-12 14:19 UTC, HaiSeong commented on jdbc/src/main/java/com/interface21/transaction/TransactionManager.java
> +    private void executeTransaction(Consumer<Connection> consumer, Connection connection) throws SQLException {
우선 인자가 달라 오버로딩이 가능했고
이름을 다르게 한다면 `executeTransactionWithConsumer`, `executeTransactionWithFunction` 정도가 되었을것 같아요.
프라이빗 메소드긴 하지만 이미 인자의 타입을 보고 알 수 있는 정보인데 메서드 이름에 담을 필요는 없다 생각했어요!

2024-10-12 14:19 UTC, HaiSeong commented on jdbc/src/main/java/com/interface21/transaction/TransactionManager.java
> +    public <T> T transaction(Function<Connection, T> function) {
동사형으로 변경해버리겠습니다. 👍

2024-10-12 14:20 UTC, HaiSeong commented on jdbc/src/test/java/com/interface21/transaction/TransactionManagerTest.java
> +        });
반영하겠습니다. 의미가 없는 주석이네요!

2024-10-12 14:29 UTC, HaiSeong commented on app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
>  public class MockUserHistoryDao extends UserHistoryDao {
좋은 네이밍이네요. 반영해보겠습니다.
항상 `TestXXX` 같은 이름을 지었는데 앞으로도 `InMemoryXXX`를 애용할것 같아요

2024-10-13 08:45 UTC, zangsu commented on study/src/test/java/transaction/stage2/Stage2Test.java
> +     * -> 물리적 트랜잭션은 실제 데이터베이스에 커밋되거나 롤백되는 트랜잭션을 말하고 논리적 트랜잭션은 서비스 메서드에서 사용하는 트랜잭션을 말한다.
"제가 알기론" 주석처리 하기 이전엔 `FirstUserService` 때문에 물리적 트랜잭션이 트랜잭션 하나만, 주석처리 이후에는 물리적 트랜잭션이 아무것도 없는 것이 맞을 거에요.

> 눈으로 확인할때는 분명히 2개의 트랜잭션이 나오는데 이상하다고 생각이 되어요

아마 이 "눈으로 확인한" 것은 테스트코드의 반환값인 `Set<String>` 의 개수를 말하는 것 같은데요.
제 생각에는 `Set` 의 원소 개수와 물리적 트랜잭션의 개수는 다른 것 같기도 하네요
저는 그래서 콘솔에 출력되는 로그를 확인하면서 테스트 했어요.

```java
2024-10-13T17:41:45.362+09:00  INFO 48166 --- [    Test worker] transaction.stage2.FirstUserService      : 
transaction.stage2.FirstUserService.saveFirstTransactionWithNotSupported is Actual Transaction Active : ✅ true
Hibernate: insert into users (account,email,password,id) values (?,?,?,default)
2024-10-13T17:41:45.363+09:00  INFO 48166 --- [    Test worker] transaction.stage2.SecondUserService     : 
transaction.stage2.SecondUserService.saveSecondTransactionWithNotSupported is Actual Transaction Active : ❌ false
```

확실한 것은 아니지만,,, 저는 이 로그의 트랜잭션들이 물리 트랜잭션이라 생각하고 테스트를 진행했습니다.
이런 로그들이 같이 찍히니 이 부분도 확인을 해 보시죠!

+) 또는 H2 에서 찍히는 로그를 확인할 수 도 있어요.
`application.yml` 의 `TRACE_LEVEL_SYSTEM_OUT=3;` 부분을 주석 해제 하면 됩니다!

2024-10-13 08:47 UTC, zangsu commented on app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
>  public class MockUserHistoryDao extends UserHistoryDao {
어라, 제 의도는  "어떤것이 다른 Fake인" 것인지를 나타내는 이름으로 바꿔보는 것이었어요...ㅎㅎ
이번의 `MockUserHistoryDao` 는 예외를 던지기 위한 Dao 이니 `NotWorkXXX` 나 `AlwaysTrowXXX` 와 같은 네이밍을 고려해 봐도 좋을 것 같습니닷..

2024-10-13 09:38 UTC, zangsu approved these changes
고생하셨습니다 로키! 
4단계의 로키 코드가 기대되네요~~

학습 테스트 관련 코멘트 하나, 클래스 명 관련 코멘트 하나 남겨두었으니 확인해 보시고 다음 단계에서 마저 반영 해 주시면 좋을 것 같아요!
3단계는 이만 머지하겠습니다~

2024-10-13 09:38 UTC, merged

2024-10-14 06:14 UTC, HaiSeong commented on app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
>  public class MockUserHistoryDao extends UserHistoryDao {
아하 짱수의 의도를 알았습니다. `AlwaysThrowXXX` 라는 네이밍이 예외를 던지는 이름이 담겨있네요! 이걸 적용해볼게요.

2024-10-14 06:38 UTC, HaiSeong commented on study/src/test/java/transaction/stage2/Stage2Test.java
> +     * -> 물리적 트랜잭션은 실제 데이터베이스에 커밋되거나 롤백되는 트랜잭션을 말하고 논리적 트랜잭션은 서비스 메서드에서 사용하는 트랜잭션을 말한다.
확인해봤습니다.
결론적으로 NOT_SUPPORTED 는 진행되는 트랜잭션이 있으면 중지 하고 트랜잭션 없이 비즈니스 로직을 실행하는군요.
해당 값을 1 / 0 이 맞을것 같아요.
짱수 덕분에 대충 넘어갈뻔 했는데 잘 학습할 수 있었습니다!