[4단계 - JDBC 라이브러리 구현하기] 폭포(이성주) 미션 제출합니다.
woowacourse/java-jdbc pull request #824
Opened 2024-10-13 02:12 UTC by BurningFalls

안녕하세요, 테니! 4단계 Transaction synchronization 적용과 AOP 학습테스트 구현 완료하여 PR 보냅니다. 😄 

진행 순서대로 큰 틀을 하나의 커밋으로 묶어 관리했으니, 커밋 순서대로 따라가시면 리뷰하기 편하실 것 같습니다.

리뷰 부탁드립니다. 감사합니다! 🙇

2024-10-14 07:28 UTC, ay-eonii requested changes
안녕하세요 폭포~

벌써 마지막 미션이네요!

요구사항 잘 만족해주셔서 큰 수정요청은 없습니다 ㅎ ㅎ 

간단한 질문 몇가지 남겼는데 확인 부탁드려요 ~

마지막까지 화이팅 💪

2024-10-14 07:28 UTC, ay-eonii commented on jdbc/src/main/java/com/interface21/transaction/support/TransactionSynchronizationManager.java
> +                .orElse(null);
`ThreadLocal.withInitial()` 를 활용하면 nullable을 방지할 수 있을 것 같아요 😄

2024-10-14 07:28 UTC, ay-eonii commented on jdbc/src/test/java/com/interface21/transaction/support/TransactionSynchronizationManagerTest.java
> +        TransactionSynchronizationManager.bindResource(dataSource, connection);
unbind전에 connection이 있는지 확인해보는 것도 좋겠어요 ㅎㅎ

2024-10-14 07:28 UTC, ay-eonii commented on app/src/main/java/com/techcourse/service/TxUserService.java
> +            conn.setAutoCommit(false);
사소하지만, changePasswordWithTransaction 메서드 내부에서 설정하는 게 더 자연스러울 것 같은데 어떻게 생각하시나요 ? ㅎㅎ

2024-10-14 07:28 UTC, ay-eonii commented on app/src/main/java/com/techcourse/service/TxUserService.java
> +            TransactionSynchronizationManager.unbindResource(dataSource);
bind는 DataSourceUtils에서 하는데, unbind는 외부에서 하고있네요! 의도한 바가 있는지 궁금해요!

2024-10-14 07:28 UTC, ay-eonii commented on study/src/test/java/aop/stage0/TransactionHandler.java
> +}
EOF 경고가 있어용 👀

2024-10-14 07:28 UTC, ay-eonii commented on study/src/test/java/aop/stage1/Stage1Test.java
> +        proxyFactoryBean.setProxyTargetClass(true);
해당 설정은 무엇일까용 ? 그리고 false와 어떤 차이가 있을까요?

2024-10-14 07:28 UTC, ay-eonii commented on study/src/test/java/aop/stage2/AopConfig.java
> +    }
이 빈은 무엇인가용?

2024-10-14 07:28 UTC, ay-eonii commented on jdbc/src/test/java/com/interface21/transaction/support/TransactionSynchronizationManagerTest.java
> +    void testBindResource() {
👍 꼼꼼한 폭포 ..

2024-10-15 01:46 UTC, BurningFalls commented on jdbc/src/main/java/com/interface21/transaction/support/TransactionSynchronizationManager.java
> +                .orElse(null);
안그래도 만들면서도 단순한 방법이 없을까 계속 고민하다가 방법을 찾지 못했었는데 이런 방법이 있었네요! 감사합니다 ㅎㅎ 1b5d4690a14ca51cce244f86eb4318d1398072d6

2024-10-15 02:00 UTC, BurningFalls commented on jdbc/src/test/java/com/interface21/transaction/support/TransactionSynchronizationManagerTest.java
> +        TransactionSynchronizationManager.bindResource(dataSource, connection);
`bindResource`를 하지 않아도 `unbindResource`에서 에러가 나지 않아, 결국에 가져오는 resource가 null이어서 바인딩 해제 테스트를 제대로 수행했다고 보기 어렵네요! 놓치고 있었던 부분이었습니다. 감사합니다! 239a7e00675251f461995410de331fecc96d97ba

2024-10-15 02:07 UTC, BurningFalls commented on app/src/main/java/com/techcourse/service/TxUserService.java
> +            conn.setAutoCommit(false);
이름을 `WithTransaction`이라고 하고 commit을 밖에서 해주고 있었네요 😅 테니가 말씀해 주신게 더 자연스러운 것 같아요! 수정했습니다. 2c25dc14b00eff41487865057e48986b639e2c44

2024-10-15 02:25 UTC, BurningFalls commented on app/src/main/java/com/techcourse/service/TxUserService.java
> +            TransactionSynchronizationManager.unbindResource(dataSource);
커넥션을 가져오는데 실패하면 `bindResource`를 하지 않는 것이 자연스럽지만, 커넥션을 닫는데 실패하더라도 확실하게 `unbind`를 해주고 싶어서 `DataSourceUtils.releaseConnection()` 메서드 안에 바인드 해제 로직을 넣지 않았습니다.

2024-10-15 02:52 UTC, BurningFalls commented on app/src/main/java/com/techcourse/service/TxUserService.java
> +            TransactionSynchronizationManager.unbindResource(dataSource);
처음에는 커넥션을 닫는 것이 실패하더라도 `unbind`를 해주어야 하기 때문에 분리했다고 생각했었는데, 확인해보니 finally 두번째 구문이 실행이 안될뿐더러 오히려 더 애매해지는 것 같네요. 지금으로서는 딱히 외부 내부 로직 분리의 이유는 없는 것 같습니다.

2024-10-15 03:24 UTC, BurningFalls commented on study/src/test/java/aop/stage1/Stage1Test.java
> +        proxyFactoryBean.setProxyTargetClass(true);
<img width="658" alt="image" src="https://github.com/user-attachments/assets/7782ecec-2619-4121-9398-12cdf889dab8">

해당 설정은 프록시가 인터페이스의 구현체인 클래스도 타겟으로 설정할 수 있도록 해주는 설정으로 이해하고 있습니다. false인 경우, 인터페이스만 타겟으로 설정할 수 있어, `stage1.UserService`를 바라보지 못해 테스트가 돌아가지 않는 것을 확인할 수 있었습니다.

2024-10-15 04:21 UTC, BurningFalls commented on study/src/test/java/aop/stage2/AopConfig.java
> +    }
ㅋㅋ 알빠임 쓰레빠임 ㅋㅋ

2024-10-15 06:12 UTC, BurningFalls commented on study/src/test/java/aop/stage2/AopConfig.java
> +    }
이렇게 하면 자동으로 컨테이너에 있는 모든 Advisor를 감지하여, 프록시가 필요한 빈에 대해 프록시 객체를 생성해줄 수 있습니다. 또한, 프록시객체의 세부 설정도 한번에 처리하여 AOP를 지원할 수 있습니다.

2024-10-15 10:56 UTC, BurningFalls commented
꼼꼼한 리뷰 감사합니다, 테니! 리뷰 반영과 코멘트 확인부탁드려요~

2024-10-15 14:52 UTC, ay-eonii commented on study/src/test/java/aop/stage2/AopConfig.java
> +    }
그렇군요 ! 배워갑니다 😁

2024-10-15 14:54 UTC, ay-eonii approved these changes
안녕하세요! 리뷰 반영해주신 거 확인했습니다 ~

JDBC 미션 고생많으셨어요 👏
다음 미션도 화이팅입니다 💪

2024-10-15 14:54 UTC, merged