[3단계 - JDBC 라이브러리 구현하기] 다온(조형익) 미션 제출합니다.
woowacourse/java-jdbc pull request #831
Opened 2024-10-13 06:34 UTC by ikjo39

안녕하세요 아토!
벌써 3단계라니 시간 참 빠르네요 🥹

다른 서비스에 동일하게 사용할 수 있도록 범용성을 위해 트랜잭션을 부여하는 로직을 외부로 분리하였습니다.
또 그때마다 의존성을 주입해야하니 AOP가 필요한 이유가 간접적으로 느껴지네요 ㅎ
이번 리뷰도 잘 부탁드립니다!

2024-10-13 09:46 UTC, hyxrxn requested changes
다온 안녕하세요. 아토입니다!

너무 깔끔하게 잘 구현해주셔서 크게 남길 말이 없네요.
몇 가지 질문 남겼으니 답변 후 다시 리뷰요청 주세요~~~
4단계까지 최대한 빠르게 가봅시닷

화이팅💪

2024-10-13 09:46 UTC, hyxrxn commented on app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
> +    }
테스트를 위해 오버라이드 한 메서드인데, 테스트에서 더이상 사용하지 않는 이 메서드 위의 메서드는 지워도 되지 않을까요?

2024-10-13 09:46 UTC, hyxrxn commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +            return handleQuery(conn, query, preparedStatementExecutor, objects);
기존 메서드 내부에서 커넥션을 추가한 메서드를 부르니 더 깔끔하네요!
그냥 복붙하고 커넥션만 추가한 저를 반성합니다...

2024-10-13 09:46 UTC, hyxrxn commented on docs/README.md
> +- [x] 리팩토링 고민하기
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 귀엽군요...

2024-10-13 09:46 UTC, hyxrxn commented on jdbc/src/main/java/com/interface21/transaction/support/TransactionManager.java
> +            conn.setAutoCommit(false);
이후에 설정을 다시 되돌려놓지 않아도 괜찮을까요?

2024-10-13 09:46 UTC, hyxrxn commented on jdbc/src/main/java/com/interface21/transaction/support/TransactionManager.java
> +            throw new DataAccessException("데이터 접근 과정에서 문제가 발생하였습니다.", e);
각 상황별로 어떤 예외를 던질지에 대한 다온의 기준이 궁금해요!

2024-10-13 09:46 UTC, hyxrxn commented on app/src/test/java/com/techcourse/service/UserServiceTest.java
> +    @DisplayName("트랜잭션이 도중 예외가 발생하면 데이터 변경이 롤백된다.")
```suggestion
    @DisplayName("트랜잭션 도중 예외가 발생하면 데이터 변경이 롤백된다.")
```

2024-10-13 09:46 UTC, hyxrxn commented on app/src/test/java/com/techcourse/service/UserServiceTest.java
> +        String createBy = "gugu";
final을 뗀 이유가 따로 있으신지요???

2024-10-13 10:47 UTC, ikjo39 commented on app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
> +    }
옙 동의합니다!
해당 메서드 삭제하였습니다!

2024-10-13 10:50 UTC, ikjo39 commented on jdbc/src/main/java/com/interface21/transaction/support/TransactionManager.java
> +            conn.setAutoCommit(false);
현재는 커넥션을 사용한 후 재사용 없이 반환하므로 괜찮다 생각하였습니다!

2024-10-13 10:54 UTC, ikjo39 commented on jdbc/src/main/java/com/interface21/transaction/support/TransactionManager.java
> +            throw new DataAccessException("데이터 접근 과정에서 문제가 발생하였습니다.", e);
같은 예외를 던지고 있어서 여쭤보신걸까요? 

1. DataSource 객체에서 Connection 을 획득하는 과정에서 발생한 예외인 경우
2. Transaction을 수행하는 과정에서 발생한 `SQLException`과 `DataAccessException`(런타임) 예외인 경우
3. Rollback 을 수행하는 과정에서 예외인 경우

위의 3가지 예외 상황을 다른 문맥으로 보아 서로 다르게 처리하였습니다.

2024-10-13 10:56 UTC, ikjo39 commented on app/src/test/java/com/techcourse/service/UserServiceTest.java
> +    @DisplayName("트랜잭션이 도중 예외가 발생하면 데이터 변경이 롤백된다.")
`@DisplayName`을 다시 보는 습관이 정착 안되어있나봐요.
지속적으로 받아오던 리뷰여서 덕분에 메타인지 확실히 되었습니다 :)

2024-10-13 10:59 UTC, ikjo39 commented on app/src/test/java/com/techcourse/service/UserServiceTest.java
> +        String createBy = "gugu";
final 키워드를 붙이려면 철저하게 모든 코드에 나타내야 한다는 주의입니다.
1, 2, 3 레벨을 거치며 저 혼자 하더라도 수 많은 휴먼 에러로 안 붙이던 부분이 보이더라구요.
혼란을 방지하기 위해 final 키워드를 지양하는 편입니다.
\+ 원래는 모든 범위에서 final 키워드를 삭제해야 맞지만 미션에서는 영향을 주는 범위 안에서만 수정하였습니다 :)

2024-10-13 16:26 UTC, hyxrxn requested changes
질문이 아직 남아 약간만 더 남겼습니다!
답변 기다리고 있을게요 🤗

2024-10-13 16:26 UTC, hyxrxn commented on jdbc/src/main/java/com/interface21/transaction/support/TransactionManager.java
> +            conn.setAutoCommit(false);
그런데 `TransactionManager`은 말 그대로 `트랜잭션`을 관리해주는 역할이잖아요.
얘가 커넥션을 재사용하는지 안하는지를 알 필요가, 혹은 알 수가 있을까요?
본인이 어떤 `DataSource`를 쓰고 있는건지 구체적으로 모를텐데요.

2024-10-13 16:26 UTC, hyxrxn commented on app/src/test/java/com/techcourse/service/UserServiceTest.java
> +        String createBy = "gugu";
저도 동의합니다!!

붙이려면 통일해야 한다는 것과, 영향을 주는 범위 안에서만 수정하는 것도요!
지금이야 클래스가 아주 많지는 않지만 언젠가 클래스가 엄청나게 많은 것을 수정해야 한다면...
모든 곳을 다 고칠 수는 없겠죠.

2024-10-13 16:26 UTC, hyxrxn commented on jdbc/src/main/java/com/interface21/transaction/support/TransactionManager.java
> +            throw new DataAccessException("데이터 접근 과정에서 문제가 발생하였습니다.", e);
> 같은 예외를 던지고 있어서 여쭤보신걸까요?

네!
JdbcTemplate 과 TransactionManager 모든 곳에서 예외 상황시 다 같은 예외를 던지고 있어 그 부분이 궁금해 여쭤봤습니다~~
저는 단일 시도에서 예외가 발생한 상황과 하나의 트랜잭션에서 예외가 발생한 상황을 구분해야 하는거 아닌지 고민을 했었어서요.
같은 예외로 처리되어 `서로 다르게 처리`했다는 부분이 이해가 잘 안가는데 메시지로 구분을 해주었다는 의미가 맞을까요?!

2024-10-14 00:37 UTC, ikjo39 commented on jdbc/src/main/java/com/interface21/transaction/support/TransactionManager.java
> +            conn.setAutoCommit(false);
아토 말이 맞네요!
커넥션의 기본 상태가 autocommit true 설정이 되어있으니 다시 맞춰주겠습니다.

2024-10-14 00:38 UTC, ikjo39 commented on jdbc/src/main/java/com/interface21/transaction/support/TransactionManager.java
> +            throw new DataAccessException("데이터 접근 과정에서 문제가 발생하였습니다.", e);
옙 메세지로 구분하여 처리해주었습니다.
더 명확한 의미 전달을 위해선 다른 예외로 던져줄 필요도 있어보이네요
각 상황별로 예외를 추가할게요!

2024-10-14 03:49 UTC, hyxrxn commented on jdbc/src/main/java/com/interface21/transaction/support/TransactionManager.java
> +            conn.setAutoCommit(false);
false로 바꾸는 부분과 true로 다시 바꾸는 부분이 두 메서드로 분리되어있어서 약간 헷갈릴 것 같다는 생각이 들기는 하네요...!!!
다음 단계 진행 전 관련해서 잠깐 생각 한 번만 해보시고 넘어가시죠.

2024-10-14 03:52 UTC, hyxrxn approved these changes
모두 확인 되었습니다~~~ 💯
고생하셨고... 5시간 화이팅입니다!
4단계에서 보아요

2024-10-14 03:52 UTC, hyxrxn commented on jdbc/src/main/java/com/interface21/transaction/support/TransactionManager.java
> +            conn.setAutoCommit(false);
false로 바꾸는 부분과 true로 다시 바꾸는 부분이 두 메서드로 분리되어있어서 약간 헷갈릴 것 같다는 생각이 들기는 하네요...!!!
다음 단계 진행 전 관련해서 잠깐 생각 한 번만 해보시고 넘어가시죠.

2024-10-14 03:52 UTC, merged