[3단계 - Transaction 적용하기] 레디(최동근) 미션 제출합니다.
woowacourse/java-jdbc pull request #836
Opened 2024-10-13 08:49 UTC by reddevilmidzy

안녕하세요 초코칩!! 

리팩터링하고 싶은 부분들이 많았지만 다음 단계로 미루고 구현에 집중하였습니다..! 

이번 리뷰도 잘 부탁드립니다 :)

2024-10-13 13:26 UTC, Chocochip101 requested changes
빠르게 구현해주셨네요, 레디!

리뷰 남겼으니 확인 부탁드려요 😄

2024-10-13 13:26 UTC, Chocochip101 commented on app/src/main/java/com/techcourse/service/UserService.java
> +        try (final Connection connection = dataSource.getConnection()) {
Datasource로부터 커넥션을 가져오는 로직을 UserService에서 제거해보는 것은 어떤가요?

2024-10-13 13:26 UTC, Chocochip101 commented on app/src/main/java/com/techcourse/domain/User.java
> +    public Long getId() {
변경하신 이유가 있나요?

2024-10-13 13:26 UTC, Chocochip101 commented on jdbc/src/main/java/com/interface21/jdbc/core/TransactionManager.java
> +            connection.commit();
autoCommit을 다시 true로 설정할 필요는 없을까요?

2024-10-13 16:14 UTC, reddevilmidzy commented on app/src/main/java/com/techcourse/service/UserService.java
> +        try (final Connection connection = dataSource.getConnection()) {
넵! UserService에서 커넥션을 가져오는 책임을 transactionManager에게 넘겨주었습니다..! 변경한 코드가 썩 마음에 들지는 않지만 4단계 때 더 발전시켜보겠습니닷 😃

2024-10-14 01:44 UTC, Chocochip101 approved these changes
레디의 의견 잘 들었고, 피드백 빠르게 해주셨네요👍

4 단계까지 화이팅입니다🙌🏻

2024-10-14 01:44 UTC, merged