[4단계 - JDBC 라이브러리 구현하기] 비토(오상훈) 미션 제출합니다.
woowacourse/java-jdbc pull request #847
Opened 2024-10-13 12:04 UTC by unifolio0

안녕하세요 레모네!
생각보다 코드가 맘에 들지 않은데 아직 명확한 해결책은 안 떠올라서 고민하다가 일단 리뷰 요청 보냅니다!
벌써 마지막 단계네요!
리뷰 잘 부탁드립니다!

2024-10-14 09:25 UTC, JiHyeonL requested changes
안녕하세요 비토! 레모네입니다.
제가 아직 학습 테스트를 마무리 하지 못해서 기능 위주로 리뷰 남겼습니다 😭

다음 리뷰 요청 때는 학습 테스트 리뷰도 꼭 달아드리겠습니다!

마지막 미션도 화이팅 😎

2024-10-14 09:25 UTC, JiHyeonL commented on jdbc/src/main/java/com/interface21/transaction/support/TransactionSynchronizationManager.java
>      }
`remove` 하기 전에 데이터소스가 존재하는지 확인하는 방어로직이 있으면 좋을 것 같네요!

2024-10-14 09:25 UTC, JiHyeonL commented on jdbc/src/main/java/com/interface21/jdbc/TransactionManager.java
> +            connection = DataSourceUtils.getConnection(dataSource);
try 문 밖에서 
`Connection connection = DataSourceUtils.getConnection(dataSource)`로 정의 하지 않고, null로 초기화 한 뒤 try 문 안에서 커넥션을 할당해 준 이유가 있을까요?

2024-10-15 02:50 UTC, unifolio0 commented on jdbc/src/main/java/com/interface21/transaction/support/TransactionSynchronizationManager.java
> +        }
수정했습니다!

2024-10-15 02:52 UTC, unifolio0 commented on jdbc/src/main/java/com/interface21/transaction/support/TransactionSynchronizationManager.java
>      }
수정했습니다!

2024-10-15 02:55 UTC, unifolio0 commented on jdbc/src/main/java/com/interface21/jdbc/TransactionManager.java
> +            connection = DataSourceUtils.getConnection(dataSource);
`DataSourceUtils.getConnection(dataSource)`하는 로직에서 예외가 발생했을 때 `try-catch`로 처리해주기 위함이었는데 확인해보니 내부 로직에서 예외 처리를 해주고 있었네요!

수정했습니다!

2024-10-16 17:01 UTC, JiHyeonL requested changes
안녕하세요 비토! 리뷰가 너무 늦었죠 죄송합니다😢
위에 언급드린대로 학습테스트 관련 리뷰 남겼습니다!

요구사항은 다 만족시키셔서 다음 리뷰 요청 때 어프루브 할 것 같습니다.

마지막까지 화이팅이에요!!

2024-10-17 01:06 UTC, unifolio0 commented on study/src/test/java/aop/stage1/TransactionPointcut.java
>      }
수정했습니다! 추가로 `Transactional` 어노테이션이 메소드에만 붙일 수 있길래 `ElementType.TYPE`도 추가했습니다!

2024-10-17 01:17 UTC, unifolio0 commented on study/src/test/java/aop/stage1/TransactionAdvisor.java
>      }
해당 메소드는 `advice`가 같은 클래스일 때 각각의 인스턴스에 별도로 적용이 될지(`true`) 일괄적으로 적용이 될지(`false`)를 결정하는 메소드입니다!
다만, 현재의 프레임 워크에서는 사용하지 않는다고 합니다.
`true`로 바꾼이유는 `default`값이 `true`고 대부분의 구현체도 `true`를 반환하기에 `true`를 반환하도록 했습니다!

2024-10-17 01:26 UTC, unifolio0 commented on study/src/test/java/aop/stage1/Stage1Test.java
> +        UserService userService = (UserService) proxyFactoryBean.getObject();
`UserService`가 `Interface`가 없기 때문에 해당 상황에서는 자동으로 `CGLIB 프록시`가 생성됩니다!
`setProxyTargetClass(true);`는 `Interface`가 있어도 `CGLIB 프록시`를 사용하도록 강제해주는 메소드 입니다.
> 그리고 CGLIB 프록시가 생성되지 않는 상황은 언제일까요?

1. `Interface`가 존재하고 `setProxyTargetClass(false);`로 설정되어 있거나
2. `CGLIB` 라이브러리가 클래스패스에 없는 경우에 `CGLIB 프록시`가 생성되지 않습니다!

2024-10-17 01:31 UTC, JiHyeonL approved these changes
비토! 피드백 반영해 주신 부분 확인했습니다.
마지막 4단계 미션까지 수고 많으셨습니다 👏
다음 미션도 화이팅이에요!! 😭

2024-10-17 01:31 UTC, merged