[4단계 - JDBC 라이브러리 구현하기] 도비(김도엽) 미션 제출합니다.
woowacourse/java-jdbc pull request #863
Opened 2024-10-14 02:30 UTC by Dobby-Kim

안녕하세요 뽀오오오온드

벌써 마지막 리뷰 요청이군요!

이번 리뷰에서는 마지막 리뷰인만큼 여유를 가지고 여러 얘기 나눠보면 좋을 것 같습니다 :>

리뷰 잘부탁드린다구요😘😘

2024-10-15 07:10 UTC, tackyu requested changes
안녕하세요 도비
4단계까지 고생 많으셨습니다!👍👍
몇가지 코멘트 남겼는데, 확인 부탁 드릴게요
다음에 학습테스트도 같이 제출해주시면 좋을 것 같습니다!

2024-10-15 07:10 UTC, tackyu commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +    }
dataSource를 반환하게끔 설계하신 이유가 궁금합니다
`update`와 같은 메서드에서 직접 커넥션을 가져와, 메서드 오버로딩을 없애는 것에 대해 도비의 의견이 궁금하네요!

2024-10-20 10:00 UTC, Dobby-Kim commented on app/src/main/java/com/techcourse/service/TxUserService.java
> +        }
`unbindedResource`는 단순히 바인딩을 끊는 용도로도 사용되어야된다고 생각합니다. 같은 `Transaction`을 사용하다가도, 사용하지 않을 수도 있어야하니까요 :>

2024-10-20 10:02 UTC, Dobby-Kim commented on app/src/main/java/com/techcourse/service/TxUserService.java
> +                conn.rollback();
Transaction 안에서의 sql 쿼리가 실패하면 rollback 해야하지 않을까요?

2024-10-20 10:04 UTC, Dobby-Kim commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +    }
해당 jdbcTemplate에서 datasource를 가져와야 Util에서 map으로 존재하는 같은 connection을 찾아 들고 올 수 있게 했어야했습니다!

2024-10-22 07:15 UTC, tackyu commented on app/src/main/java/com/techcourse/service/TxUserService.java
> +                conn.rollback();
```java   
  try (Connection conn = DataSourceUtils.getConnection(dataSource)) {
            conn.setAutoCommit(false);
            User user = updateUserPassword(conn, id, newPassword);
            userHistoryDao.log(conn, new UserHistory(user, createBy));
            conn.commit();
        } catch (SQLException e) {
            throw new DataAccessException("Failed to change password", e);
        }
```
이전 단계에서 `try-catch`로 처리 하셔서 궁금했습니다!

2024-10-29 05:28 UTC, tackyu approved these changes
안녕하세요 도비!
커넥션의 생명 주기 관리, dataSource 주입 위치를
미션에 한정 되어서만 생각했는데, 도비 의견이 좀 더 확장성이 있는 것 같아
동의하게 되네요.

고생 많으셨습니다!

2024-10-29 05:28 UTC, tackyu commented on study/src/test/java/aop/stage0/Stage0Test.java
직접 구현하신 `TransactionHandler`를 사용해서 테스트를 진행해도 좋을 것 같습니다!

2024-10-29 05:28 UTC, merged