[4단계 - JDBC 라이브러리 구현하기] 커찬(이충안) 미션 제출합니다.
woowacourse/java-jdbc pull request #869
Opened 2024-10-14 04:56 UTC by leegwichan

안녕하세요 에버! 커찬입니다.
빠르게 구현해 보았는데 잘 되었는지 모르겠네요;; 리뷰 부탁드리겠습니다!

2024-10-15 16:28 UTC, helenason requested changes
안녕하세요 커찬!

4단계 미션 코드와 학습테스트 코드 리뷰 드립니다.

학습테스트가 통과되지 않아서 리뷰 다시 요청 주시면 관련하여 더 자세히 리뷰 남겨보도록 할게요!

마지막까지 화이팅입니다아 👊

2024-10-15 16:28 UTC, helenason commented on jdbc/src/main/java/com/interface21/transaction/support/TransactionSynchronizationManager.java
> +        }
(저도 받은 리뷰) `ThreadLocal.withInitial()` 라는 메서드를 지원한다고 합니다! 적용해보는 건 어떨까요 ~~~?

2024-10-15 16:28 UTC, helenason commented on study/src/test/java/aop/stage0/TransactionHandler.java
> +        }
단순 질문인데요. 예외 처리를 위와 같이 구현하신 커찬의 의도가 궁금합니다!

2024-10-15 16:28 UTC, helenason commented on study/src/test/java/aop/stage1/Stage1Test.java
> +    }
ProxyFactory라는 클래스로도 프록시 객체를 만들 수 있군요!
저는 ProxyFactoryBean 클래스를 사용하였는데요. 두 클래스의 차이는 무엇일까요? 🤔

2024-10-15 16:28 UTC, helenason commented on study/src/test/java/aop/stage1/TransactionAdvisor.java
>      }
TransactionAdvisor가 구현하고 있는 PointcutAdvisor 내부 코드를 보면, Advisor 인터페이스에서 default로 위 반환값을 true로 지정하고 있는데요.
```java
default boolean isPerInstance() {
    return true;
}
```
어떤 이유로 false로 반환하던 값을 다시 true로 변경하셨나요? 만약, 의도가 있는 코드라면 이미 정의되어있는 default 코드와 동일한 코드이니 재정의는 불필요해보입니다!

2024-10-15 16:28 UTC, helenason commented on study/src/test/java/aop/stage2/AopConfig.java
>  }
<img width="500" alt="image" src="https://github.com/user-attachments/assets/186cee63-3d48-4cf1-9d7d-75fd62d895c0">

학습테스트가 통과되지 않네요! AopConfig 클래스에서 빈을 적절히 설정해봅시다! 👍

2024-10-15 16:28 UTC, helenason commented on study/src/test/java/aop/stage1/TransactionAdvice.java
> +
위 로직은 TransactionPointcut 클래스에서 검증되고 있기 때문에 저는 불필요하다고 판단했는데, 커찬은 어떻게 생각하시나요?

만약 위 로직을 유지하실 생각이라면, getAnnotation()에서 null을 체크하는 로직보다, isAnnotationPresent()로 체크하는 것은 어떨까요?!

2024-10-15 16:28 UTC, helenason commented on study/src/test/java/aop/stage0/Stage0Test.java
> -        final var appUserService = new AppUserService(userDao, stubUserHistoryDao);
커찬은 var 타입을 선호하지 않으시나요? 선호하지 않으신다면 이유가 궁금하네요 ~~~~~~~

2024-10-16 02:30 UTC, leegwichan commented on jdbc/src/main/java/com/interface21/transaction/support/TransactionSynchronizationManager.java
> +        }
에버 리뷰를 적용하니 코드가 간결해지네요 👍

2024-10-16 02:46 UTC, leegwichan commented on study/src/test/java/aop/stage0/TransactionHandler.java
> +        }
`Proxy.newProxyInstance()`로 만든 객체의 타겟에서 예외가 발생하면 발생한 예외를 감싼 `InvocationTargetException`이 발생합니다. 그런데 우리의 요구 사항은 "내부에서 예외가 발생했을 경우, 그 예외를 던져주는 것" 입니다.

그래서 아래와 같이 구성했습니다.
1. `InvocationTargetException` 이 발생한 경우
    1. 내부 Exception이 RuntimeException인 경우 (정상 케이스) : 내부의 예외를 던져주도록 한다.
    2. 내부 Exception이 RuntimeException이 아닌 경우 : 프록시가 잘못된 경우이므로 프록시 예외로 처리
2. 이외의 경우 : 프록시가 잘못된 경우이므로 프록시 예외로 처리

2024-10-16 02:57 UTC, leegwichan commented on study/src/test/java/aop/stage1/Stage1Test.java
> +    }
오! 저는 처음 고민해 보는 주제인데요~ [스택 오버플로우](https://stackoverflow.com/questions/47111867/what-is-the-difference-between-proxyfactory-and-proxyfactorybean-in-spring-frame)에 자료가 있네요.

> ProxyFactory is independently of Spring's IoC container. ProxyFactoryBean is combining Spring AOP with Spring's IoC container.

ProxyFactory는 Spring AOP를 위한 클래스고, ProxyFactoryBean은 Spring AOP와 Spring's IoC container를 위한 클래스네요. 지금과 같이 Spring's IoC container를 안쓰는 상황에서 ProxyFactory를 쓰는 것은 합리적이라 볼 수 있겠네요.

2024-10-16 03:01 UTC, leegwichan commented on study/src/test/java/aop/stage1/TransactionAdvisor.java
>      }
의미 없이 true로 해 놓았었는데 한 번 알아보았습니다.
isPerInstance()는 빈의 모든 인스턴스에 다른 인스턴스의 프록시가 적용되는 지를 물어보는 의미입니다.
같은 인스턴스를 사용하더라도 문제 없으니, 이 값은 false로 되돌려 놓도록 하겠습니다.

2024-10-16 03:05 UTC, leegwichan commented on study/src/test/java/aop/stage1/TransactionAdvice.java
> +
> 위 로직은 TransactionPointcut 클래스에서 검증되고 있기 때문에 저는 불필요하다고 판단했는데, 커찬은 어떻게 생각하시나요?

TransactionAdvice가 항상 TransActionAdvisor에만 사용된다는 보장은 없으니까요. 뭐 어디선가 누군가 다른 로직으로 재사용할 수 있으니, 객체가 분리되어 있다면 여러 곳에서 검증하는 편입니다.

> getAnnotation()에서 null을 체크하는 로직보다, isAnnotationPresent()로 체크하는 것은 어떨까요?!

에버 의견 반영해서 `isAnnotationPresent()`로 변경했습니다!

2024-10-16 03:08 UTC, leegwichan commented on study/src/test/java/aop/stage0/Stage0Test.java
> -        final var appUserService = new AppUserService(userDao, stubUserHistoryDao);
다른 분들은 var는 타입이 길어질 때 사용하시는 것 같은데요. 저는 타입이 길더라도 명시하는 것의 이점이 더 많다고 생각합니다.

개발 초기에 JS를 썼을 때, 해당 객체가 뭔지도 잘 모르고 어떤 메서드가 있는지도 잘 몰라서 고생했던 경험이 있어서;;
무조건적으로 나쁘지 않다고 생각해서 다른 사람이 쓴 코드가 있다면 따라가는 편이지만, 제가 수정하는 코드에 있다면 주로 타입을 명시하는 편입니다~

2024-10-17 17:59 UTC, helenason approved these changes
리뷰 반영된 것과 테스트 모두 통과하는 것 확인하였습니다!

이만 머지하도록 할게요. 커찬 그동안 수고 많으셨어요

다음 미션도 파이팅~~~~~~~

2024-10-17 18:00 UTC, merged