[4단계 - JDBC 라이브러리 구현하기] 카고(정민호) 미션 제출합니다.
woowacourse/java-jdbc pull request #872
Opened 2024-10-14 05:07 UTC by devhoya97

안녕하세요 폴라! 벌써 마지막 미션이네요 🥹

이번 단계를 진행하면서 고민했던 포인트는 하나를 공유하고자 합니다!

Q: JdbcTemplate의 queryForObject()와 같이 조회를 위한 메서드도 Connection을 DataSourceUtils로부터 얻어오는게 좋을까? 즉, 트랜잭션 관리가 필요할까? 데이터를 변경하지 않으니까 조회가 실패해도 rollback을 할 필요가 없으므로 굳이 트랜잭션으로 관리할 필요가 없지 않을까?

그리고 직접 내린 답변은 다음과 같습니다.

A: 트랜잭션1에서 데이터를 변경하고 커밋하기 전에, 트랜잭션2에서 데이터를 조회하면 트랜잭션 격리 수준에 따라 데이터의 일관성을 유지하기 위해 트랜잭션1의 변경 사항이 반영되지 않고 조회될 수 있습니다. 하지만 하나의 트랜잭션 내에서 데이터를 변경 후 조회하는 과정이 있다면, 해당 조회에서는 변경된 사항이 반영되어야 합니다. 이런 과정을 위해선 조회도 하나의 트랜잭션으로 묶여야겠지요. 그래서 조회에서도 트랜잭션이 필요하다는 결론을 내렸습니다!

이에 대한 폴라의 의견이 궁금해요!

이번에도 리뷰 잘 부탁드립니다 🙇‍♂️

2024-10-15 03:48 UTC, jinchiim requested changes
안녕하세요 카고!

리뷰 반영 및 저번 단계에서 말씀하신 대로 몇가지 메서드도 하나로 변경해주셨네요! 👍🏻
잘 학습하신 것 같아 엄청난 리뷰 보다는 간단한 몇가지 질문 드렸으니 편하게 답변 주세요!

마지막 4단계도 열심히 달려봅시다! 🫡

2024-10-15 03:48 UTC, jinchiim commented on app/src/main/java/com/techcourse/service/TxUserService.java
> +        }
트랜잭션을 하는 서비스가 많이 생긴다면 이와 같이 `Connection`의 `commit` 과 `rollback` 을 하는 메서드 와 코드가 중복적으로 발생하지 않을까요?! 🤔

2024-10-15 03:48 UTC, jinchiim commented on app/src/test/java/com/techcourse/service/UserServiceTest.java
> +        assertThat(userService.findById(1L)).isNotEqualTo(newPassword);
`User` 과 비교하고 있는 듯 합니다! 😄

2024-10-15 03:48 UTC, jinchiim commented on study/src/test/java/aop/stage2/AopConfig.java
> +        defaultAdvisorAutoProxyCreator.setProxyTargetClass(true);
꼼꼼히 챙겨주셨네요! 👍🏻

2024-10-15 03:48 UTC, jinchiim commented on study/src/test/java/aop/stage1/TransactionAdvice.java
> +            throw new DataAccessException(e);
구체적인 메시지를 주면 좋겠습니다! ☺️

2024-10-15 03:48 UTC, jinchiim commented on study/src/test/java/aop/stage1/TransactionAdvisor.java
>      @Override
단순 학습을 위한 질문이 될 것 같은데요!
`isPerInstance()`는 무엇이고 카고의 상황에서는 어떻게 설정해야할까요?? 😄

2024-10-16 02:18 UTC, devhoya97 commented on app/src/test/java/com/techcourse/service/UserServiceTest.java
> +        assertThat(userService.findById(1L)).isNotEqualTo(newPassword);
헉 그렇네요. 꼼꼼한 리뷰 감사합니다 👍 반영하였습니다!

2024-10-16 02:30 UTC, devhoya97 commented on app/src/main/java/com/techcourse/service/TxUserService.java
> +        }
좋은 질문이네요! Runnable 인터페이스를 활용하여 트랜잭션 처리 로직 분리하여 재사용성을 고려해봤습니다. 현재 리턴타입이 필요 없는 메서드만 다루므로 Runnable을 활용했는데, 만약 트랜잭션을 하는 서비스 메서드인데 리턴값도 필요하다면 Runnable이 아닌 Supplier 사용을 고려할 것 같습니다!

2024-10-16 02:34 UTC, devhoya97 commented on study/src/test/java/aop/stage1/TransactionAdvice.java
> +            throw new DataAccessException(e);
학습테스트라서 크게 신경 안 쓰고 있었다가 딱 걸렸네요 ㅎㅎ... 아래와 같이 상황에 대한 설명을 추가했습니다!
`throw new DataAccessException("트랜잭션 수행 중 예외가 발생해 롤백합니다.", e);`

2024-10-16 02:46 UTC, devhoya97 commented on study/src/test/java/aop/stage1/TransactionAdvisor.java
>      @Override
오 안 그래도 학습테스트를 하면서 이게 뭐지 하고 넘어갔던 기억이 있는데 짚어주셨네요!

> Return whether this advice is associated with a particular instance (for example, creating a mixin) or shared with all instances of the advised class obtained from the same Spring bean factory.
Note that this method is not currently used by the framework. Typical Advisor implementations always return true. Use singleton/prototype bean definitions or appropriate programmatic proxy creation to ensure that Advisors have the correct lifecycle model.
As of 6.0.10, the default implementation returns true.
Returns:
whether this advice is associated with a particular target instance

Spring bean factory에서 인스턴스를 가져오는데, 가져오는 인스턴스마다 다른 어드바이저가 필요한 경우 true로 설정하는 것 같아요. 현재 학습테스트 상황에서는 Spring bean factory에서 인스턴스를 가져올 때, 인스턴스가 서로 다를 필요도 없고, 서로 다르다고 하더라도 어드바이저가 다를 필요가 없으므로 false로 사용하는게 맞는 것 같습니다!

2024-10-17 05:23 UTC, jinchiim commented on app/src/main/java/com/techcourse/service/TxUserService.java
> +        }
만약 `userService`가 아닌 다른 `Service`가 생긴다먄 어떻게 될까요?!
그때도 여전히 카고는 위 메서드를 써야 하지 않을까요? 😄

2024-10-17 05:23 UTC, jinchiim commented on study/src/test/java/aop/stage1/TransactionAdvisor.java
>      @Override
잘 찾아봐주셨네요!! ☺️

2024-10-17 05:27 UTC, jinchiim commented
저번 리뷰에서 생각만하고 따로 코멘트를 안드렸더라구요 😅

> 트랜잭션1에서 데이터를 변경하고 커밋하기 전에, 트랜잭션2에서 데이터를 조회하면 트랜잭션 격리 수준에 따라 데이터의 일관성을 유지하기 위해 트랜잭션1의 변경 사항이 반영되지 않고 조회될 수 있습니다. 하지만 하나의 트랜잭션 내에서 데이터를 변경 후 조회하는 과정이 있다면, 해당 조회에서는 변경된 사항이 반영되어야 합니다. 이를 위해선 변경과 조회가 하나의 트랜잭션으로 묶여야겠지요. 그래서 조회에서도 트랜잭션이 필요하다는 결론을 내렸습니다!

저도 같은 고민을 이번 미션에서 했었습니다!
조회까지 붙여야 하나? 롤백해도 결과는 똑같을텐데 라는 생각이 들더라고요.

하지만 좀 더 생각해보니 말씀하신 대로 트랜잭션의 격리 수준에 따라서 조회도 결과가 같거나, 달라져야 하더라구요.
그래서 이번 미션에서 조회 메서드에도 같은 컨넥션을 공유하는 트랜잭션이 필요하다는 것에 동의합니다! 😋

2024-10-17 06:32 UTC, jinchiim approved these changes
안녕하세요 카고!
리뷰 잘 반영해주셨습니다!  저번에 제 의견을 단줄 알았는데 머릿속으로 달았더라구요^^...
의견 살포시 달고 머지하겟습니다!
다음 미션도 화이팅하세요!

즐거웠습니다! 😄

2024-10-17 06:32 UTC, merged