[4단계 - Transaction synchronization 적용하기] 무빈(김현중) 미션 제출합니다.
woowacourse/java-jdbc pull request #890
Opened 2024-10-14 06:52 UTC by hjk0761

잉크 안녕하세요!
드디어 마지막 단계입니다.

### 구현 사항
- 서비스 추상화
- Transaction Synchronization 적용

LMS 에서 제시한 미션 요구사항을 만족하는 걸 목표로 미션 진행했습니다!
트랜잭션 관련한 부분이라 테스트 짜는게 너무 어렵더군요 ㅠㅠ
따로 구현하진 못했습니다,,,

마지막까지 리뷰 잘 부탁드립니다!
잉크도 화이팅이에요!!

2024-10-15 14:31 UTC, yechop requested changes
안녕하세요 무빈! 마지막 단계 고생 많으셨습니다
이번 미션 무빈의 코드 보면서 많이 배웠네요.
다 질문이니 코멘트 한번 확인해주시고 무빈 의견에 따라 반영하진 않으셔도 됩니다

2024-10-15 14:31 UTC, yechop commented on jdbc/src/main/java/com/interface21/transaction/support/TransactionSynchronizationManager.java
> +        }
``private static final ThreadLocal<Map<DataSource, Connection>> resources = ThreadLocal.withInitial(HashMap::new);``

생성하면서 초기화하는 방법도 있습니다

2024-10-15 14:31 UTC, yechop commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +            }
트랜젝션이 아닌경우엔 커넥션을 직접 닫아주어야 하는군요?
닫지 않으면 어떻게 되나요?  그리고 트랜젝션일 경우 직접 닫아주지 않아도 되는 이유는 뭘까요?

추가로 메서드명이 isNotTransactionalConnection 이면 가독성이 더 좋을것 같아요!

2024-10-15 15:48 UTC, hjk0761 commented on jdbc/src/main/java/com/interface21/transaction/support/TransactionSynchronizationManager.java
> +        }
이런 방법은 몰랐네요!
바로 적용해 보겠습니다 ㅎㅎ

2024-10-15 15:53 UTC, hjk0761 commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +            }
먼저 트랜잭션인 경우에도 커넥션을 닫아주게 된다면, 트랜잭션 안의 남아있는 작업들은 새로운 커넥션을 받아 수행되거나, 커넥션이 없어 오류를 마주하게 됩니다. 또한 같은 커넥션 아래에서 작업을 수행해야 한 번에 커밋하거나 한 번에 롤백을 수행할 수 있게 됩니다!
트랜잭션이 아닌 경우 커넥션을 닫지 않게 된다면, 이후에 새로운 작업에서 롤백이 수행되면 이전 작업 또한 같이 롤백될 수 있는 위험이 있습니다.

그렇기 때문에 트랜잭션 여부에 따라 커넥션을 닫아주는 방식으로 구현하게 되었습니다!

2024-10-15 15:54 UTC, hjk0761 commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +            }
isTransactionalConnection 메서드가 ! 연산자와만 쓰이기에 네이밍도 not 을 사용하도록 수정했습니다!

2024-10-15 15:56 UTC, hjk0761 commented on app/src/main/java/com/techcourse/service/AppUserService.java
> +        updatePassword(id, newPassword, createBy);
이는 이전에 트랜잭션 처리가 Service 에서 수행될 때의 잔해입니다.
지금 상황에서 두 메서드가 분리될 필요가 없는 것 같아 하나로 합쳐보겠습니다!

2024-10-15 16:03 UTC, hjk0761 commented on app/src/main/java/com/techcourse/service/TxUserService.java
> +        return transactionManager.start(() -> userService.findById(id));
개인적으로 읽기와 쓰기 모든 작업은 트랜잭션을 통해 중간에 값이 바뀌는 경우를 방지해야 한다고 생각합니다.

다만 모든 경우를 트랜잭션으로 처리를 하게 되면 락 때문에 비효율적인 프로그램이 될 것이고, 이를 방지하고자 읽기 작업엔 트랜잭션 격리 레벨을 다르게 두거나 readOnly 등을 통해 무작정 베타 락을 걸고 작업하지 않도록 할 것입니다.

그런 의미에서 트랜잭션을 저장 및 조회 메서드에도 적용해 두었는데, 지금 이런 부분이 구현되지 않은 시점에서 과분한 처사인 것 같기도 합니다!

아무래도 조회 메서드가 자주 불릴수록 더욱 비효율적인 동작을 하게 될 것 이므로 트랜잭션을 제외해 보았습니다!

2024-10-16 12:12 UTC, yechop requested changes
질문 답변들 감사합니다 궁금했던 점들 모두 해소됐어요
이제 마지막으로 aop 학습테스트 올려주세요!

2024-10-16 14:34 UTC, hjk0761 commented
제가 학습테스트를 깜빡 잊고 있었군요...!!
빠르게 구현해서 제출합니다 ㅎㅎ

2024-10-18 09:22 UTC, merged