[4단계 - JDBC 라이브러리 구현하기] 테드(김규태) 미션 제출합니다.
woowacourse/java-jdbc pull request #908
Opened 2024-10-14 08:08 UTC by Kimprodp

안녕하세요 리니~

미션 마지막 단계 진행하여 리뷰 요청 드립니다😊

Connection 객체를 비즈니스 로직과 분리하기 위해 TransactionManager를 사용했습니다.
TransactionManager를 통해 모든 비즈니스 로직이 자동으로 트랜잭션이 관리되고, TransactionSynchronizationManager를 통해 스레드 간 동일한 커넥션을 사용할 수 있도록 구현했습니다.

이번에도 리뷰 잘 부탁드립니다!

2024-10-14 16:18 UTC, linirini requested changes
테드~! 우선은 학습 테스트 외 미션 코드 관련하여 리뷰 남깁니다!
다음 리뷰 요청 때 AOP 학습 테스트도 함께 반영하여 요청해주세요:>
마지막까지 화이팅해봐요👊

2024-10-14 16:18 UTC, linirini commented on jdbc/src/main/java/com/interface21/transaction/support/TransactionManager.java
> +            throw new DataAccessException(e);
RuntimeException 중에는 비즈니스 로직에 의해 던져진 예외도 있을 것 같은데요!
그 예외들까지 모두 DataAccessException으로 포장된다면 비즈니스 예외와 데이터베이스 예외가 명확하게 구분되지 않을 것 같아요:)

2024-10-14 16:18 UTC, linirini commented on jdbc/src/main/java/com/interface21/transaction/support/TransactionSynchronizationManager.java
>      private static final ThreadLocal<Map<DataSource, Connection>> resources = new ThreadLocal<>();
`ThreadLocal.withInitial(HashMap::new)`를 활용하면 아래 메서드들의 로직을 더 간단하게 만들 수 있을 것 같아요:)

2024-10-14 16:18 UTC, linirini commented on jdbc/src/main/java/com/interface21/transaction/support/TransactionSynchronizationManager.java
>      private static final ThreadLocal<Map<DataSource, Connection>> resources = new ThreadLocal<>();
질문) ThreadLocal은 무엇인가요? ThreadLocal의 장점은 무엇일까요? ThreadLocal을 사용할 때 주의할 점은 무엇이 있을까요?

2024-10-14 16:18 UTC, linirini commented on app/src/main/java/com/techcourse/service/AppUserService.java
> +    public AppUserService(UserDao userDao, final UserHistoryDao userHistoryDao) {
final 사용을 맞춰주세요:)

2024-10-15 08:53 UTC, Kimprodp commented on jdbc/src/main/java/com/interface21/jdbc/datasource/DataSourceUtils.java
>              connection.close();
dataResource 만을 받는 것이 아닌, connection도 같이 보내고 있기 때문에 만약 getConnection() 를 통해 커넥션이 TransactionSynchronizationManager에 저장되었으나, 이 클래스를 사용하는 곳에서 새로 dataSource.getConnection()를 하여 새로운 커넥션을 보낸다면 TransactionSynchronizationManager.unbindResource(dataSource) 에서 반환된 커넥션과 다를 수 있다고 생각해요.

어떤 경우든 DataSourceUtils 입장에서 releaseConnection의 용도는 전달된 커넥션을 해제하는 것이기 때문에 전달된 커넥션이 다른 경우에도 모두 닫은 것으로 구현했습니다!

2024-10-15 09:06 UTC, Kimprodp commented on jdbc/src/main/java/com/interface21/transaction/support/TransactionManager.java
> +            throw new DataAccessException(e);
서비스의 비즈니스 로직은도 여기서 처리되겠군요.. 😢 수정했습니다!

2024-10-15 13:47 UTC, Kimprodp commented on app/src/main/java/com/techcourse/service/AppUserService.java
> +    public AppUserService(UserDao userDao, final UserHistoryDao userHistoryDao) {
빼먹었네요 반영했습니다!

2024-10-18 13:55 UTC, Kimprodp commented
안녕하세요 리니!

다른 일정들이 일부 겹쳐 리뷰 반영이 늦어졌는데, 이해해주셔서 감사해요.
이전에 코멘트 주신 것들과 학습 테스트까지 해서 다시 요청 드립니다😊

2024-10-19 09:05 UTC, linirini commented on jdbc/src/main/java/com/interface21/jdbc/datasource/DataSourceUtils.java
>              connection.close();
해당 방식으로 하면 커넥션을 더 잘 관리할 수 있겠네요👍

2024-10-19 10:06 UTC, linirini requested changes
테드-! 안녕하세요
곧 있으면 마지막 데모데이네요, 아무래도 요구사항과 미션을 병행하려니 바쁜 것 같아요🥲
코멘트 반영해주신 부분 확인했습니다! 그리고 학습 테스트에 대해 학습 차원에서 질문을 좀 남겨보았어요.! 저에게도 AOP는 너무 어려운 개념이다보니 학습에 도움될만한 질문일지 잘 모르겠네요😅
선택적으로 학습하시고, 답변 남겨주셔도 좋을 것 같습니다!
마지막까지 화이팅입니다~!

2024-10-19 10:06 UTC, linirini commented on study/src/test/java/aop/stage1/TransactionAdvice.java
> +public class TransactionAdvice implements MethodInterceptor {
Advice를 구현하기 위해 MethodInterceptor를 사용하는데요, 해당 클래스는 무엇이며, 왜 사용하나요?

2024-10-22 14:07 UTC, Kimprodp commented on jdbc/src/main/java/com/interface21/jdbc/datasource/DataSourceUtils.java
> +            if (releasedConnection != null && !releasedConnection.isClosed()) {
오 가독성이 더 좋은 것 같네요 😊👍

2024-10-22 14:07 UTC, Kimprodp commented on jdbc/src/main/java/com/interface21/transaction/support/TransactionManager.java
> +            throw new DataAccessException(e);
RuntimeException 도 catch 해서 롤백하도록 변경했습니다!

2024-10-22 14:13 UTC, Kimprodp commented on study/src/test/java/aop/stage2/AopConfig.java
> +    public DefaultAdvisorAutoProxyCreator proxyCreator() {
JDK Dynamic Proxy와 CGLIB 모두 사용합니다.

JDK Dynamic Proxy : 인터페이스 기반(인터페이스를 구현하고 있는 클래스) 프록시 객체를 동적으로 생성할 때 사용
CGLIB : 인터페이스를 구현하지 않는 클래스의 프록시 객체를 생성할 때 사용

2024-10-22 14:21 UTC, Kimprodp commented on study/src/test/java/aop/stage2/AopConfig.java
> +        defaultAdvisorAutoProxyCreator.setProxyTargetClass(true);
DefaultAdvisorAutoProxyCreator가 aop 대상 클래스의 프록시 객체를 생성하는 역할을 하는데요. 밑에 spring에서 사용하는 프록시 종류에서 설명드린 것처럼 대상에 따라 사용하는 프록시 종류가 다르기 때문에 setProxyTargetClass() 메서드를 통해서 선택해주어야 합니다.

기본값은 false 이고, JDK Dynamic Proxy를 사용합니다.
true로 설정한다면 CGLIB를 사용합니다.

현재 코드에서는 프록시 대상이 인터페이스를 구현하고 있지 않기 때문에 false로 설정한다면 대상의 프록시를 생성하지 못하게 됩니다 😊

2024-10-22 14:46 UTC, Kimprodp commented on study/src/test/java/aop/stage1/TransactionAdvice.java
> +public class TransactionAdvice implements MethodInterceptor {
TransactionPointcut에서 정의된 메서드가 실행되면 advice의 invoke()가 실행됩니다. (이걸 물어보신게 맞는지 모르겠어요.. ㅎ)

2024-10-22 14:50 UTC, Kimprodp commented on study/src/test/java/aop/stage1/TransactionAdvice.java
> +public class TransactionAdvice implements MethodInterceptor {
MethodInterceptor는 이름에서 알 수 있듯이 메서드가 호출될 때 가로채는 기능을 합니다. aop를 사용하는 목적이 대상의 메서드 실행 전후에 부가 기능을 추가하는 것이므로 MethodInterceptor의 invoke()를 통해서 메서드를 가로채고, 인자로 전달되는 MethodInvocation의 proceed()를 전후로 부가 기능을 정의할 수 있습니다.

2024-10-22 14:51 UTC, Kimprodp commented
리니, 주신 피드백 반영과 학습에 대한 질문을 학습하고 답변을 달아봤습니다! 확인 부탁드릴게요 😊

2024-10-23 17:27 UTC, linirini commented on study/src/test/java/aop/stage1/TransactionAdvice.java
> +public class TransactionAdvice implements MethodInterceptor {
Advice가 적용될 수 있는 시점에 대해서 학습해보면 좋을 것 같아서 질문드렸습니다!
읽어보면 좋을만한 레퍼런스도 함께 남길게요👍
https://www.geeksforgeeks.org/aspect-oriented-programming-and-aop-in-spring-framework/

2024-10-23 17:28 UTC, linirini commented on jdbc/src/main/java/com/interface21/transaction/support/TransactionManager.java
> +            throw e;
😆👍

2024-10-23 17:29 UTC, linirini approved these changes
테드~ 마지막 데모데이를 앞두고 많이 바쁘시죠 ㅎㅎ
마지막까지 리뷰 반영하시느라 정말 수고많으셨습니다!
이만 JDBC 미션은 마무리해보려고 합니다:)
남은 미션도 화이팅! 런칭데이도 화이팅👊

2024-10-23 17:29 UTC, merged