[4단계 - JDBC 라이브러리 구현하기] 잉크(이예찬) 미션 제출합니다.
woowacourse/java-jdbc pull request #909
Opened 2024-10-14 08:10 UTC by yechop

안녕하세요 카고
마감 기한에 맞춰 리뷰를 조절해주신 덕분에 수월하게 이번 미션 진행했습니다.
마지막 단계도 잘 부탁드립니다~

2024-10-16 02:15 UTC, devhoya97 requested changes
안녕하세요 잉크! 마지막 미션도 잘 구현해주셨네요~ 간단한 코멘트 남겼는데 확인해주시면 감사하겠습니다!

이번 리뷰요청에는 학습테스트가 포함되어있지 않은 것 같아요. 다음 리뷰요청시 학습테스트까지 포함해주시면 감사하겠습니다!! :)

2024-10-16 02:15 UTC, devhoya97 commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +        try(PreparedStatement pstmt = conn.prepareStatement(sql)) {
try와 괄호 사이를 한 칸 띄워야겠네요 :)

2024-10-16 02:15 UTC, devhoya97 commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
>      public <T> T queryForObject(final String sql, RowMapper<T> rowMapper, final PreparedStatementSetter preparedStatementSetter) {
queryForObject의 결과가 1이 아니면 예외를 던지는 사이즈 검증이 있었던 것 같은데, 어느 순간 사라진 것 같아요!

2024-10-19 10:31 UTC, yechop commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
>      public <T> T queryForObject(final String sql, RowMapper<T> rowMapper, final PreparedStatementSetter preparedStatementSetter) {
검증을 추가했습니다!

2024-10-20 13:43 UTC, devhoya97 approved these changes
학습테스트 부분에서 아~주 간단한 코멘트 남겼으니 편하실 때 확인해주시면 감사하겠습니다!

레벨4가 거의 막바지에 왔는데, 남은 기간도 응원하겠습니다! 함께 화이팅하시죠 :)

2024-10-20 13:43 UTC, devhoya97 commented on study/src/test/java/aop/stage0/TransactionHandler.java
> +        }
코드를 보면 RuntimeException까지 catch해서 DataAccessException으로 다시 던져주고 있어요. RuntimeException은 아마 method.invoke() 과정에서 발생할 수 있을 것 같은데 이를 DataAccessException으로 포장해서 다시 던지는 이유가 궁금합니다!

예를 들어 트랜잭션에 감싸져 있는 메서드에서 특정 비즈니스 로직 때문에 IllegalArgumentException을 던지고 있다면, 해당 예외가 여기서 catch되어 DataAccessException으로 다시 던져질 것 같은데, IllegalArgumentException이 그대로 던져지는게 더 자연스럽지 않나 싶어서 여쭤봅니다!

2024-10-20 13:43 UTC, devhoya97 commented on study/src/test/java/aop/stage1/Stage1Test.java
> +        UserService userService = (UserService) proxyFactoryBean.getObject();
아래 테스트코드에서도 반복되고 있으니, ProxyFactoryBean를 필드로 두고 BeforeEach로 초기화하도록 리팩토링 해볼 수 있을 것 같아요! 다만 학습테스트에서는 이러한 리팩토링을 신경쓰기보다는 AOP의 동작원리를 학습하는데 더 시간을 쓰는게 맞는 것 같아서 굳이 반영하실 필요는 없고, 읽고 넘어가주세요 ㅎㅎ

2024-10-20 13:44 UTC, merged