[4단계 - Transaction synchronization 적용하기] 레디(최동근) 미션 제출합니다.
woowacourse/java-jdbc pull request #919
Opened 2024-10-14 08:37 UTC by reddevilmidzy

안녕하세요 초코칩!

2024-10-15 00:42 UTC, Chocochip101 requested changes
마지막까지 미션 완성하느라 수고하셨습니다 🙌🏻

구현 잘해주셔서, 작은 리뷰 남겼습니다 😄 

테스트 실행되게 수정해주시고 다시 리뷰 요청해주세요!

cf. 혹시 aop 학습 테스트는 진행 안하시는 걸까요?

2024-10-15 00:42 UTC, Chocochip101 commented on app/src/main/java/com/techcourse/service/TxUserService.java
> +    private final UserService userService;
```suggestion
    private static final Logger log = LoggerFactory.getLogger(TxUserService.class);
    
    private final UserService userService;
```

2024-10-15 00:42 UTC, Chocochip101 commented on jdbc/src/main/java/com/interface21/transaction/support/TransactionSynchronizationManager.java
> +        RESOURCES.remove();
안쓰이는 메서드인데, 작성해주신 이유가 있나요?

2024-10-30 10:06 UTC, reddevilmidzy commented
리뷰 반영 늦어져서 죄송합니다,, aop 학습 테스트도 추가하였습니다!

2024-10-31 02:05 UTC, Chocochip101 approved these changes
잘 적용주셨네요~

수고많으셨습니다 :)

2024-10-31 02:05 UTC, merged