[4단계 - JDBC 라이브러리 구현하기] 안나(김민겸) 미션 제출합니다.
woowacourse/java-jdbc pull request #920
Opened 2024-10-14 08:40 UTC by Mingyum-Kim

안녕하세요 애쉬! 4단계로 다시 돌아왔습니다.

다소 급하게 구현한 감이 있어 완성도가 낮을 것 같아요. 
리뷰 남겨주시면 빠르게 처리하겠습니다. 🙇‍♀️🙇‍♀️ 

잘 부탁드립니다!

2024-10-15 10:31 UTC, ashsty requested changes
안녕하세요 안나~

짧은 시간 안에도 기본적으로 깔끔하게 코드 잘 짜주신 것 같아요.

간단한 코멘트 몇 가지 남겨두었습니다.
다음 제출 때는 `Transactional` 학습 테스트 + `AOP` 학습 테스트까지 함께 제출해주시면 될 것 같아요.

마지막까지 화이팅~~!

2024-10-15 10:31 UTC, ashsty commented on study/src/main/java/aop/service/AppUserService.java
> +@Primary
`@Primary` 어노테이션을 추가해주신 이유가 있을까요? 👀

2024-10-15 10:31 UTC, ashsty commented on study/src/main/java/aop/service/TransactionHandler.java
> +        }
[질문] 이 분기를 추가해주셨네요! 따로 처리하고 계신 이유가 뭘까요?
(저는 이렇게 처리하지 않아서, 이유가 궁금해요!)

2024-10-15 10:31 UTC, ashsty commented on jdbc/src/main/java/com/interface21/transaction/support/TransactionManager.java
> +            throw new JdbcTemplateException("트랜잭션 롤백 중 예외가 발생했습니다.", e);
롤백 예외 처리까지 👍

2024-10-15 10:31 UTC, ashsty commented on app/src/main/java/com/techcourse/service/UserService.java
인터페이스를 활용해 `App`과 `Tx` 클래스를 분리했는데도 해당 클래스가 남아있네요!
특별한 이유가 있을까요? 👀

2024-10-15 10:31 UTC, ashsty commented on app/src/test/java/com/techcourse/service/UserServiceTest.java
> +        final var userService = new UserService(dataSource, userDao, userHistoryDao);
이 테스트는 `UserService`가 인터페이스로 바뀌기 전, 기존 서비스 로직을 테스트하고 있는 것 같아요.
의도하신 걸까요? 👀

2024-10-15 10:31 UTC, ashsty commented on app/src/main/java/com/techcourse/service/TxUserService.java
> +    public TxUserService(final TransactionManager transactionManager, final UserServiceInterface userService) {
제가 받았던 리뷰 공유드려요!

`TxUserService`의 파라미터로 `TxUserService`가 들어올 수 있는 경우는 없을까요? 🤔

2024-10-15 10:31 UTC, ashsty commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +        Connection connection = DataSourceUtils.getConnection(dataSource);
`TxUserService`에서 트랜잭셔널을 사용하지 않는 메서드(ex.insert)의 경우 
`Connection`이 해제되지 않을 것 같아요.

이런 경우는 어떻게 처리할 수 있을까요? 👀

2024-10-16 02:11 UTC, Mingyum-Kim commented on study/src/main/java/aop/service/AppUserService.java
> +@Primary
처음에 TransactionHandler를 만들 때 `@Component` 어노테이션을 추가하고 스프링의 IoC Container를 사용해서 빈 등록을 했었어요. 그런데 UserService가 인터페이스이고 구현하는 클래스가 2개 이상이다보니 빈 주입 에러가 생기더라고요 😢 그래서 테스트 통과를 위해 임시 방편으로 AppUserService를 사용했어요. 
컴파일 타임에 등록할 빈을 지정하는 것이 좋은 설계는 아닐 것 같아, 스프링 사용을 제거하고 직접 주입해주도록 변경하였습니다. 👍

2024-10-16 02:15 UTC, Mingyum-Kim commented on study/src/main/java/aop/service/TransactionHandler.java
> +        }
`@Transactional`이 추가된 메서드라면 트랜잭션을 적용하여 메서드를 호출하고, 그렇지 않다면 바로 호출하는 방식을 적용하기 위해 분기문을 추가했습니다. 
그런데 이제 보니 분기문 조건이 잘못 된 것같네요 😢 트랜잭션이 잘 적용될 수 있도록 분기문을 수정하였습니다!

2024-10-16 02:45 UTC, Mingyum-Kim commented on app/src/main/java/com/techcourse/service/UserService.java
기존 코드를 건들지 않고 인터페이스와 AppUserService와 TxUserService를 만들려고 하였습니다. 
그런데 생각해보니 기존 UserService를 리팩토링한 형태로 만든거라 필요가 없겠네요! UserService는 제거하였습니다. 👍

2024-10-16 02:48 UTC, Mingyum-Kim commented on app/src/test/java/com/techcourse/service/UserServiceTest.java
> +        final var userService = new UserService(dataSource, userDao, userHistoryDao);
아니요!! 누락하였습니다 😢😢 AppUserService를 사용해 테스트하도록 변경하였어요.

2024-10-16 11:37 UTC, Mingyum-Kim commented on jdbc/src/main/java/com/interface21/transaction/support/TransactionSynchronizationManager.java
> +        resources.get().put(key, value);
오호 그러네요 😀 
통일성을 위해 `resource`로 분리하고 사용하였습니다 !

2024-10-16 11:51 UTC, Mingyum-Kim commented on app/src/main/java/com/techcourse/service/TxUserService.java
> +    public TxUserService(final TransactionManager transactionManager, final UserServiceInterface userService) {
헉 ㅠㅠ 지금 설계에서는 충분히 가능성 있어보여요! 
실제로 테스트코드에서 TxUserService의 파라미터에 TxUserService의 객체를 넣고 돌려보았는데 참조 방향에 따라 앞선 TxUserService서 커넥션이 닫힌 뒤 다른 TxUserService에서 커넥션을 호출하면서 오류가 생기는 것 같아요. 

![image](https://github.com/user-attachments/assets/4bba77f2-d535-4161-b086-16e70365731b)

TxUserService를 생성하는 시점에서 본인을 의존하고 있지 않도록 예외처리를 해야겠어요. 감사합니다!

2024-10-16 12:08 UTC, Mingyum-Kim commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +        Connection connection = DataSourceUtils.getConnection(dataSource);
커넥션을 사용해 update 후 Connection을 반납하려면 JdbcTemplate의 각 쿼리문을 INSERT한 뒤 바로 `finally` 구문에서 닫아주는 게 제일 명확한데요 😅 그럼 TxUserService에서 여러 작업을 한 커넥션에서 사용할 수 없더라고요.
AppUserService에서 각 SQL 쿼리문을 날릴 때마다 커넥션을 닫아주어야 한다는 것은 인지하고 있지만 방법이 떠오르지 않습니다 😥 
혹시 애쉬가 정답을 알고 있다면 힌트를 주실 수 있을까요?

2024-10-31 12:45 UTC, ashsty commented on jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
> +        Connection connection = DataSourceUtils.getConnection(dataSource);
저는 `JdbcTemplate`에서 커넥션을 열기 전에, 
`DataSourceutils` 클래스에서 이미 열려 있는 커넥션이 있는지 확인하고 분기 처리를 해주었어요.
(=트랜잭션을 사용하고 있는 메서드인지)

- 열려 있는 커넥션이 있다면: 커넥션 닫지 않고 반납 (트랜잭션을 처리하며 닫힐 테니)
- 없다면: 커넥션 닫음

하지만 저도 썩 마음에 드는 해답은 아닌지라... 🥹
안나만의 방법을 찾게 된다면 좋겠네요!

2024-10-31 12:48 UTC, merged